# LightRAG × HotpotQA（distractor）最小实验

这个 Notebook 以共享语料库方式在 HotpotQA 上运行 LightRAG，并输出可断点续跑的逐题结果与 Answer EM/F1。它参考了所给 Notebook 的**数据采样、持久化和评测接口**，但不复用其中 GraphRAG 或单题向量检索的方法实现。

实验设定：从 `validation` 中固定随机抽取 hard + bridge 样本；汇总这些样本全部候选段落并按标题去重；用该共享语料建立一次 LightRAG 索引；再逐题查询。它是 *closed-corpus distractor* 实验，不等同于 HotpotQA FullWiki 排行榜设定。

> 提醒：实体/关系抽取会产生大量 LLM 调用。先以 `NUM_QUESTIONS=25` 做冒烟测试，确认后再改为 200。

In [ ]:
# 在 Colab/Jupyter 的新环境中执行一次。完成后请重启内核。
%pip install -q "lightrag-hku" datasets pandas tqdm openai

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.7/53.7 kB 2.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 1.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.8/4.8 MB 51.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.9/50.9 kB 3.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.3/175.3 kB 7.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 840.2/840.2 kB 27.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.8/89.8 kB 3.4 MB/s eta 0:00:00

In [ ]:
import asyncio
from functools import partial
import json
import os
import re
import shutil
import string
import time
from collections import Counter
from getpass import getpass
from pathlib import Path

import pandas as pd
from datasets import load_dataset
from tqdm.auto import tqdm

# 不把密钥写入 Notebook 或磁盘。也可在运行前由终端设置 OPENAI_API_KEY。
if not os.environ.get('OPENAI_API_KEY'):
    os.environ['OPENAI_API_KEY'] = getpass('OpenAI API key: ').strip()
if not os.environ['OPENAI_API_KEY']:
    raise ValueError('OPENAI_API_KEY 不能为空')

# 先跑小样本，确认成本、依赖与权限正常后再设为 200。
NUM_QUESTIONS = 200
RANDOM_SEED = 42
CHAT_MODEL = 'gpt-4o-mini'
ANSWER_NORMALIZER_MODEL = 'gpt-4o-mini'  # 仅负责把冗长回答压缩为最终答案
EMBEDDING_MODEL = 'text-embedding-3-small'  # openai_embed 的默认模型
QUERY_MODES = ['hybrid']  # 完整比较可改为 ['naive', 'local', 'global', 'hybrid']
PROJECT_ROOT = Path('hotpot_lightrag')
DATA_DIR = PROJECT_ROOT / 'experiment_data'
RAG_DIR = PROJECT_ROOT / 'lightrag_store'
DATA_DIR.mkdir(parents=True, exist_ok=True)
RAG_DIR.mkdir(parents=True, exist_ok=True)
print({'NUM_QUESTIONS': NUM_QUESTIONS, 'modes': QUERY_MODES, 'root': str(PROJECT_ROOT)})

OpenAI API key: ··········
{'NUM_QUESTIONS': 200, 'modes': ['hybrid'], 'root': 'hotpot_lightrag'}

## 1. 固定评测题目并建立共享语料

不能为每个问题只插入该题的十个候选段落，否则没有测试共享知识库检索能力。这里模仿参考 GraphRAG Notebook：选定问题后，把它们的候选段落合并、按标题去重并建立一次索引。标题被保留在正文中，方便图谱抽取跨文档实体关系。

In [ ]:
QUESTIONS_PATH = DATA_DIR / 'questions.json'
CORPUS_PATH = DATA_DIR / 'corpus.jsonl'

def prepare_hotpot_subset(num_questions=NUM_QUESTIONS, seed=RANDOM_SEED):
    dataset = load_dataset('hotpotqa/hotpot_qa', 'distractor', split='validation')
    subset = (dataset
              .filter(lambda row: row['level'] == 'hard' and row['type'] == 'bridge')
              .shuffle(seed=seed)
              .select(range(min(num_questions, len(dataset)))))

    docs_by_title, questions = {}, []
    for row in subset:
        questions.append({
            'id': row['id'],
            'question': row['question'],
            'answer': row['answer'],
            'supporting_facts': row['supporting_facts'],
        })
        for title, sentences in zip(row['context']['title'], row['context']['sentences']):
            text = ' '.join(sentence.strip() for sentence in sentences if sentence.strip()).strip()
            # 同标题有多个版本时，保留更完整的一份。
            if len(text) > len(docs_by_title.get(title, '')):
                docs_by_title[title] = text

    corpus = [
        {'doc_id': f'hotpot-{i:06d}', 'title': title, 'text': text}
        for i, (title, text) in enumerate(sorted(docs_by_title.items()))
    ]
    QUESTIONS_PATH.write_text(json.dumps(questions, ensure_ascii=False, indent=2), encoding='utf-8')
    with CORPUS_PATH.open('w', encoding='utf-8') as handle:
        for doc in corpus:
            handle.write(json.dumps(doc, ensure_ascii=False) + '\n')
    return questions, corpus

questions, corpus = prepare_hotpot_subset()
print(f'questions={len(questions)}, unique candidate documents={len(corpus)}')
print(corpus[0]['title'])
print(corpus[0]['text'][:300])

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/9.52k [00:00<?, ?B/s]

distractor/train-00000-of-00002.parquet: reconstructing file:   0%|          |  0.00B /  166MB

distractor/train-00000-of-00002.parquet: downloading bytes:           |  0.00B

distractor/train-00001-of-00002.parquet: reconstructing file:   0%|          |  0.00B /  166MB

distractor/train-00001-of-00002.parquet: downloading bytes:           |  0.00B

distractor/validation-00000-of-00001.par(…): reconstructing file:   0%|          |  0.00B / 27.5MB

distractor/validation-00000-of-00001.par(…): downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/90447 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/7405 [00:00<?, ? examples/s]

Filter:   0%|          | 0/7405 [00:00<?, ? examples/s]

questions=200, unique candidate documents=1986
(I Can't Make It) Another Day
"(I Can't Make It) Another Day" is a song by American recording artist Michael Jackson featuring Lenny Kravitz, released on the posthumous album "Michael" which has sold 6.5 million globally. Initially leaked as a 90-second snippet, it was referred to as "Another Day". Shortly after the leak, singer

## 2. 初始化并建立 LightRAG 索引

官方 SDK 适合此类研究/评测用途。`naive` 是纯 chunk 向量检索，`local`、`global`、`hybrid` 会使用知识图谱；因此在相同索引与同一题集上切换模式即可形成内部对照。若更改采样、模型、embedding 或 chunk 参数，请删除 `hotpot_lightrag/lightrag_store` 后重新索引；本 Notebook 不会自动删除已有索引。

In [ ]:
from lightrag import LightRAG, QueryParam
from lightrag.llm.openai import openai_complete, openai_embed
from lightrag.utils import EmbeddingFunc

INDEX_META_PATH = RAG_DIR / 'hotpot_index_meta.json'

def render_document(doc):
    return f"Document ID: {doc['doc_id']}\nTitle: {doc['title']}\nContent: {doc['text']}"

# 每个 Wikipedia 标题段落作为独立文档插入，保留来源边界与可追溯性。
# 不要把整个 corpus 拼成一个长字符串；否则 LightRAG 会把它记为 1 个 full document。
corpus_texts = [render_document(doc) for doc in corpus]
corpus_ids = [doc['doc_id'] for doc in corpus]

# 保留 LightRAG 所需的 embedding_dim/max_token_size 元数据，同时固定模型。
# 若切换为 text-embedding-3-large，须相应改为 EMBEDDING_DIM = 3072 并重建索引。
EMBEDDING_DIM = 1536
embedding_func = EmbeddingFunc(
    embedding_dim=EMBEDDING_DIM,
    max_token_size=8192,
    func=partial(openai_embed.func, model=EMBEDDING_MODEL),
)

async def build_or_load_rag():
    rag = LightRAG(
        working_dir=str(RAG_DIR),
        llm_model_func=openai_complete,
        llm_model_name=CHAT_MODEL,
        embedding_func=embedding_func,
        chunk_token_size=800,
        chunk_overlap_token_size=100,
        llm_model_max_async=4,
        addon_params={'language': 'English'},
    )
    await rag.initialize_storages()

    expected_meta = {
        'num_questions': NUM_QUESTIONS, 'seed': RANDOM_SEED,
        'chat_model': CHAT_MODEL, 'embedding_model': EMBEDDING_MODEL,
        'num_documents': len(corpus), 'insertion_mode': 'one-document-per-title',
    }
    if INDEX_META_PATH.exists():
        actual_meta = json.loads(INDEX_META_PATH.read_text(encoding='utf-8'))
        if actual_meta != expected_meta:
            raise RuntimeError(
                '当前索引与配置不一致。请删除 lightrag_store 后重新执行本节，以免混用索引。'
            )
        print('检测到与当前配置一致的索引，直接加载。')
    else:
        started = time.time()
        await rag.ainsert(corpus_texts, ids=corpus_ids)
        INDEX_META_PATH.write_text(json.dumps(expected_meta, indent=2), encoding='utf-8')
        print(f'索引完成：{(time.time() - started) / 60:.1f} 分钟')
    return rag

rag = await build_or_load_rag()

流式输出内容被截断，只能显示最后 5000 行内容。
INFO: Upserting relation VDB: `Cherokee Campground->Tagg Run Campground`
INFO: Upserting relation VDB: `Common Well->Toland`
INFO: Upserting relation VDB: `Duplex Houses->Toland`
INFO: Upserting relation VDB: `Toland->Toland Community`
INFO: Upserting relation VDB: `Clay Bank->Toland`
INFO: Upserting relation VDB: `One-Room School House->Toland`
INFO: Upserting relation VDB: `Clay Bank->Sand Pit Operation`
INFO: Upserting relation VDB: `Families of Toland->Toland`
INFO: Phase 2 relation processing completed for hotpot-001798: edges=21 added_entities=0
INFO: Completed merging: 26 entities, 0 extra entities, 21 relations
INFO: [] entities flush: embedding 17 vectors in 2 batch(es) (batch_num=10)
INFO: [] relationships flush: embedding 21 vectors in 3 batch(es) (batch_num=10)
INFO: [] chunks flush: embedding 1 vectors in 1 batch(es) (batch_num=10)
INFO: [] Writing graph with 11568 nodes, 12111 edges
INFO: In memory DB persist to disk
INFO: Completed processing file 299/486: unknown_source
INFO: Extracting stage 304/486: unknown_source
INFO: Processing d-id: hotpot-001803
INFO: Chunking F(legacy): size=800, split_only=False, overlap=100, doc_id: hotpot-001803
INFO: Parsing (native): hotpot-001917
INFO:  == LLM cache == saving: default:extract:60455670a4174fbefad696d4197d21e0
INFO:  == LLM cache == saving: default:extract:0680aca6f8ace73f01d247156675e9c4
INFO: Chunk 1 of 1 extracted 10 Ent + 8 Rel hotpot-001802-chunk-000
INFO: Merging stage 303/486: unknown_source
INFO: Phase 0: Writing recovery indexes for hotpot-001802: 10 candidate entities, 8 candidate relations
INFO:  == LLM cache == saving: default:extract:3cb10bb887af79feb0a20b77da15aeb0
INFO: Phase 1: Processing 10 entities from hotpot-001802 (async: 8)
INFO: Merged: `Quebec` | 4+1
INFO: Merged: `Vermont` | 3+1
INFO: Phase 2: Processing 8 relations from hotpot-001802 (async: 8)
INFO: Upserting relation VDB: `Tomifobia Nature Trail->Tomifobia River`
INFO: Upserting relation VDB: `Lake Massawippi->Tomifobia Nature Trail`
INFO: Upserting relation VDB: `Beebe Plain->Tomifobia Nature Trail`
INFO: Upserting relation VDB: `Ayer's Cliff->Tomifobia Nature Trail`
INFO: Upserting relation VDB: `Stanstead->Tomifobia Nature Trail`
INFO: Upserting relation VDB: `Tomifobia Nature Trail->Vermont`
INFO: Upserting relation VDB: `Car Parking Lots->Tomifobia Nature Trail`
INFO: Upserting relation VDB: `Tomifobia Nature Trail->Wildlife Observation`
INFO: Phase 2 relation processing completed for hotpot-001802: edges=8 added_entities=0
INFO: Completed merging: 10 entities, 0 extra entities, 8 relations
INFO: [] entities flush: embedding 10 vectors in 1 batch(es) (batch_num=10)
INFO: [] relationships flush: embedding 8 vectors in 1 batch(es) (batch_num=10)
INFO: [] chunks flush: embedding 1 vectors in 1 batch(es) (batch_num=10)
INFO: [] Writing graph with 11576 nodes, 12119 edges
INFO:  == LLM cache == saving: default:extract:f5058bc2eed3b63ef830fbe3091262f5
INFO: Chunk 1 of 1 extracted 22 Ent + 9 Rel hotpot-001801-chunk-000
INFO: Merging stage 302/486: unknown_source
INFO: Phase 0: Writing recovery indexes for hotpot-001801: 22 candidate entities, 9 candidate relations
INFO: Phase 1: Processing 22 entities from hotpot-001801 (async: 8)
INFO: In memory DB persist to disk
INFO:  == LLM cache == saving: default:extract:dbae96e869274b1e0600c9a6f23fc0dc
INFO: Completed processing file 303/486: unknown_source
INFO: Extracting stage 305/486: unknown_source
INFO: Processing d-id: hotpot-001804
INFO: Chunking F(legacy): size=800, split_only=False, overlap=100, doc_id: hotpot-001804
INFO: Parsing (native): hotpot-001918
INFO: Phase 2: Processing 9 relations from hotpot-001801 (async: 8)
INFO: Upserting relation VDB: `Gunnison River->Tomichi Creek`
INFO: Upserting relation VDB: `Monarch Pass->Tomichi Creek`
INFO: Upserting relation VDB: `Sargents->Tomichi Creek`
INFO: Upserting relation VDB: `Agape Creek->Tomichi Creek`
INFO: Upserting relation VDB: `Long Branch Creek->Tomichi Creek`
INFO: Upserting relation VDB: `Needle Creek Reservoir->Tomichi Creek`
INFO: Upserting relation VDB: `Hot Springs Reservoir->Tomichi Creek`
INFO:  == LLM cache == saving: default:extract:f8bd4ddfaa984c6e3e34dbfd861fed07
INFO: Chunk 1 of 1 extracted 5 Ent + 5 Rel hotpot-001803-chunk-000
INFO: Merging stage 304/486: unknown_source
INFO: Phase 0: Writing recovery indexes for hotpot-001803: 5 candidate entities, 5 candidate relations
INFO: Upserting relation VDB: `Cochetopa Creek->Tomichi Creek`
INFO: Phase 1: Processing 5 entities from hotpot-001803 (async: 8)
INFO: Upserting relation VDB: `Quartz Creek->Tomichi Creek`
INFO: Merged: `Toni Braxton` | 6+1
INFO: Phase 2 relation processing completed for hotpot-001801: edges=9 added_entities=0
INFO: Completed merging: 22 entities, 0 extra entities, 9 relations
INFO: Merged: `Flamingo Las Vegas` | 1+1
INFO: [] entities flush: embedding 27 vectors in 3 batch(es) (batch_num=10)
INFO: [] relationships flush: embedding 9 vectors in 1 batch(es) (batch_num=10)
INFO: [] chunks flush: embedding 1 vectors in 1 batch(es) (batch_num=10)
INFO: [] Writing graph with 11601 nodes, 12128 edges
INFO: Phase 2: Processing 5 relations from hotpot-001803 (async: 8)
INFO: Upserting relation VDB: `Toni Braxton->Toni Braxton: Revealed`
INFO: In memory DB persist to disk
INFO: Completed processing file 302/486: unknown_source
INFO: Extracting stage 306/486: unknown_source
INFO: Processing d-id: hotpot-001805
INFO: Chunking F(legacy): size=800, split_only=False, overlap=100, doc_id: hotpot-001805
INFO: Upserting relation VDB: `The Showroom->Toni Braxton: Revealed`
INFO: Parsing (native): hotpot-001919
INFO: Upserting relation VDB: `April 6, 2008->Toni Braxton: Revealed`
INFO: Upserting relation VDB: `Flamingo Las Vegas->The Showroom`
INFO: Upserting relation VDB: `Flamingo Las Vegas->Toni Braxton`
INFO: Phase 2 relation processing completed for hotpot-001803: edges=5 added_entities=0
INFO: Completed merging: 5 entities, 0 extra entities, 5 relations
INFO: [] relationships flush: embedding 5 vectors in 1 batch(es) (batch_num=10)
INFO: [] chunks flush: embedding 1 vectors in 1 batch(es) (batch_num=10)
INFO: [] Writing graph with 11601 nodes, 12133 edges
INFO:  == LLM cache == saving: default:extract:30a64c548d3a8d1dd44b3b829639348c
INFO: In memory DB persist to disk
INFO: Completed processing file 304/486: unknown_source
INFO: Extracting stage 307/486: unknown_source
INFO: Processing d-id: hotpot-001806
INFO: Chunking F(legacy): size=800, split_only=False, overlap=100, doc_id: hotpot-001806
INFO: Parsing (native): hotpot-001920
INFO:  == LLM cache == saving: default:extract:a5b3b06c6028487b9bd60e3be4b3d9b3
INFO:  == LLM cache == saving: default:extract:45253cd0ccc34e5b8f05377909232ed6
INFO: Chunk 1 of 1 extracted 11 Ent + 9 Rel hotpot-001804-chunk-000
INFO: Merging stage 305/486: unknown_source
INFO: Phase 0: Writing recovery indexes for hotpot-001804: 11 candidate entities, 9 candidate relations
INFO: Phase 1: Processing 11 entities from hotpot-001804 (async: 8)
INFO: Merged: `Groom Dry Lake` | 1+1
INFO: Merged: `Area 51` | 3+1
INFO: Merged: `Nevada Test and Training Range` | 1+1
INFO: Phase 2: Processing 9 relations from hotpot-001804 (async: 8)
INFO: Upserting relation VDB: `Tonopah->Tonopah Test Range`
INFO: Upserting relation VDB: `Nellis Range->Tonopah Test Range`
INFO: Upserting relation VDB: `Groom Dry Lake->Tonopah Test Range`
INFO: Upserting relation VDB: `Conspiracy Theorists->Tonopah Test Range`
INFO: Upserting relation VDB: `Nuclear Weapons Stockpile Reliability Testing->Tonopah Test Range`
INFO: Upserting relation VDB: `Research and Development of Fusing and Firing Systems->Tonopah Test Range`
INFO: Upserting relation VDB: `Testing Nuclear Weapon Delivery Systems->Tonopah Test Range`
INFO: Upserting relation VDB: `Restricted Area R-4809->Tonopah Test Range`
INFO: Upserting relation VDB: `Nevada Test and Training Range->Restricted Area R-4809`
INFO: Phase 2 relation processing completed for hotpot-001804: edges=9 added_entities=0
INFO: Completed merging: 11 entities, 0 extra entities, 9 relations
INFO: [] entities flush: embedding 11 vectors in 2 batch(es) (batch_num=10)
INFO: [] relationships flush: embedding 9 vectors in 1 batch(es) (batch_num=10)
INFO: [] chunks flush: embedding 1 vectors in 1 batch(es) (batch_num=10)
INFO: [] Writing graph with 11609 nodes, 12142 edges
INFO:  == LLM cache == saving: default:extract:b77fde4530467a9b7c404f0699f701cb
INFO: Chunk 1 of 1 extracted 3 Ent + 6 Rel hotpot-001805-chunk-000
INFO: Merging stage 306/486: unknown_source
INFO: Phase 0: Writing recovery indexes for hotpot-001805: 7 candidate entities, 6 candidate relations
INFO: Phase 1: Processing 3 entities from hotpot-001805 (async: 8)
INFO: Merged: `Tony McCoy` | 1+1
INFO: Merged: `Northern Ireland` | 5+1
INFO:  == LLM cache == saving: default:extract:f3d91cda05c9ba922c6b1cd631d9c485
INFO: In memory DB persist to disk
INFO: Phase 2: Processing 6 relations from hotpot-001805 (async: 8)
INFO: Completed processing file 305/486: unknown_source
INFO: Extracting stage 308/486: unknown_source
INFO: Processing d-id: hotpot-001807
INFO: Chunking F(legacy): size=800, split_only=False, overlap=100, doc_id: hotpot-001807
INFO: Chunks appended from relation: `Ireland`
INFO: Parsing (native): hotpot-001921
INFO: Upserting relation VDB: `Ireland->Tony McCoy`
INFO: Chunks appended from relation: `UK`
INFO: Upserting relation VDB: `Tony McCoy->UK`
INFO: Upserting relation VDB: `4,358 winners->Tony McCoy`
INFO: Upserting relation VDB: `20 consecutive times->Tony McCoy`
INFO: Upserting relation VDB: `Northern Ireland->Tony McCoy`
INFO: Upserting relation VDB: `4,358->Tony McCoy`
INFO: Phase 2 relation processing completed for hotpot-001805: edges=6 added_entities=2
INFO: Completed merging: 3 entities, 2 extra entities, 6 relations
INFO: [] entities flush: embedding 7 vectors in 1 batch(es) (batch_num=10)
INFO: [] relationships flush: embedding 6 vectors in 1 batch(es) (batch_num=10)
INFO: [] chunks flush: embedding 1 vectors in 1 batch(es) (batch_num=10)
INFO: [] Writing graph with 11612 nodes, 12148 edges
INFO:  == LLM cache == saving: default:extract:208a783559ff50e3aee1734cd7be9e44
INFO: Chunk 1 of 1 extracted 4 Ent + 3 Rel hotpot-001806-chunk-000
INFO: Merging stage 307/486: unknown_source
INFO: Phase 0: Writing recovery indexes for hotpot-001806: 4 candidate entities, 3 candidate relations
INFO: Phase 1: Processing 4 entities from hotpot-001806 (async: 8)
INFO: In memory DB persist to disk
INFO:  == LLM cache == saving: default:extract:09a1087bc41f860e08bf27fd1a9a66e2
INFO: Phase 2: Processing 3 relations from hotpot-001806 (async: 8)
INFO: Completed processing file 306/486: unknown_source
INFO: Extracting stage 309/486: unknown_source
INFO: Processing d-id: hotpot-001808
INFO: Chunking F(legacy): size=800, split_only=False, overlap=100, doc_id: hotpot-001808
INFO: Parsing (native): hotpot-001922
INFO: Upserting relation VDB: `Coti-Chiavari->Torra Di Capu Di Muru`
INFO: Upserting relation VDB: `Corsica->Torra Di Capu Di Muru`
INFO: Upserting relation VDB: `Genoese Tower->Torra Di Capu Di Muru`
INFO: Phase 2 relation processing completed for hotpot-001806: edges=3 added_entities=0
INFO: Completed merging: 4 entities, 0 extra entities, 3 relations
INFO: [] entities flush: embedding 4 vectors in 1 batch(es) (batch_num=10)
INFO: [] relationships flush: embedding 3 vectors in 1 batch(es) (batch_num=10)
INFO: [] chunks flush: embedding 1 vectors in 1 batch(es) (batch_num=10)
INFO: [] Writing graph with 11616 nodes, 12151 edges
INFO:  == LLM cache == saving: default:extract:f41578919cef7ebe8fa4ca46909e05c9
INFO: Chunk 1 of 1 extracted 4 Ent + 4 Rel hotpot-001807-chunk-000
INFO: Merging stage 308/486: unknown_source
INFO: Phase 0: Writing recovery indexes for hotpot-001807: 4 candidate entities, 4 candidate relations
INFO: Phase 1: Processing 4 entities from hotpot-001807 (async: 8)
INFO: Merged: `Corsica` | 1+1
INFO:  == LLM cache == saving: default:extract:b47b08085c9ba4ebd4e58ca4f0e68d44
INFO: In memory DB persist to disk
INFO: Phase 2: Processing 4 relations from hotpot-001807 (async: 8)
INFO: Completed processing file 307/486: unknown_source
INFO: Extracting stage 310/486: unknown_source
INFO: Processing d-id: hotpot-001809
INFO: Chunking F(legacy): size=800, split_only=False, overlap=100, doc_id: hotpot-001809
INFO: Upserting relation VDB: `Torra Di Fautea->Zonza`
INFO: Parsing (native): hotpot-001923
INFO: Upserting relation VDB: `Corsica->Zonza`
INFO: Upserting relation VDB: `Punta Di Fautea->Torra Di Fautea`
INFO: Upserting relation VDB: `Corsica->Punta Di Fautea`
INFO: Phase 2 relation processing completed for hotpot-001807: edges=4 added_entities=0
INFO: Completed merging: 4 entities, 0 extra entities, 4 relations
INFO: [] entities flush: embedding 4 vectors in 1 batch(es) (batch_num=10)
INFO: [] relationships flush: embedding 4 vectors in 1 batch(es) (batch_num=10)
INFO: [] chunks flush: embedding 1 vectors in 1 batch(es) (batch_num=10)
INFO: [] Writing graph with 11619 nodes, 12155 edges
INFO:  == LLM cache == saving: default:extract:54fe34d8fa76552461dc3d29e0b36c09
INFO: Chunk 1 of 1 extracted 5 Ent + 5 Rel hotpot-001808-chunk-000
INFO: Merging stage 309/486: unknown_source
INFO: Phase 0: Writing recovery indexes for hotpot-001808: 5 candidate entities, 5 candidate relations
INFO: Phase 1: Processing 5 entities from hotpot-001808 (async: 8)
INFO: In memory DB persist to disk
INFO:  == LLM cache == saving: default:extract:8b8d37c9f866316cf760207dd079d465
INFO: Merged: `Corsica` | 2+1
INFO: Completed processing file 308/486: unknown_source
INFO: Merged: `Genoese Tower` | 1+1
INFO: Extracting stage 311/486: unknown_source
INFO: Processing d-id: hotpot-001810
INFO: Chunking F(legacy): size=800, split_only=False, overlap=100, doc_id: hotpot-001810
INFO: Phase 2: Processing 5 relations from hotpot-001808 (async: 8)
INFO: Parsing (native): hotpot-001924
INFO: Upserting relation VDB: `Sartène->Torra Di Roccapina`
INFO:  == LLM cache == saving: default:extract:76c8cc2b406830e9eb990d522f06fc53
INFO: Chunk 1 of 1 extracted 4 Ent + 4 Rel hotpot-001809-chunk-000
INFO: Merging stage 310/486: unknown_source
INFO: Phase 0: Writing recovery indexes for hotpot-001809: 4 candidate entities, 4 candidate relations
INFO: Upserting relation VDB: `Corsica->Torra Di Roccapina`
INFO: Phase 1: Processing 4 entities from hotpot-001809 (async: 8)
INFO: Upserting relation VDB: `Cappu Di Roccapina->Torra Di Roccapina`
INFO: Upserting relation VDB: `Corsica->Sartène`
INFO: Merged: `Corsica` | 3+1
INFO: Phase 2: Processing 4 relations from hotpot-001809 (async: 8)
INFO: Upserting relation VDB: `Genoese Tower->Torra Di Roccapina`
INFO: Phase 2 relation processing completed for hotpot-001808: edges=5 added_entities=0
INFO: Completed merging: 5 entities, 0 extra entities, 5 relations
INFO: [] entities flush: embedding 8 vectors in 1 batch(es) (batch_num=10)
INFO: [] relationships flush: embedding 5 vectors in 1 batch(es) (batch_num=10)
INFO: [] chunks flush: embedding 1 vectors in 1 batch(es) (batch_num=10)
INFO: [] Writing graph with 11625 nodes, 12160 edges
INFO: Upserting relation VDB: `Bonifacio->Torra Di Sant'Amanza`
INFO: In memory DB persist to disk
INFO:  == LLM cache == saving: default:extract:e30b9de173abe0e2afaeb578a7c8b0c3
INFO: Completed processing file 309/486: unknown_source
INFO: Extracting stage 312/486: unknown_source
INFO: Processing d-id: hotpot-001811
INFO: Chunking F(legacy): size=800, split_only=False, overlap=100, doc_id: hotpot-001811
INFO: Upserting relation VDB: `Corsica->Torra Di Sant'Amanza`
INFO: Parsing (native): hotpot-001925
INFO: Upserting relation VDB: `Punta Di U Capicciolu->Torra Di Sant'Amanza`
INFO: Upserting relation VDB: `Bonifacio->Corsica`
INFO: Phase 2 relation processing completed for hotpot-001809: edges=4 added_entities=0
INFO: Completed merging: 4 entities, 0 extra entities, 4 relations
INFO: [] relationships flush: embedding 4 vectors in 1 batch(es) (batch_num=10)
INFO: [] chunks flush: embedding 1 vectors in 1 batch(es) (batch_num=10)
INFO: [] Writing graph with 11625 nodes, 12164 edges
INFO:  == LLM cache == saving: default:extract:7dce456d7d3ebe72b8e79c3b35a219e2
INFO: Chunk 1 of 1 extracted 4 Ent + 4 Rel hotpot-001810-chunk-000
INFO: Merging stage 311/486: unknown_source
INFO: Phase 0: Writing recovery indexes for hotpot-001810: 4 candidate entities, 4 candidate relations
INFO: Phase 1: Processing 4 entities from hotpot-001810 (async: 8)
INFO: Merged: `Sartène` | 1+1
INFO: Merged: `Corsica` | 4+1
INFO: Merged: `Genoese Tower` | 2+1
INFO: Phase 2: Processing 4 relations from hotpot-001810 (async: 8)
INFO: Upserting relation VDB: `Sartène->Torra Di Senetosa`
INFO: In memory DB persist to disk
INFO:  == LLM cache == saving: default:extract:d8f6e4cec3b0aec95cd77f16a707f1e7
INFO: Completed processing file 310/486: unknown_source
INFO: Extracting stage 313/486: unknown_source
INFO: Processing d-id: hotpot-001812
INFO: Chunking F(legacy): size=800, split_only=False, overlap=100, doc_id: hotpot-001812
INFO: Upserting relation VDB: `Corsica->Torra Di Senetosa`
INFO: Parsing (native): hotpot-001926
INFO: Merged: `Corsica`~`Sartène` | 1+1
INFO: Upserting relation VDB: `Genoese Tower->Torra Di Senetosa`
INFO: Upserting relation VDB: `Corsica->Sartène`
INFO: Phase 2 relation processing completed for hotpot-001810: edges=4 added_entities=0
INFO: Completed merging: 4 entities, 0 extra entities, 4 relations
INFO: [] entities flush: embedding 4 vectors in 1 batch(es) (batch_num=10)
INFO: [] relationships flush: embedding 4 vectors in 1 batch(es) (batch_num=10)
INFO: [] chunks flush: embedding 1 vectors in 1 batch(es) (batch_num=10)
INFO: [] Writing graph with 11626 nodes, 12167 edges
INFO:  == LLM cache == saving: default:extract:8ea65f16a4993852400d10e0a11d86d6
INFO: Chunk 1 of 1 extracted 5 Ent + 4 Rel hotpot-001811-chunk-000
INFO: Merging stage 312/486: unknown_source
INFO: Phase 0: Writing recovery indexes for hotpot-001811: 5 candidate entities, 4 candidate relations
INFO: Phase 1: Processing 5 entities from hotpot-001811 (async: 8)
INFO: In memory DB persist to disk
INFO: Merged: `Sartène` | 2+1
INFO:  == LLM cache == saving: default:extract:d3c086b951f903b285013f5f728b595a
INFO: Merged: `Corsica` | 5+1
INFO: Merged: `Barbary Pirates` | 1+1
INFO: Completed processing file 311/486: unknown_source
INFO: Phase 2: Processing 4 relations from hotpot-001811 (async: 8)
INFO: Extracting stage 314/486: unknown_source
INFO: Processing d-id: hotpot-001813
INFO: Chunking F(legacy): size=800, split_only=False, overlap=100, doc_id: hotpot-001813
INFO: Parsing (native): hotpot-001927
INFO: Upserting relation VDB: `Sartène->Torra Di Tizzà`
INFO: Upserting relation VDB: `Corsica->Torra Di Tizzà`
INFO: Upserting relation VDB: `Republic Of Genoa->Torra Di Tizzà`
INFO: Upserting relation VDB: `Barbary Pirates->Republic Of Genoa`
INFO: Phase 2 relation processing completed for hotpot-001811: edges=4 added_entities=0
INFO: Completed merging: 5 entities, 0 extra entities, 4 relations
INFO: [] entities flush: embedding 5 vectors in 1 batch(es) (batch_num=10)
INFO: [] relationships flush: embedding 4 vectors in 1 batch(es) (batch_num=10)
INFO: [] chunks flush: embedding 1 vectors in 1 batch(es) (batch_num=10)
INFO: [] Writing graph with 11628 nodes, 12171 edges
INFO:  == LLM cache == saving: default:extract:f515c4ae334a8f2057b3cade5df7dbe2
INFO: Chunk 1 of 1 extracted 5 Ent + 6 Rel hotpot-001812-chunk-000
INFO: Merging stage 313/486: unknown_source
INFO: Phase 0: Writing recovery indexes for hotpot-001812: 5 candidate entities, 6 candidate relations
INFO: Phase 1: Processing 5 entities from hotpot-001812 (async: 8)
INFO: Merged: `Corsica` | 6+1
INFO: In memory DB persist to disk
INFO:  == LLM cache == saving: default:extract:9d7b3484a47fc5e7809c7b4fe32cafd1
INFO: Phase 2: Processing 6 relations from hotpot-001812 (async: 8)
INFO: Completed processing file 312/486: unknown_source

索引完成：197.8 分钟

In [ ]:
# 冒烟测试：先检查一个问题的输出，再进行批量评测。
example = questions[0]
response = await rag.aquery(
    example['question'],
    param=QueryParam(
        mode='hybrid', top_k=20, chunk_top_k=8, enable_rerank=False,
        response_type='Return only one short final answer, without explanation or citations.',
    ),
)
print('Question:', example['question'])
print('Gold:', example['answer'])
print('LightRAG:', response)

INFO: keyword LLM func: 4 new workers initialized (Timeouts: Func: 240s, Worker: 480s, Health Check: 495s)
INFO:  == LLM cache == saving: hybrid:keywords:038c91fbc4db4094dff2fad3d4e53fda
INFO: Query nodes: young woman, yellow shawl (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 32 relations
INFO: Query edges: Dutch painter, domestic interior scenes, middle class life, Louvre Paris (top_k:20, cosine:0.2)
INFO: Global query: 26 entites, 20 relations
INFO: Raw search results: 44 entities, 49 relations, 0 vector chunks
INFO: After truncation: 44 entities, 49 relations
INFO: Selecting 38 from 38 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 49 relations
INFO: Round-robin merged chunks: 38 -> 38 (deduplicated 0)
INFO: Final context: 44 entities, 49 relations, 8 chunks
INFO: Final chunks S+F/O: E5/1 E3/2 E3/3 E5/4 E4/5 E7/6 E2/7 E2/8
INFO: query LLM func: 4 new workers initialized (Timeouts: Func: 240s, Worker: 480s, Health Check: 495s)
INFO:  == LLM cache == saving: hybrid:query:a66ffad0694d29dbd2e76d41feb27c03

Question: What Dutch painter specialized in domestic interior scenes of middle class life and has a painting of a young woman dressed in a yellow shawl in the Louvre, Paris?
Gold: Johannes Vermeer
LightRAG: The Dutch painter who specialized in domestic interior scenes of middle-class life and has a painting of a young woman dressed in a yellow shawl in the Louvre, Paris, is Johannes Vermeer. This painting is titled "The Lacemaker."

### References
- [1] The Lacemaker (Vermeer)
- [2] Johannes Vermeer

## 3. 批量查询（支持断点续跑）

每种查询模式分别写入 JSONL；已成功完成的 `(mode, id)` 不会重复请求。中断后直接重跑此单元格即可。

In [ ]:
PREDICTIONS_PATH = DATA_DIR / 'lightrag_predictions.jsonl'

def completed_pairs(path):
    if not path.exists():
        return set()
    pairs = set()
    for line in path.read_text(encoding='utf-8').splitlines():
        try:
            row = json.loads(line)
            if row.get('status') == 'ok':
                pairs.add((row['mode'], row['id']))
        except json.JSONDecodeError:
            pass
    return pairs

async def answer_question(question, mode):
    result = await rag.aquery(
        question,
        param=QueryParam(
            mode=mode, top_k=20, chunk_top_k=8, enable_rerank=False,
            response_type='Return only one short final answer, without explanation or citations.',
        ),
    )
    return str(result).strip()

done = completed_pairs(PREDICTIONS_PATH)
for mode in QUERY_MODES:
    for item in tqdm(questions, desc=f'LightRAG {mode}'):
        if (mode, item['id']) in done:
            continue
        started = time.time()
        record = {
            'id': item['id'], 'mode': mode, 'question': item['question'],
            'gold_answer': item['answer'], 'seconds': None,
        }
        try:
            record['prediction'] = await answer_question(item['question'], mode)
            record['status'] = 'ok'
        except Exception as error:
            record['prediction'] = ''
            record['status'] = 'error'
            record['error'] = repr(error)
        record['seconds'] = round(time.time() - started, 3)
        with PREDICTIONS_PATH.open('a', encoding='utf-8') as handle:
            handle.write(json.dumps(record, ensure_ascii=False) + '\n')
        print(f"[{mode}] {item['id']} | {record['status']} | {record['prediction']!r}")

print('Saved:', PREDICTIONS_PATH)

LightRAG hybrid:   0%|          | 0/200 [00:00<?, ?it/s]

INFO: Query nodes: young woman, yellow shawl (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 32 relations
INFO: Query edges: Dutch painter, domestic interior scenes, middle class life, Louvre Paris (top_k:20, cosine:0.2)
INFO: Global query: 26 entites, 20 relations
INFO: Raw search results: 44 entities, 49 relations, 0 vector chunks
INFO: After truncation: 44 entities, 49 relations
INFO: Selecting 38 from 38 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 49 relations
INFO: Round-robin merged chunks: 38 -> 38 (deduplicated 0)
INFO: Final context: 44 entities, 49 relations, 8 chunks
INFO: Final chunks S+F/O: E5/1 E3/2 E3/3 E5/4 E4/5 E7/6 E2/7 E2/8
INFO:  == LLM cache == Query cache hit, using cached response as query result

[hybrid] 5ac47d7355429919431739b3 | ok | 'The Dutch painter who specialized in domestic interior scenes of middle-class life and has a painting of a young woman dressed in a yellow shawl in the Louvre, Paris, is Johannes Vermeer. This painting is titled "The Lacemaker."\n\n### References\n- [1] The Lacemaker (Vermeer)\n- [2] Johannes Vermeer'

INFO:  == LLM cache == saving: hybrid:keywords:f47b4b82a06adc03123acc23800c727b
INFO: Query nodes: Aughton Park railway station, Northern Line, Liverpool (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 40 relations
INFO: Query edges: transportation, railway stations, geography (top_k:20, cosine:0.2)
INFO: Global query: 33 entites, 20 relations
INFO: Raw search results: 50 entities, 57 relations, 0 vector chunks
INFO: After truncation: 50 entities, 57 relations
INFO: Selecting 40 from 40 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 57 relations
INFO: Round-robin merged chunks: 40 -> 40 (deduplicated 0)
INFO: Final context: 50 entities, 57 relations, 8 chunks
INFO: Final chunks S+F/O: E6/1 E7/2 E6/3 E3/4 E2/5 E3/6 E2/7 E1/8
INFO:  == LLM cache == saving: hybrid:query:5fbf736295258c4cc7dd5e7e739bcadd

[hybrid] 5ab7f27e5542991d322237d6 | ok | 'Aughton Park railway station is located approximately 11½ miles (19 km) northeast of Liverpool Central. \n\n### References\n- [1] Aughton Park railway station'

INFO:  == LLM cache == saving: hybrid:keywords:8f00f79917211b49bedc060ac02ba7e2
INFO: Query nodes: The Enormous Radio, son (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 26 relations
INFO: Query edges: author, short story (top_k:20, cosine:0.2)
INFO: Global query: 30 entites, 20 relations
INFO: Raw search results: 49 entities, 45 relations, 0 vector chunks
INFO: After truncation: 49 entities, 45 relations
INFO: Selecting 31 from 31 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 45 relations
INFO: Round-robin merged chunks: 31 -> 31 (deduplicated 0)
INFO: Final context: 49 entities, 45 relations, 8 chunks
INFO: Final chunks S+F/O: E4/1 E5/2 E4/3 E2/4 E2/5 E3/6 E3/7 E7/8
INFO:  == LLM cache == saving: hybrid:query:97f3076c8c8e3210400c16ebdc8761b7

[hybrid] 5a72160e55429971e9dc9253 | ok | 'The son of the author of the short story "The Enormous Radio," John Cheever, is Benjamin Cheever. \n\n### References\n\n- [1] John Cheever\n- [2] The Enormous Radio'

INFO:  == LLM cache == saving: hybrid:keywords:07eeb2491f79eaf55020fed3a2d51fad
INFO: Query nodes: member, nickname (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 23 relations
INFO: Query edges: Dru Hill, cartoon character (top_k:20, cosine:0.2)
INFO: Global query: 21 entites, 20 relations
INFO: Raw search results: 41 entities, 43 relations, 0 vector chunks
INFO: After truncation: 41 entities, 43 relations
INFO: Selecting 36 from 36 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 43 relations
INFO: Round-robin merged chunks: 36 -> 36 (deduplicated 0)
INFO: Final context: 41 entities, 43 relations, 8 chunks
INFO: Final chunks S+F/O: E5/1 E9/2 E3/3 E4/4 E3/5 E4/6 E3/7 E2/8
INFO:  == LLM cache == saving: hybrid:query:2d098c4d28d136b2138f7a410ce2f7ae

[hybrid] 5aba89d555429901930fa816 | ok | 'One of the members of Dru Hill, Woody Rock, is nicknamed after the cartoon character Woody Woodpecker.'

INFO:  == LLM cache == saving: hybrid:keywords:f34dd035fec3bdcf4170905c8d772ef1
INFO: Query nodes: Four Seasons of Love (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 46 relations
INFO: Query edges: music industry, record sales, singer (top_k:20, cosine:0.2)
INFO: Global query: 31 entites, 20 relations
INFO: Raw search results: 50 entities, 65 relations, 0 vector chunks
INFO: After truncation: 50 entities, 65 relations
INFO: Selecting 125 from 131 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 65 relations
INFO: Round-robin merged chunks: 125 -> 125 (deduplicated 0)
INFO: Final context: 50 entities, 65 relations, 8 chunks
INFO: Final chunks S+F/O: E6/1 E3/2 E3/3 E3/4 E4/5 E4/6 E3/7 E2/8
INFO:  == LLM cache == saving: hybrid:query:f3d2c24f5fe21409e8a7acdd088a94f4

[hybrid] 5ab78a445542992aa3b8c826 | ok | 'I do not have enough information to answer.'

INFO:  == LLM cache == saving: hybrid:keywords:78db638c69f0bbcce26586375c50d23f
INFO: Query nodes: Wong Fei-hung (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 42 relations
INFO: Query edges: film, director, Wong Fei-hung (top_k:20, cosine:0.2)
INFO: Global query: 19 entites, 20 relations
INFO: Raw search results: 25 entities, 44 relations, 0 vector chunks
INFO: After truncation: 25 entities, 44 relations
INFO: Selecting 9 from 9 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 44 relations
INFO: Round-robin merged chunks: 9 -> 9 (deduplicated 0)
INFO: Final context: 25 entities, 44 relations, 8 chunks
INFO: Final chunks S+F/O: E12/1 E6/2 E3/3 E3/4 E4/5 E4/6 E1/7 E3/8
INFO:  == LLM cache == saving: hybrid:query:95b2ecce9cacfcf48312bbbfe572259d

[hybrid] 5abcf9d155429959677d6b90 | ok | 'The director of a film about Wong Fei-hung, Sammo Hung, also directed the film "Warriors Two." \n\n### References\n* [1] Warriors Two'

INFO:  == LLM cache == saving: hybrid:keywords:cadbfc996e5ce396d284e8c3f9972f66
INFO: Query nodes: city, location (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 49 relations
INFO: Query edges: Bishop Carroll Catholic High School, Kapaun Mt. Carmel Catholic High School, Kansas (top_k:20, cosine:0.2)
INFO: Global query: 22 entites, 20 relations
INFO: Raw search results: 42 entities, 69 relations, 0 vector chunks
INFO: After truncation: 42 entities, 69 relations
INFO: Selecting 44 from 44 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 69 relations
INFO: Round-robin merged chunks: 44 -> 44 (deduplicated 0)
INFO: Final context: 42 entities, 69 relations, 8 chunks
INFO: Final chunks S+F/O: E4/1 E5/2 E8/3 E4/4 E1/5 E3/6 E1/7 E2/8
INFO:  == LLM cache == saving: hybrid:query:6065dafc02bc44cb7a29568d8a8ba639

[hybrid] 5a7ddc5a5542995f4f4022da | ok | 'Both Bishop Carroll Catholic High School and Kapaun Mt. Carmel Catholic High School are located in Wichita, Kansas. \n\n### References\n\n- [1] Bishop Carroll Catholic High School\n- [2] Kapaun Mt. Carmel Catholic High School'

INFO:  == LLM cache == saving: hybrid:keywords:fd1571c1d62dcb5afe544cf9a13c3ef3
INFO: Query nodes: Luke Rockhold (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 34 relations
INFO: Query edges: MMA, UFC, champion (top_k:20, cosine:0.2)
INFO: Global query: 26 entites, 20 relations
INFO: Raw search results: 37 entities, 43 relations, 0 vector chunks
INFO: After truncation: 37 entities, 43 relations
INFO: Selecting 9 from 9 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 43 relations
INFO: Round-robin merged chunks: 9 -> 9 (deduplicated 0)
INFO: Final context: 37 entities, 43 relations, 8 chunks
INFO: Final chunks S+F/O: E8/1 E4/2 E3/3 E9/4 E5/5 E8/6 E4/7 E3/8
INFO:  == LLM cache == saving: hybrid:query:5e271784d2469b497a265b4a18ad0fc6

[hybrid] 5ae14b5c55429920d52343aa | ok | 'Luke Rockhold defeated Chris Weidman, who was the first fighter to earn a win against Anderson Silva in the UFC. \n\n### References\n\n- [1] Luke Rockhold\n- [2] Chris Weidman'

INFO:  == LLM cache == saving: hybrid:keywords:c83dea41da417b1b3474c3f1abea5919
INFO: Query nodes: Where Blood and Fire Bring Rest (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 21 relations
INFO: Query edges: novel, movie, Stanley Kubrick, album (top_k:20, cosine:0.2)
INFO: Global query: 21 entites, 20 relations
INFO: Raw search results: 41 entities, 41 relations, 0 vector chunks
INFO: After truncation: 41 entities, 41 relations
INFO: Selecting 23 from 23 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 41 relations
INFO: Round-robin merged chunks: 23 -> 23 (deduplicated 0)
INFO: Final context: 41 entities, 41 relations, 8 chunks
INFO: Final chunks S+F/O: E8/1 E5/2 E2/3 E4/4 E2/5 E2/6 E6/7 E2/8
INFO:  == LLM cache == saving: hybrid:query:d91a4a044466e6f3e43383695ea807db

[hybrid] 5adfb78f5542995ec70e9081 | ok | 'The novel that the movie "The Shining," directed by Stanley Kubrick and sampled in the album "Where Blood and Fire Bring Rest," was based on was written by Stephen King. \n\n### References\n- [1] The Shining (film)\n- [2] Where Blood and Fire Bring Rest'

INFO:  == LLM cache == saving: hybrid:keywords:5de21cf1d94d8efc8a61e175bdea1252
INFO: Query nodes: Maxi, Dick, Twink, daughter (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 42 relations
INFO: Query edges: Irish entertainer, girl band (top_k:20, cosine:0.2)
INFO: Global query: 25 entites, 20 relations
INFO: Raw search results: 42 entities, 59 relations, 0 vector chunks
INFO: After truncation: 42 entities, 59 relations
INFO: Selecting 37 from 37 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 59 relations
INFO: Round-robin merged chunks: 37 -> 37 (deduplicated 0)
INFO: Final context: 42 entities, 59 relations, 8 chunks
INFO: Final chunks S+F/O: E7/1 E2/2 E4/3 E5/4 E1/5 E4/6 E2/7 E1/8
INFO:  == LLM cache == saving: hybrid:query:2dd8244c02799fa08494ac2de95f1847

[hybrid] 5a722fae55429971e9dc9343 | ok | 'The daughter of the Irish entertainer in the girl band Maxi, Dick and Twink, is named Chloë Agnew. \n\n### References\n\n- [1] Adele King\n- [2] Maxi, Dick and Twink'

INFO:  == LLM cache == saving: hybrid:keywords:186cbeb42efeb2bf3de2a61a8ecd0a5f
INFO: Query nodes: year, appearance (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 33 relations
INFO: Query edges: South Korean drama film, high school, Baek Bong-ki (top_k:20, cosine:0.2)
INFO: Global query: 29 entites, 20 relations
INFO: Raw search results: 49 entities, 53 relations, 0 vector chunks
INFO: After truncation: 49 entities, 53 relations
INFO: Selecting 41 from 41 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 53 relations
INFO: Round-robin merged chunks: 41 -> 41 (deduplicated 0)
INFO: Final context: 49 entities, 53 relations, 8 chunks
INFO: Final chunks S+F/O: E4/1 E4/2 E3/3 E3/4 E4/5 E2/6 E4/7 E4/8
INFO:  == LLM cache == saving: hybrid:query:0b4ef85b262f7f71192cfb982a02f211

[hybrid] 5abf1e825542997ec76fd3cb | ok | 'Baek Bong-ki appeared in the South Korean drama film set in a high school, "Once Upon a Time in High School," in the year 2004.\n\n### References\n\n- [1] Baek Bong-ki\n- [2] Once Upon a Time in High School'

INFO:  == LLM cache == saving: hybrid:keywords:bb19ddd756ad413caa015ed310f02775
WARNING: low_level_keywords is empty
INFO: Query edges: river, tributary, Frenchmans Creek (top_k:20, cosine:0.2)
INFO: Global query: 29 entites, 20 relations
INFO: Raw search results: 29 entities, 20 relations, 0 vector chunks
INFO: After truncation: 29 entities, 20 relations
INFO: Selecting 11 from 11 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 20 relations
INFO: Round-robin merged chunks: 11 -> 11 (deduplicated 0)
INFO: Final context: 29 entities, 20 relations, 8 chunks
INFO: Final chunks S+F/O: E3/1 E2/2 E3/3 E2/4 E6/5 E2/6 E6/7 E3/8
INFO:  == LLM cache == saving: hybrid:query:296bff9c874e95cc0105d09ca651e2c4

[hybrid] 5ade0fb95542997545bbbe39 | ok | 'Frenchmans Creek is a tributary of the Darling River, which measures 1472 km from its source in northern New South Wales to its confluence with the Murray River at Wentworth, New South Wales.\n\n### References\n\n- [1] Document Title One: Frenchmans Creek (New South Wales)\n- [2] Document Title Two: Frenchmans Creek (California)\n- [3] Document Title Three: Red Rock River (Montana)'

INFO:  == LLM cache == saving: hybrid:keywords:156639aad0a69ff78b53f889fa81254e
INFO: Query nodes: survived, six (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 24 relations
INFO: Query edges: Celtic languages, Western European territories, cultural traits (top_k:20, cosine:0.2)
INFO: Global query: 22 entites, 20 relations
INFO: Raw search results: 42 entities, 44 relations, 0 vector chunks
INFO: After truncation: 42 entities, 44 relations
INFO: Selecting 38 from 38 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 44 relations
INFO: Round-robin merged chunks: 38 -> 38 (deduplicated 0)
INFO: Final context: 42 entities, 44 relations, 8 chunks
INFO: Final chunks S+F/O: E4/1 E7/2 E6/3 E3/4 E5/5 E1/6 E1/7 E1/8
INFO:  == LLM cache == saving: hybrid:query:5dc27bd1f69c8c90b708daf151798391

[hybrid] 5adf1c3f5542993a75d263ec | ok | 'The six Western European territories where Celtic languages or cultural traits have survived are:\n\n1. Brittany\n2. Cornwall\n3. Ireland\n4. Isle of Man\n5. Scotland\n6. Wales\n\nThese regions are collectively referred to as the Celtic nations. \n\n### References\n\n- [1] Celtic nations\n- [2] Pan Celtic Festival\n- [3] Celtic studies'

INFO:  == LLM cache == saving: hybrid:keywords:5594a8ad37ce8db41c065c5849fae098
INFO: Query nodes: Clone of Clones (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 33 relations
INFO: Query edges: Clone of Clones, music, band (top_k:20, cosine:0.2)
INFO: Global query: 28 entites, 20 relations
INFO: Raw search results: 35 entities, 41 relations, 0 vector chunks
INFO: After truncation: 35 entities, 41 relations
INFO: Selecting 17 from 17 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 41 relations
INFO: Round-robin merged chunks: 17 -> 17 (deduplicated 0)
INFO: Final context: 35 entities, 41 relations, 8 chunks
INFO: Final chunks S+F/O: E11/1 E6/2 E2/3 E2/4 E1/5 E2/6 E5/7 E2/8
INFO:  == LLM cache == saving: hybrid:query:b14f8767cf605ea500a0be30cdcda82a

[hybrid] 5abcf5ec55429959677d6b76 | ok | 'Clones of Clones have played shows alongside SomeKindaWonderful, which is based in Cleveland, Ohio. \n\n### References\n- [1] Clones of Clones'

INFO:  == LLM cache == saving: hybrid:keywords:be53ab37cb54ffbbffba5106ab74ba91
INFO: Query nodes: The Clash of Triton, To SquarePants or Not to SquarePants (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 54 relations
INFO: Query edges: SpongeBob SquarePants, episode, airing order (top_k:20, cosine:0.2)
INFO: Global query: 22 entites, 20 relations
INFO: Raw search results: 29 entities, 54 relations, 0 vector chunks
INFO: After truncation: 29 entities, 54 relations
INFO: Selecting 17 from 17 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 54 relations
INFO: Round-robin merged chunks: 17 -> 17 (deduplicated 0)
INFO: Final context: 29 entities, 54 relations, 8 chunks
INFO: Final chunks S+F/O: E8/1 E8/2 E4/3 E5/4 E6/5 E2/6 E2/7 E4/8
INFO:  == LLM cache == saving: hybrid:query:a745cbdfdd41a371c538fbc343e9b27c

[hybrid] 5addc79d5542995b365fab7b | ok | 'The episode "The Clash of Triton" aired first on July 5, 2010, while "To SquarePants or Not to SquarePants" is a special episode that was part of the tenth anniversary celebration of the series, which aired later.\n\n### References\n\n- [1] The Clash of Triton\n- [2] SpongeBob SquarePants (season 6)'

INFO:  == LLM cache == saving: hybrid:keywords:d5bab3bc4957b9b268963f50be6938ed
INFO: Query nodes: role, best known (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 32 relations
INFO: Query edges: Grown-Ups, actor, Allo Allo (top_k:20, cosine:0.2)
INFO: Global query: 23 entites, 20 relations
INFO: Raw search results: 41 entities, 49 relations, 0 vector chunks
INFO: After truncation: 41 entities, 49 relations
INFO: Selecting 27 from 27 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 49 relations
INFO: Round-robin merged chunks: 27 -> 27 (deduplicated 0)
INFO: Final context: 41 entities, 49 relations, 8 chunks
INFO: Final chunks S+F/O: E3/1 E2/2 E2/3 E2/4 E3/5 E5/6 E3/7 E9/8
INFO:  == LLM cache == saving: hybrid:query:8da597801e96d401d2806c1dce330064

[hybrid] 5add596f5542990dbb2f7e4d | ok | 'Grown-Ups starred Sam Kelly, who is best known for his role as Captain Hans Geering in the sitcom "\'Allo \'Allo!". \n\n### References\n\n- [7] Sam Kelly\n- [8] Grown-Ups'

INFO:  == LLM cache == saving: hybrid:keywords:94f16409ddda18ebbe451a62675105dc
INFO: Query nodes: seven-time, Foxcatcher, medalist (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 30 relations
INFO: Query edges: World and Olympic medalist, Foxcatcher, birth date (top_k:20, cosine:0.2)
INFO: Global query: 29 entites, 20 relations
INFO: Raw search results: 38 entities, 37 relations, 0 vector chunks
INFO: After truncation: 38 entities, 37 relations
INFO: Selecting 39 from 39 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 37 relations
INFO: Round-robin merged chunks: 39 -> 39 (deduplicated 0)
INFO: Final context: 38 entities, 37 relations, 8 chunks
INFO: Final chunks S+F/O: E12/1 E4/2 E1/3 E2/4 E2/5 E2/6 E1/7 E1/8
INFO:  == LLM cache == saving: hybrid:query:12ccd6374d2a18672791c3d1d8908bb4

[hybrid] 5ae491155542995ad6573da3 | ok | 'Dave Schultz, the seven-time World and Olympic medalist on whom "Foxcatcher" was based, was born on June 6, 1959. \n\n### References\n\n- [1] Foxcatcher\n- [2] Dave Schultz (wrestling)'

INFO:  == LLM cache == saving: hybrid:keywords:f41c0845e9f4b82e420cf8f3a02dadb8
INFO: Query nodes: Grimsby, Minster (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 33 relations
INFO: Query edges: Grimsby Minster, English Province (top_k:20, cosine:0.2)
INFO: Global query: 27 entites, 20 relations
INFO: Raw search results: 36 entities, 41 relations, 0 vector chunks
INFO: After truncation: 36 entities, 41 relations
INFO: Selecting 41 from 41 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 41 relations
INFO: Round-robin merged chunks: 41 -> 41 (deduplicated 0)
INFO: Final context: 36 entities, 41 relations, 8 chunks
INFO: Final chunks S+F/O: E7/1 E3/2 E5/3 E3/4 E2/5 E1/6 E2/7 E2/8
INFO:  == LLM cache == saving: hybrid:query:c70856c61c6e4ba41b9c6ab8f12793c8

[hybrid] 5a7fd1515542992e7d278db1 | ok | 'Grimsby Minster is located in the Province of Canterbury, as it is part of the Church of England within the Diocese of Lincoln. \n\n### References\n\n- [1] Grimsby Minster\n- [2] Diocese of Lincoln'

INFO:  == LLM cache == saving: hybrid:keywords:a73f4e05c974f3131aacb845c0b95d79
INFO: Query nodes: Revealed (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 32 relations
INFO: Query edges: Toni Braxton, performance, hotel and casino (top_k:20, cosine:0.2)
INFO: Global query: 19 entites, 20 relations
INFO: Raw search results: 35 entities, 48 relations, 0 vector chunks
INFO: After truncation: 35 entities, 48 relations
INFO: Selecting 26 from 26 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 48 relations
INFO: Round-robin merged chunks: 26 -> 26 (deduplicated 0)
INFO: Final context: 35 entities, 48 relations, 8 chunks
INFO: Final chunks S+F/O: E5/1 E4/2 E5/3 E5/4 E3/5 E4/6 E5/7 E2/8
INFO:  == LLM cache == saving: hybrid:query:acf6306fd5b06577933db4ffb511125e

[hybrid] 5ae3eeb25542995dadf2425e | ok | 'Toni Braxton: Revealed was performed at the Flamingo Las Vegas, which is owned and operated by Caesars Entertainment Corporation. \n\n### References\n- [1] Toni Braxton: Revealed'

INFO:  == LLM cache == saving: hybrid:keywords:58d3b068177057729a0d6eb0a6d87a9e
INFO: Query nodes: Padosan (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 26 relations
INFO: Query edges: Padosan, supporting actor, playback singer, language (top_k:20, cosine:0.2)
INFO: Global query: 25 entites, 20 relations
INFO: Raw search results: 32 entities, 33 relations, 0 vector chunks
INFO: After truncation: 32 entities, 33 relations
INFO: Selecting 11 from 11 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 33 relations
INFO: Round-robin merged chunks: 11 -> 11 (deduplicated 0)
INFO: Final context: 32 entities, 33 relations, 8 chunks
INFO: Final chunks S+F/O: E15/1 E4/2 E4/3 E2/4 E4/5 E2/6 E2/7 E2/8
INFO:  == LLM cache == saving: hybrid:query:b278339073b8c8e8ac5746026b0ab124

[hybrid] 5a8db916554299441c6ba057 | ok | 'Padosan features Kishore Kumar as a supporting actor, who is known as one of the successful playback singers in the Hindi film industry.\n\n### References\n\n- [1] Padosan'

INFO:  == LLM cache == saving: hybrid:keywords:6bceafed09b2a5e6ed018bc00be932db
INFO: Query nodes: mother, patricia, Rome (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 39 relations
INFO: Query edges: Alberic II of Spoleto, patricia of Rome, title history (top_k:20, cosine:0.2)
INFO: Global query: 24 entites, 20 relations
INFO: Raw search results: 41 entities, 56 relations, 0 vector chunks
INFO: After truncation: 41 entities, 56 relations
INFO: Selecting 29 from 29 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 56 relations
INFO: Round-robin merged chunks: 29 -> 29 (deduplicated 0)
INFO: Final context: 41 entities, 56 relations, 8 chunks
INFO: Final chunks S+F/O: E3/1 E2/2 E6/3 E4/4 E4/5 E3/6 E2/7 E2/8
INFO:  == LLM cache == saving: hybrid:query:3e8fa1233dc96930793a99d5d7799c19

[hybrid] 5a7e6f295542991319bc94b1 | ok | 'Pope John X conferred the title "patricia" of Rome upon Marozia, the mother of Alberic II of Spoleto. \n\n### References\n- [1] Marozia'

INFO:  == LLM cache == saving: hybrid:keywords:b7d1d2a93f1922aa9c0a7edbcb839812
INFO: Query nodes: U.F.O, Princess of China (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 31 relations
INFO: Query edges: Coldplay songs, common factor, U.F.O, Princess of China (top_k:20, cosine:0.2)
INFO: Global query: 21 entites, 20 relations
INFO: Raw search results: 30 entities, 38 relations, 0 vector chunks
INFO: After truncation: 30 entities, 38 relations
INFO: Selecting 18 from 18 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 38 relations
INFO: Round-robin merged chunks: 18 -> 18 (deduplicated 0)
INFO: Final context: 30 entities, 38 relations, 8 chunks
INFO: Final chunks S+F/O: E6/1 E11/2 E2/3 E5/4 E3/5 E1/6 E1/7 E1/8
INFO:  == LLM cache == saving: hybrid:query:df5480f7c66395d772a604825c976555

[hybrid] 5a7326cb5542994cef4bc47f | ok | 'Both "U.F.O." and "Princess of China" were written during the same period for Coldplay\'s fifth studio album, "Mylo Xyloto." Additionally, each song features contributions from all four band members of Coldplay. They are interconnected, as "U.F.O." serves as the opening track leading into "Princess of China." \n\n### References\n\n- [1] U.F.O. (Coldplay song)\n- [2] Princess of China'

INFO:  == LLM cache == saving: hybrid:keywords:dc865cf9e1ac3f0fc5ac14a80a364e8c
INFO: Query nodes: abdication (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 27 relations
INFO: Query edges: Russia-United Kingdom relations, war, rivalry, Emperor Nicholas II (top_k:20, cosine:0.2)
INFO: Global query: 21 entites, 20 relations
INFO: Raw search results: 41 entities, 47 relations, 0 vector chunks
INFO: After truncation: 41 entities, 47 relations
INFO: Selecting 34 from 34 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 47 relations
INFO: Round-robin merged chunks: 34 -> 34 (deduplicated 0)
INFO: Final context: 41 entities, 47 relations, 8 chunks
INFO: Final chunks S+F/O: E6/1 E4/2 E3/3 E5/4 E4/5 E3/6 E3/7 E2/8
INFO:  == LLM cache == saving: hybrid:query:3b3dedef6b440af3430d5d264062feae

[hybrid] 5ade25ed5542997c77aded70 | ok | 'The Russia-United Kingdom relations were in a state of rivalry during the Cold War, which occurred after the abdication of Emperor Nicholas II following the Russian Revolution. \n\n### References\n\n- [1] Russia–United Kingdom relations\n- [2] Russian Revolution'

INFO:  == LLM cache == saving: hybrid:keywords:e5414038aaa26b4510dd5b37e4bc264f
INFO: Query nodes: 116th season, 117th season, six competitions, four competitions (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 30 relations
INFO: Query edges: sports team, competitions, seasons (top_k:20, cosine:0.2)
INFO: Global query: 31 entites, 20 relations
INFO: Raw search results: 47 entities, 45 relations, 0 vector chunks
INFO: After truncation: 47 entities, 45 relations
INFO: Selecting 55 from 55 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 45 relations
INFO: Round-robin merged chunks: 55 -> 55 (deduplicated 0)
INFO: Final context: 47 entities, 45 relations, 8 chunks
INFO: Final chunks S+F/O: E4/1 E1/2 E1/3 E1/4 E1/5 E2/6 E2/7 E1/8
INFO:  == LLM cache == saving: hybrid:query:5b5cd29a81ebeeb51cd5a12976c34d93

[hybrid] 5ab6644655429954757d327d | ok | 'Football Club Barcelona competed in six competitions during their 116th season and four competitions in their 117th season. \n\n### References\n- [1] 2015–16 FC Barcelona season\n- [2] 2016–17 FC Barcelona season'

INFO:  == LLM cache == saving: hybrid:keywords:053ba558e6c18a3dddc3702badc42ee9
INFO: Query nodes: Kalanipauahi, niece, husband (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 39 relations
INFO: Query edges: family relationships, historical figures (top_k:20, cosine:0.2)
INFO: Global query: 32 entites, 20 relations
INFO: Raw search results: 52 entities, 59 relations, 0 vector chunks
INFO: After truncation: 52 entities, 59 relations
INFO: Selecting 35 from 35 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 59 relations
INFO: Round-robin merged chunks: 35 -> 35 (deduplicated 0)
INFO: Final context: 52 entities, 59 relations, 8 chunks
INFO: Final chunks S+F/O: E5/1 E4/2 E3/3 E1/4 E1/5 E1/6 E1/7 E2/8
INFO:  == LLM cache == saving: hybrid:query:22498f8563d0ce50d30241204b578d81

[hybrid] 5a7dff595542997cc2c474eb | ok | 'I do not have enough information to answer.'

INFO:  == LLM cache == saving: hybrid:keywords:4b001500df2001ec7805ac013f58daac
INFO: Query nodes: Yannick Ferreira Carrasco, home games (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 31 relations
INFO: Query edges: football, player information (top_k:20, cosine:0.2)
INFO: Global query: 36 entites, 20 relations
INFO: Raw search results: 55 entities, 50 relations, 0 vector chunks
INFO: After truncation: 55 entities, 50 relations
INFO: Selecting 45 from 45 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 50 relations
INFO: Round-robin merged chunks: 45 -> 45 (deduplicated 0)
INFO: Final context: 55 entities, 50 relations, 8 chunks
INFO: Final chunks S+F/O: E3/1 E6/2 E1/3 E1/4 E1/5 E1/6 E4/7 E1/8
INFO:  == LLM cache == saving: hybrid:query:1eb25a38f00613495d1ca183da86c1e8

[hybrid] 5aba5e2555429955dce3edf1 | ok | 'Yannick Ferreira Carrasco plays home games at the Wanda Metropolitano, the home stadium of Atlético Madrid.\n\n### References\n\n- [1] Atlético Madrid'

INFO:  == LLM cache == saving: hybrid:keywords:a197e4217c9ff166b692bb937fe55ff6
INFO: Query nodes: town, success, Moe Sedway, Benjamin Bugsy Siegel (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 43 relations
INFO: Query edges: Moe Sedway, Benjamin Siegel, murder, town success (top_k:20, cosine:0.2)
INFO: Global query: 20 entites, 20 relations
INFO: Raw search results: 26 entities, 43 relations, 0 vector chunks
INFO: After truncation: 26 entities, 43 relations
INFO: Selecting 16 from 16 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 43 relations
INFO: Round-robin merged chunks: 16 -> 16 (deduplicated 0)
INFO: Final context: 26 entities, 43 relations, 8 chunks
INFO: Final chunks S+F/O: E5/1 E5/2 E4/3 E3/4 E3/5 E5/6 E8/7 E7/8
INFO:  == LLM cache == saving: hybrid:query:1d9d2a7a59f654d1a0583188a32826ea

[hybrid] 5a7130365542994082a3e645 | ok | 'Moe Sedway achieved success in Las Vegas after Benjamin "Bugsy" Siegel\'s murder. \n\n### References\n\n- [1] Moe Sedway\n- [2] Bugsy Siegel\n- [3] Cohen crime family'

INFO:  == LLM cache == saving: hybrid:keywords:9c37ac8283e4b3b30ecbb732a719f253
WARNING: low_level_keywords is empty
INFO: Query edges: birthplace, musician, The Motion Makes Me Last (top_k:20, cosine:0.2)
INFO: Global query: 32 entites, 20 relations
INFO: Raw search results: 32 entities, 20 relations, 0 vector chunks
INFO: After truncation: 32 entities, 20 relations
INFO: Selecting 22 from 22 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 20 relations
INFO: Round-robin merged chunks: 22 -> 22 (deduplicated 0)
INFO: Final context: 32 entities, 20 relations, 8 chunks
INFO: Final chunks S+F/O: E3/1 E6/2 E1/3 E2/4 E2/5 E4/6 E2/7 E2/8
INFO:  == LLM cache == saving: hybrid:query:e83e1a9edb677f2579a0cc0742b09ec3

[hybrid] 5a77e62b5542992a6e59dfea | ok | 'The musician responsible for creating "The Motion Makes Me Last" is Matthew Cooper, who is known professionally as Eluvium. He was born in Tennessee. \n\n### References\n\n- [1] Eluvium (musician)'

INFO:  == LLM cache == saving: hybrid:keywords:d310143a062ce49466bf8d62ec13d7c6
INFO: Query nodes: fictional realm (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 27 relations
INFO: Query edges: superhero, American comic book series, horror comics anthology, Norse mythology (top_k:20, cosine:0.2)
INFO: Global query: 22 entites, 20 relations
INFO: Raw search results: 39 entities, 41 relations, 0 vector chunks
INFO: After truncation: 39 entities, 41 relations
INFO: Selecting 50 from 50 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 41 relations
INFO: Round-robin merged chunks: 50 -> 50 (deduplicated 0)
INFO: Final context: 39 entities, 41 relations, 8 chunks
INFO: Final chunks S+F/O: E11/1 E7/2 E4/3 E1/4 E1/5 E2/6 E2/7 E1/8
INFO:  == LLM cache == saving: hybrid:query:7096062cc1a1f0838106e1abd536df8f

[hybrid] 5a8351fd55429954d2e2ec98 | ok | 'The superhero followed in the American comic book series that began as a horror comics anthology and introduced the fictional realm based on Norse mythology is "The Mighty Thor." This series started as "Journey Into Mystery," which initially featured horror stories before transitioning to superhero content, with Thor being prominently featured from issue #83 onward.\n\n### References\n\n- [1] Journey into Mystery\n- [2] Asgard (comics)'

INFO:  == LLM cache == saving: hybrid:keywords:d6285cb24f64a12b4583bb3e7af2b6fe
INFO: Query nodes: Short Bus (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 26 relations
INFO: Query edges: guitarist, Device, American industrial rock group (top_k:20, cosine:0.2)
INFO: Global query: 29 entites, 20 relations
INFO: Raw search results: 49 entities, 46 relations, 0 vector chunks
INFO: After truncation: 49 entities, 46 relations
INFO: Selecting 36 from 36 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 46 relations
INFO: Round-robin merged chunks: 36 -> 36 (deduplicated 0)
INFO: Final context: 49 entities, 46 relations, 8 chunks
INFO: Final chunks S+F/O: E4/1 E8/2 E5/3 E4/4 E2/5 E2/6 E2/7 E2/8
INFO:  == LLM cache == saving: hybrid:query:15d12d4eeaafeaac042d4063a0f47b0d

[hybrid] 5ab278745542997061209617 | ok | 'The guitarist who played with both Device and the American industrial rock group Filter, whose debut album was named "Short Bus," is Geno Lenardo. \n\n### References\n\n- [1] Device (metal band)\n- [2] Short Bus (album)\n- [3] Filter (band)'

INFO:  == LLM cache == saving: hybrid:keywords:2e2c1d5068d82cbf83a63318128e90dc
INFO: Query nodes: Tomi Ameobi (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 31 relations
INFO: Query edges: regional dialect, English footballer, nickname (top_k:20, cosine:0.2)
INFO: Global query: 31 entites, 20 relations
INFO: Raw search results: 50 entities, 49 relations, 0 vector chunks
INFO: After truncation: 50 entities, 49 relations
INFO: Selecting 31 from 31 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 49 relations
INFO: Round-robin merged chunks: 31 -> 31 (deduplicated 0)
INFO: Final context: 50 entities, 49 relations, 8 chunks
INFO: Final chunks S+F/O: E6/1 E4/2 E2/3 E2/4 E1/5 E3/6 E2/7 E3/8
INFO:  == LLM cache == saving: hybrid:query:be1b06b3da6e21bdeb014f7da7498899

[hybrid] 5ae5a63c5542992663a4f203 | ok | 'The nickname of the regional dialect from Newcastle upon Tyne, the city where English footballer Tomi Ameobi was born, is **Geordie**. \n\n### References\n- [1] Newcastle upon Tyne'

INFO:  == LLM cache == saving: hybrid:keywords:ace49f1cbb8511bb4ecc9c57ee897c06
INFO: Query nodes: Lenny Kravitz, Lady (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 61 relations
INFO: Query edges: Lenny Kravitz, Lady song, birth year (top_k:20, cosine:0.2)
INFO: Global query: 20 entites, 20 relations
INFO: Raw search results: 25 entities, 61 relations, 0 vector chunks
INFO: After truncation: 25 entities, 61 relations
INFO: Selecting 21 from 21 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 61 relations
INFO: Round-robin merged chunks: 21 -> 21 (deduplicated 0)
INFO: Final context: 25 entities, 61 relations, 8 chunks
INFO: Final chunks S+F/O: E6/1 E4/2 E6/3 E3/4 E4/5 E2/6 E2/7 E6/8
INFO:  == LLM cache == saving: hybrid:query:0c303985041a1ef6fbb4691dc297e2c8

[hybrid] 5ab56e085542992aa134a315 | ok | 'The subject of the Lenny Kravitz song "Lady," Nicole Kidman, was born on June 20, 1967.\n\n### References\n\n- [1] Lady (Lenny Kravitz song)'

INFO:  == LLM cache == saving: hybrid:keywords:2fc193015fd3eb8943c5ae5185449f09
INFO: Query nodes: Anna Lewandowska, footballer (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 37 relations
INFO: Query edges: relationship, football club (top_k:20, cosine:0.2)
INFO: Global query: 30 entites, 20 relations
INFO: Raw search results: 50 entities, 57 relations, 0 vector chunks
INFO: After truncation: 50 entities, 57 relations
INFO: Selecting 46 from 46 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 57 relations
INFO: Round-robin merged chunks: 46 -> 46 (deduplicated 0)
INFO: Final context: 50 entities, 57 relations, 8 chunks
INFO: Final chunks S+F/O: E3/1 E3/2 E2/3 E2/4 E4/5 E1/6 E1/7 E2/8
INFO:  == LLM cache == saving: hybrid:query:918e517410960d76a19cee9d610a2984

[hybrid] 5a8e08d35542995085b37395 | ok | 'Anna Lewandowska is married to Robert Lewandowski, who plays as a striker for Bayern Munich.\n\n### References\n\n- [1] Anna Lewandowska\n- [2] Robert Lewandowski'

INFO:  == LLM cache == saving: hybrid:keywords:43ef78435d78ffdd8a8f205bef7f6863
INFO: Query nodes: Yōko Shōji, most famous manga (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 27 relations
INFO: Query edges: manga, Yōko Shōji, chapter count (top_k:20, cosine:0.2)
INFO: Global query: 27 entites, 20 relations
INFO: Raw search results: 31 entities, 32 relations, 0 vector chunks
INFO: After truncation: 31 entities, 32 relations
INFO: Selecting 8 from 8 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 32 relations
INFO: Round-robin merged chunks: 8 -> 8 (deduplicated 0)
INFO: Final context: 31 entities, 32 relations, 8 chunks
INFO: Final chunks S+F/O: E5/1 E5/2 E5/3 E3/4 E8/5 E1/6 E5/7 E2/8
INFO:  == LLM cache == saving: hybrid:query:ee762a66f3a0e9df1771b8e5d8a727fc

[hybrid] 5adcaa7f5542990d50227cdb | ok | 'Yōko Shōji\'s most famous manga, "Seito Shokun!", has a total of 24 chapters, which were published into tankōbon volumes. \n\n### References\n\n- [1] Yōko Shōji\n- [2] Seito Shokun!'

INFO:  == LLM cache == saving: hybrid:keywords:bc42740f3a85a399922d926d87f9c313
INFO: Query nodes: Miami Showband, killings, UVF Mid-Ulster Brigade (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 51 relations
INFO: Query edges: UVF Mid-Ulster Brigade, Miami Showband killings, attack date (top_k:20, cosine:0.2)
INFO: Global query: 19 entites, 20 relations
INFO: Raw search results: 24 entities, 51 relations, 0 vector chunks
INFO: After truncation: 24 entities, 51 relations
INFO: Selecting 12 from 12 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 51 relations
INFO: Round-robin merged chunks: 12 -> 12 (deduplicated 0)
INFO: Final context: 24 entities, 51 relations, 8 chunks
INFO: Final chunks S+F/O: E5/1 E9/2 E6/3 E7/4 E3/5 E1/6 E5/7 E2/8
INFO:  == LLM cache == saving: hybrid:query:859517286485c204eda769003567a9eb

[hybrid] 5ae16ea85542990adbacf790 | ok | 'The UVF Mid-Ulster Brigade conducted the attack known as the Miami Showband killings on 31 July 1975. \n\n### References\n\n- [1] Miami Showband killings\n- [2] UVF Mid-Ulster Brigade'

INFO:  == LLM cache == saving: hybrid:keywords:32d78fa1374ebcc689d161bb0f081f8a
INFO: Query nodes: Quiet in Heaven, Song of Liberty (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 37 relations
INFO: Query edges: music history, album recording (top_k:20, cosine:0.2)
INFO: Global query: 34 entites, 20 relations
INFO: Raw search results: 54 entities, 57 relations, 0 vector chunks
INFO: After truncation: 54 entities, 57 relations
INFO: Selecting 39 from 39 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 57 relations
INFO: Round-robin merged chunks: 39 -> 39 (deduplicated 0)
INFO: Final context: 54 entities, 57 relations, 8 chunks
INFO: Final chunks S+F/O: E2/1 E4/2 E1/3 E3/4 E2/5 E4/6 E2/7 E2/8
INFO:  == LLM cache == saving: hybrid:query:0f0f3963fc90a47bc95ff077f9a724f0

[hybrid] 5a8bc29a5542995d1e6f1446 | ok | 'I do not have enough information to answer.'

INFO:  == LLM cache == saving: hybrid:keywords:83f19b2b9a55828a0400f8a3328c05e5
INFO: Query nodes: Elsa Lanchester, husband (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 31 relations
INFO: Query edges: 1935 American drama film, Les Misérables, costarred (top_k:20, cosine:0.2)
INFO: Global query: 26 entites, 20 relations
INFO: Raw search results: 46 entities, 51 relations, 0 vector chunks
INFO: After truncation: 46 entities, 51 relations
INFO: Selecting 53 from 53 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 51 relations
INFO: Round-robin merged chunks: 53 -> 53 (deduplicated 0)
INFO: Final context: 46 entities, 51 relations, 8 chunks
INFO: Final chunks S+F/O: E6/1 E2/2 E1/3 E3/4 E3/5 E1/6 E1/7 E6/8
INFO:  == LLM cache == saving: hybrid:query:65296bc063725160df18bb0af3710812

[hybrid] 5ae15d70554299422ee9966f | ok | 'In the 1935 American drama film *Les Misérables*, Charles Laughton, who was the husband of Elsa Lanchester, co-starred with Fredric March. \n\n### References\n\n- * [1] Les Misérables (1935 film)\n- * [2] Charles Laughton'

INFO:  == LLM cache == saving: hybrid:keywords:785d6d10a399de7421fa8edb2a704ab9
INFO: Query nodes: born, year, directed, starred (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 37 relations
INFO: Query edges: Argentine singer, actor, El Tio Disparate (top_k:20, cosine:0.2)
INFO: Global query: 27 entites, 20 relations
INFO: Raw search results: 47 entities, 57 relations, 0 vector chunks
INFO: After truncation: 47 entities, 57 relations
INFO: Selecting 39 from 39 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 57 relations
INFO: Round-robin merged chunks: 39 -> 39 (deduplicated 0)
INFO: Final context: 47 entities, 57 relations, 8 chunks
INFO: Final chunks S+F/O: E4/1 E2/2 E6/3 E1/4 E7/5 E3/6 E2/7 E1/8
INFO:  == LLM cache == saving: hybrid:query:371337c962ab8559c9b396c31db71daa

[hybrid] 5a81a84e5542990a1d231e4e | ok | 'The Argentine singer and actor who both directed and starred in "El Tío Disparate" is Palito Ortega. He was born on March 8, 1942.\n\n### References\n\n- [1] Palito Ortega'

INFO:  == LLM cache == saving: hybrid:keywords:ccbb9d08ed2a58330cd90ac8f635dd7b
INFO: Query nodes: Shane Lynch, Boyzone, records sold (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 44 relations
INFO: Query edges: music records, Boyzone, Shane Lynch (top_k:20, cosine:0.2)
INFO: Global query: 23 entites, 20 relations
INFO: Raw search results: 28 entities, 46 relations, 0 vector chunks
INFO: After truncation: 28 entities, 46 relations
INFO: Selecting 15 from 15 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 46 relations
INFO: Round-robin merged chunks: 15 -> 15 (deduplicated 0)
INFO: Final context: 28 entities, 46 relations, 8 chunks
INFO: Final chunks S+F/O: E4/1 E8/2 E2/3 E6/4 E6/5 E4/6 E4/7 E1/8
INFO:  == LLM cache == saving: hybrid:query:40e76cceb7516f75fc2fcc1945a628bb

[hybrid] 5ae15ae25542990adbacf767 | ok | 'Shane Lynch, as a member of Boyzone, contributed to the sale of over 25 million records worldwide. \n\n### References\n\n- [2] Boyzone'

INFO:  == LLM cache == saving: hybrid:keywords:188d639fe0b75bb64a4195caed5d6628
INFO: Query nodes: 2009 (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 33 relations
INFO: Query edges: British Academy Television Awards, host, birth date (top_k:20, cosine:0.2)
INFO: Global query: 22 entites, 20 relations
INFO: Raw search results: 42 entities, 53 relations, 0 vector chunks
INFO: After truncation: 42 entities, 53 relations
INFO: Selecting 51 from 51 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 53 relations
INFO: Round-robin merged chunks: 51 -> 51 (deduplicated 0)
INFO: Final context: 42 entities, 53 relations, 8 chunks
INFO: Final chunks S+F/O: E6/1 E5/2 E6/3 E3/4 E3/5 E4/6 E2/7 E1/8
INFO:  == LLM cache == saving: hybrid:query:c279c9174fd416e9203570647195ec47

[hybrid] 5ae55d1e55429960a22e02cb | ok | 'I do not have enough information to answer. \n\n### References\n- None'

INFO:  == LLM cache == saving: hybrid:keywords:8cbb1059904ecb8e247ec8f78a0c44c9
INFO: Query nodes: pioneer, field (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 39 relations
INFO: Query edges: Eusebio Valli, physician, pioneering field (top_k:20, cosine:0.2)
INFO: Global query: 27 entites, 20 relations
INFO: Raw search results: 47 entities, 59 relations, 0 vector chunks
INFO: After truncation: 47 entities, 59 relations
INFO: Selecting 117 from 139 entity-related chunks by vector similarity
INFO: Find 1 additional chunks in 1 relations (deduplicated 22)
INFO: Selecting 1 from 1 relation-related chunks by vector similarity
INFO: Round-robin merged chunks: 118 -> 118 (deduplicated 0)
INFO: Final context: 47 entities, 59 relations, 8 chunks
INFO: Final chunks S+F/O: E4/1 R4/1 E4/2 E5/3 E2/4 E2/5 E1/6 E2/7
INFO:  == LLM cache == saving: hybrid:query:d1b9dda4e378be47a7e4650dda54c37d

[hybrid] 5a8ee2855542995a26add550 | ok | 'Eusebio Valli studied alongside Luigi Galvani, who was recognized as the pioneer of bioelectricity, particularly known for his discovery of animal electricity. \n\n### References\n* [1] Eusebio Valli\n* [2] Luigi Galvani'

INFO:  == LLM cache == saving: hybrid:keywords:6686f537f9c71f52c20179e7533c93f2
INFO: Query nodes: Bharat Ratna (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 34 relations
INFO: Query edges: Indian civilian award, Jayaprakash Narayan, posthumous award (top_k:20, cosine:0.2)
INFO: Global query: 22 entites, 20 relations
INFO: Raw search results: 33 entities, 42 relations, 0 vector chunks
INFO: After truncation: 33 entities, 42 relations
INFO: Selecting 13 from 13 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 42 relations
INFO: Round-robin merged chunks: 13 -> 13 (deduplicated 0)
INFO: Final context: 33 entities, 42 relations, 8 chunks
INFO: Final chunks S+F/O: E8/1 E12/2 E4/3 E6/4 E2/5 E4/6 E2/7 E2/8
INFO:  == LLM cache == saving: hybrid:query:4882c38c8044875a0f4e71428deb4bb7

[hybrid] 5ae494575542995dadf2434d | ok | 'Jayaprakash Narayan was posthumously awarded the Bharat Ratna, which is the highest civilian award in India.\n\n### References\n\n- [1] Bharat Ratna\n- [2] Jayaprakash Narayan'

INFO:  == LLM cache == saving: hybrid:keywords:6d5cbe73206d5fbaf0ef2236dfcffa45
INFO: Query nodes: Cyrina Fiallo, Michael Jacobs (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 32 relations
INFO: Query edges: television shows, sitcoms (top_k:20, cosine:0.2)
INFO: Global query: 30 entites, 20 relations
INFO: Raw search results: 50 entities, 52 relations, 0 vector chunks
INFO: After truncation: 50 entities, 52 relations
INFO: Selecting 69 from 69 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 52 relations
INFO: Round-robin merged chunks: 69 -> 69 (deduplicated 0)
INFO: Final context: 50 entities, 52 relations, 8 chunks
INFO: Final chunks S+F/O: E10/1 E1/2 E1/3 E2/4 E1/5 E4/6 E2/7 E1/8
INFO:  == LLM cache == saving: hybrid:query:43f1e9cfe61c9aee78837f9772e4dc3c

[hybrid] 5ae07db855429945ae95937a | ok | 'Cyrina Fiallo has guest starred on the Michael Jacobs-created sitcom "Girl Meets World." \n\n### References\n- [1] Girl Meets World\n- [2] Cyrina Fiallo'

INFO:  == LLM cache == saving: hybrid:keywords:a10c1600f6537fcfbdf8bcf5ddb0c8ff
INFO: Query nodes: The Waltz King (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 38 relations
INFO: Query edges: waltz, composition, 1844 (top_k:20, cosine:0.2)
INFO: Global query: 25 entites, 20 relations
INFO: Raw search results: 33 entities, 40 relations, 0 vector chunks
INFO: After truncation: 33 entities, 40 relations
INFO: Selecting 19 from 19 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 40 relations
INFO: Round-robin merged chunks: 19 -> 19 (deduplicated 0)
INFO: Final context: 33 entities, 40 relations, 8 chunks
INFO: Final chunks S+F/O: E7/1 E6/2 E5/3 E5/4 E4/5 E3/6 E2/7 E2/8
INFO:  == LLM cache == saving: hybrid:query:d283bbf0bc362a3605305e14880306be

[hybrid] 5a7a93115542995eb53be86f | ok | 'The waltz composed by "The Waltz King," Johann Strauss II, in 1844 is "Sinngedichte," also known as "Poems of the Senses" or "Epigrams." \n\n### References\n\n- [1] Sinngedichte\n- [2] Johann Strauss II'

INFO:  == LLM cache == saving: hybrid:keywords:e29db5b96b9673114c0400cbe4276870
INFO: Query nodes: Environment Act 1995, politician (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 38 relations
INFO: Query edges: Environment Act, political party (top_k:20, cosine:0.2)
INFO: Global query: 32 entites, 20 relations
INFO: Raw search results: 43 entities, 49 relations, 0 vector chunks
INFO: After truncation: 43 entities, 49 relations
INFO: Selecting 34 from 34 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 49 relations
INFO: Round-robin merged chunks: 34 -> 34 (deduplicated 0)
INFO: Final context: 43 entities, 49 relations, 8 chunks
INFO: Final chunks S+F/O: E3/1 E4/2 E3/3 E2/4 E3/5 E2/6 E3/7 E2/8
INFO:  == LLM cache == saving: hybrid:query:b2998b71669b2c78f428a05eaa2e0d47

[hybrid] 5a7cdf89554299683c1c63b0 | ok | 'The Environment Act 1995 was passed under the ministerial tutelage of John Gummer, who is associated with the British Conservative Party. \n\n### References\n\n- [1] John Gummer'

INFO:  == LLM cache == saving: hybrid:keywords:e556df0b928760dc34b85c99861b685d
INFO: Query nodes: Mischa Anne Barton (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 25 relations
INFO: Query edges: film role, protagonist, movie writing (top_k:20, cosine:0.2)
INFO: Global query: 31 entites, 20 relations
INFO: Raw search results: 51 entities, 45 relations, 0 vector chunks
INFO: After truncation: 51 entities, 45 relations
INFO: Selecting 59 from 59 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 45 relations
INFO: Round-robin merged chunks: 59 -> 59 (deduplicated 0)
INFO: Final context: 51 entities, 45 relations, 8 chunks
INFO: Final chunks S+F/O: E9/1 E1/2 E2/3 E1/4 E1/5 E1/6 E1/7 E1/8
INFO:  == LLM cache == saving: hybrid:query:853be70bf0c782d0f4ba55e72770799b

[hybrid] 5a8313a755429954d2e2ec06 | ok | 'Mischa Anne Barton\'s first major film role as the protagonist was in "Lawn Dogs," which was written by Naomi Wallace.'

INFO:  == LLM cache == saving: hybrid:keywords:a1fde3ee3e90386a4ab9e997bc3ab778
INFO: Query nodes: character, second Academy Award (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 39 relations
INFO: Query edges: James Byron Dean, final lead role, Academy Award (top_k:20, cosine:0.2)
INFO: Global query: 32 entites, 20 relations
INFO: Raw search results: 49 entities, 53 relations, 0 vector chunks
INFO: After truncation: 49 entities, 53 relations
INFO: Selecting 53 from 53 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 53 relations
INFO: Round-robin merged chunks: 53 -> 53 (deduplicated 0)
INFO: Final context: 49 entities, 53 relations, 8 chunks
INFO: Final chunks S+F/O: E4/1 E4/2 E1/3 E2/4 E1/5 E3/6 E2/7 E1/8
INFO:  == LLM cache == saving: hybrid:query:0d6df2c6802f813e904e26e313ac0202

[hybrid] 5a871a5e5542996432c5721e | ok | 'James Byron Dean played the character Jett Rink in his final lead role in the film "Giant," which earned him his second Academy Award nomination. \n\n### References\n\n- [1] James Dean\n- [2] Giant (1956 film)'

INFO:  == LLM cache == saving: hybrid:keywords:ede0bc76b496210fd90b25036b052d57
INFO: Query nodes: material, granddaughter (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 25 relations
INFO: Query edges: invention, hairdresser, Yorkshire, England (top_k:20, cosine:0.2)
INFO: Global query: 28 entites, 20 relations
INFO: Raw search results: 48 entities, 45 relations, 0 vector chunks
INFO: After truncation: 48 entities, 45 relations
INFO: Selecting 53 from 53 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 45 relations
INFO: Round-robin merged chunks: 53 -> 53 (deduplicated 0)
INFO: Final context: 48 entities, 45 relations, 8 chunks
INFO: Final chunks S+F/O: E2/1 E2/2 E1/3 E6/4 E3/5 E1/6 E2/7 E1/8
INFO:  == LLM cache == saving: hybrid:query:a1fddf099657dbfc26801ea86c7fb631

[hybrid] 5ab8688b55429934fafe6daa | ok | 'The hairdresser from Yorkshire, England, Maurice Ward, invented a material called Starlite, which was named by his granddaughter, Kimberly Ward.\n\n### References\n\n- [1] Starlite\n- [2] Maurice Ward'

INFO:  == LLM cache == saving: hybrid:keywords:1e84aa2a63004b91093cb49ceb6ba132
INFO: Query nodes: Take Me, American singer, actor, producer (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 39 relations
INFO: Query edges: music, song, 20th century (top_k:20, cosine:0.2)
INFO: Global query: 32 entites, 20 relations
INFO: Raw search results: 52 entities, 59 relations, 0 vector chunks
INFO: After truncation: 52 entities, 59 relations
INFO: Selecting 56 from 56 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 59 relations
INFO: Round-robin merged chunks: 56 -> 56 (deduplicated 0)
INFO: Final context: 52 entities, 59 relations, 8 chunks
INFO: Final chunks S+F/O: E2/1 E1/2 E6/3 E2/4 E2/5 E1/6 E1/7 E1/8
INFO:  == LLM cache == saving: hybrid:query:da12c870c6e3d827da7d0135c8c35765

[hybrid] 5ab5cdb85542997d4ad1f1e0 | ok | '"Take Me" is a song recorded by **Frank Sinatra**, who was one of the most popular and influential musical artists of the 20th century.\n\n### References\n- [1] Take Me (song)\n- [2] Frank Sinatra'

INFO:  == LLM cache == saving: hybrid:keywords:dcd8aa8398e2975f213b22a3d6401796
INFO: Query nodes: Georgetown (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 64 relations
INFO: Query edges: private university, basketball tournament, Georgetown, U.S. city (top_k:20, cosine:0.2)
INFO: Global query: 22 entites, 20 relations
INFO: Raw search results: 30 entities, 64 relations, 0 vector chunks
INFO: After truncation: 30 entities, 64 relations
INFO: Selecting 14 from 14 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 64 relations
INFO: Round-robin merged chunks: 14 -> 14 (deduplicated 0)
INFO: Final context: 30 entities, 64 relations, 8 chunks
INFO: Final chunks S+F/O: E3/1 E3/2 E7/3 E8/4 E8/5 E8/6 E8/7 E3/8
INFO:  == LLM cache == saving: hybrid:query:084d4090eaf3c13f28bd3bc86d3e2b35

[hybrid] 5abd93115542996e802b47e0 | ok | 'I do not have enough information to answer. \n\n### References'

INFO:  == LLM cache == saving: hybrid:keywords:4c9e7ab20660226542b541f6e18e4e59
INFO: Query nodes: Susquehanna University, Paul Musser (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 43 relations
INFO: Query edges: Susquehanna University, city location, Paul Musser (top_k:20, cosine:0.2)
INFO: Global query: 24 entites, 20 relations
INFO: Raw search results: 35 entities, 45 relations, 0 vector chunks
INFO: After truncation: 35 entities, 45 relations
INFO: Selecting 34 from 34 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 45 relations
INFO: Round-robin merged chunks: 34 -> 34 (deduplicated 0)
INFO: Final context: 35 entities, 45 relations, 8 chunks
INFO: Final chunks S+F/O: E4/1 E6/2 E3/3 E4/4 E1/5 E1/6 E2/7 E4/8
INFO:  == LLM cache == saving: hybrid:query:55eb6b4fb4272c91389a083ad8b1e183

[hybrid] 5ae610e55542995703ce8ae1 | ok | 'Susquehanna University and Paul Musser are both associated with Selinsgrove, Pennsylvania, as Susquehanna University is located there and Paul Musser attended the university. \n\n### References\n\n- [1] Susquehanna University\n- [2] Paul Musser'

INFO:  == LLM cache == saving: hybrid:keywords:8eb63458dd82f9a7992e1c3573d4f211
INFO: Query nodes: stem-head, symbol, SMS Emden (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 53 relations
INFO: Query edges: SMS Emden, historical naval ships, kingdoms (top_k:20, cosine:0.2)
INFO: Global query: 21 entites, 20 relations
INFO: Raw search results: 24 entities, 53 relations, 0 vector chunks
INFO: After truncation: 24 entities, 53 relations
INFO: Selecting 11 from 11 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 53 relations
INFO: Round-robin merged chunks: 11 -> 11 (deduplicated 0)
INFO: Final context: 24 entities, 53 relations, 8 chunks
INFO: Final chunks S+F/O: E8/1 E10/2 E3/3 E3/4 E1/5 E2/6 E5/7 E2/8
INFO:  == LLM cache == saving: hybrid:query:65edf9073cb00630004f41deac0f6556

[hybrid] 5ade66dd55429975fa854ebe | ok | 'SMS Emden mounted an Iron Cross on her stem-head, which is a military decoration established in the Kingdom of Prussia. \n\n### References\n\n- [1] Iron Cross\n- [2] SMS Emden (1916)'

INFO:  == LLM cache == saving: hybrid:keywords:44f26d7af4ee2e0acf5bab6a464da1e5
INFO: Query nodes: Binocular, Champion Jockey (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 32 relations
INFO: Query edges: jockey, championship, consecutive wins (top_k:20, cosine:0.2)
INFO: Global query: 24 entites, 20 relations
INFO: Raw search results: 30 entities, 34 relations, 0 vector chunks
INFO: After truncation: 30 entities, 34 relations
INFO: Selecting 13 from 13 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 34 relations
INFO: Round-robin merged chunks: 13 -> 13 (deduplicated 0)
INFO: Final context: 30 entities, 34 relations, 8 chunks
INFO: Final chunks S+F/O: E8/1 E6/2 E3/3 E3/4 E4/5 E2/6 E2/7 E4/8
INFO:  == LLM cache == saving: hybrid:query:a407619b6cbfb4558606d6fa9e9fb8cf

[hybrid] 5a8f51185542992414482a3d | ok | 'Tony McCoy, the primary jockey of Binocular, was Champion Jockey for a record 20 consecutive times. \n\n### References\n\n- [1] Tony McCoy'

INFO:  == LLM cache == saving: hybrid:keywords:3ee1d50e59db654f28e6c1747efd9856
INFO: Query nodes: Elliott-Donaldson House (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 39 relations
INFO: Query edges: lieutenant general, historical residence (top_k:20, cosine:0.2)
INFO: Global query: 30 entites, 20 relations
INFO: Raw search results: 47 entities, 56 relations, 0 vector chunks
INFO: After truncation: 47 entities, 56 relations
INFO: Selecting 55 from 55 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 56 relations
INFO: Round-robin merged chunks: 55 -> 55 (deduplicated 0)
INFO: Final context: 47 entities, 56 relations, 8 chunks
INFO: Final chunks S+F/O: E3/1 E1/2 E7/3 E2/4 E2/5 E2/6 E3/7 E2/8
INFO:  == LLM cache == saving: hybrid:query:14c352444f6a3649bcebeb9b5fdcb8eb

[hybrid] 5a771d6155429966f1a36c6d | ok | 'Nathan Bedford Forrest, a Confederate States Army General, stayed in the Elliott-Donaldson House after the American Civil War ended in 1865.\n\n### References\n- [1] Elliott-Donaldson House'

INFO:  == LLM cache == saving: hybrid:keywords:b3c829215aacfacec6da903e87b55054
INFO: Query nodes: 1675-1679, Swedish-Norwegian War, great Northern War (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 30 relations
INFO: Query edges: Battle of Uddevalla, war history (top_k:20, cosine:0.2)
INFO: Global query: 27 entites, 20 relations
INFO: Raw search results: 31 entities, 33 relations, 0 vector chunks
INFO: After truncation: 31 entities, 33 relations
INFO: Selecting 20 from 20 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 33 relations
INFO: Round-robin merged chunks: 20 -> 20 (deduplicated 0)
INFO: Final context: 31 entities, 33 relations, 8 chunks
INFO: Final chunks S+F/O: E3/1 E9/2 E2/3 E1/4 E1/5 E1/6 E5/7 E3/8
INFO:  == LLM cache == saving: hybrid:query:fce30659e4a7c35e8c506bd1214281d9

[hybrid] 5a88644455429938390d3f3f | ok | 'The Battle of Uddevalla occurred during the Scanian War, which was fought from 1675 to 1679, involving Denmark–Norway, Brandenburg, and Sweden. \n\n### References\n\n- [1] Battle of Uddevalla\n- [2] Scanian War'

INFO:  == LLM cache == saving: hybrid:keywords:4d076593300dba3d4259a5ffb0af11b9
INFO: Query nodes: Brent Robert Barry, Drew William Barry (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 47 relations
INFO: Query edges: Rick Barry, sons, birth order (top_k:20, cosine:0.2)
INFO: Global query: 20 entites, 20 relations
INFO: Raw search results: 27 entities, 47 relations, 0 vector chunks
INFO: After truncation: 27 entities, 47 relations
INFO: Selecting 52 from 52 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 47 relations
INFO: Round-robin merged chunks: 52 -> 52 (deduplicated 0)
INFO: Final context: 27 entities, 47 relations, 8 chunks
INFO: Final chunks S+F/O: E7/1 E4/2 E6/3 E4/4 E3/5 E3/6 E3/7 E1/8
INFO:  == LLM cache == saving: hybrid:query:91ed3fb2cb9d3c4a20247d1452bfa283

[hybrid] 5ab5fcae554299110f2199ad | ok | 'Brent Robert Barry was born first on December 31, 1971, while Drew William Barry was born later on February 17, 1973.\n\n### References\n\n- [1] Drew Barry\n- [2] Brent Barry\n- [3] Rick Barry'

INFO:  == LLM cache == saving: hybrid:keywords:8904365e023fc80add14eebf4e400fb1
INFO: Query nodes: Falling Stars (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 50 relations
INFO: Query edges: role-playing game, Falling Stars, publishing company, country (top_k:20, cosine:0.2)
INFO: Global query: 31 entites, 20 relations
INFO: Raw search results: 47 entities, 63 relations, 0 vector chunks
INFO: After truncation: 47 entities, 63 relations
INFO: Selecting 98 from 98 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 63 relations
INFO: Round-robin merged chunks: 98 -> 98 (deduplicated 0)
INFO: Final context: 47 entities, 63 relations, 8 chunks
INFO: Final chunks S+F/O: E8/1 E4/2 E3/3 E1/4 E2/5 E2/6 E3/7 E1/8
INFO:  == LLM cache == saving: hybrid:query:ef8a383cb8911ffe6eb39cb4b87eacde

[hybrid] 5a8a5bd355429970aeb702b9 | ok | 'Falling Stars is published by Nordcurrent, which is a Lithuanian company. \n\n### References\n- [1] Falling Stars (video game)'

INFO:  == LLM cache == saving: hybrid:keywords:ea89adf5036320885fde34e70f4689ca
INFO: Query nodes: mother, princess, Middleton Grange Shopping Centre, 1970 (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 65 relations
INFO: Query edges: royalty, shopping centre, Middleton Grange (top_k:20, cosine:0.2)
INFO: Global query: 26 entites, 20 relations
INFO: Raw search results: 33 entities, 66 relations, 0 vector chunks
INFO: After truncation: 33 entities, 66 relations
INFO: Selecting 21 from 21 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 66 relations
INFO: Round-robin merged chunks: 21 -> 21 (deduplicated 0)
INFO: Final context: 33 entities, 66 relations, 8 chunks
INFO: Final chunks S+F/O: E7/1 E5/2 E2/3 E5/4 E4/5 E3/6 E2/7 E5/8
INFO:  == LLM cache == saving: hybrid:query:070a464aad7f349f1ba7997e0f8f4b92

[hybrid] 5a7faa215542995d8a8ddee8 | ok | 'The mother of the princess who opened Middleton Grange Shopping Centre in 1970, Princess Anne, is Queen Elizabeth II.\n\n### References\n\n- [1] Anne, Princess Royal\n- [2] Middleton Grange Shopping Centre'

INFO:  == LLM cache == saving: hybrid:keywords:0c2ae2b1e5cc7256dfc22b24fa6e2bda
INFO: Query nodes: Ash Atalla, creator (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 33 relations
INFO: Query edges: Graham Linehan, sitcom, UK channel (top_k:20, cosine:0.2)
INFO: Global query: 24 entites, 20 relations
INFO: Raw search results: 44 entities, 53 relations, 0 vector chunks
INFO: After truncation: 44 entities, 53 relations
INFO: Selecting 56 from 56 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 53 relations
INFO: Round-robin merged chunks: 56 -> 56 (deduplicated 0)
INFO: Final context: 44 entities, 53 relations, 8 chunks
INFO: Final chunks S+F/O: E9/1 E4/2 E5/3 E4/4 E3/5 E5/6 E4/7 E2/8
INFO:  == LLM cache == saving: hybrid:query:3587dd9d9db68379ff489f4b41ac2956

[hybrid] 5adddce05542992200553b70 | ok | 'Graham Linehan was the creator of the Ash Atalla-produced sitcom "The IT Crowd," which aired on Channel 4. \n\n### References\n\n- [1] Graham Linehan\n- [2] The IT Crowd'

INFO:  == LLM cache == saving: hybrid:keywords:7f1645948cfd48b96344e02835c607f9
INFO: Query nodes: Sigh No More (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 43 relations
INFO: Query edges: South African singer, musical revue (top_k:20, cosine:0.2)
INFO: Global query: 33 entites, 20 relations
INFO: Raw search results: 51 entities, 62 relations, 0 vector chunks
INFO: After truncation: 51 entities, 62 relations
INFO: Selecting 109 from 109 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 62 relations
INFO: Round-robin merged chunks: 109 -> 109 (deduplicated 0)
INFO: Final context: 51 entities, 62 relations, 8 chunks
INFO: Final chunks S+F/O: E7/1 E2/2 E4/3 E5/4 E2/5 E4/6 E2/7 E1/8
INFO:  == LLM cache == saving: hybrid:query:3b66829829938e0d1c7383b424787803

[hybrid] 5adf8c965542993344016cf5 | ok | 'The South African born singer who featured in the musical revue "Sigh No More" is Graham Payn, who is noted for singing the best-known song in the show, "Matelot."\n\n### References\n\n- [1] Sigh No More (musical)'

INFO:  == LLM cache == saving: hybrid:keywords:37b34b5cfb57271bc10f3e20292b1994
INFO: Query nodes: team, test match, New Zealand (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 58 relations
INFO: Query edges: cricket, team captain, Shaheens, New Zealand national team (top_k:20, cosine:0.2)
INFO: Global query: 22 entites, 20 relations
INFO: Raw search results: 29 entities, 60 relations, 0 vector chunks
INFO: After truncation: 29 entities, 60 relations
INFO: Selecting 19 from 19 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 60 relations
INFO: Round-robin merged chunks: 19 -> 19 (deduplicated 0)
INFO: Final context: 29 entities, 60 relations, 8 chunks
INFO: Final chunks S+F/O: E2/1 E5/2 E6/3 E5/4 E7/5 E8/6 E4/7 E5/8
INFO:  == LLM cache == saving: hybrid:query:d82fa4c8927b1852c2d92b1420997319

[hybrid] 5ac38d1f55429939154137c3 | ok | 'Javed Miandad captained the Pakistan national cricket team, popularly referred to as the Shaheens, during the Test match against the New Zealand national cricket team. \n\n### References\n- *[1] Pakistan national cricket team*'

INFO:  == LLM cache == saving: hybrid:keywords:ecfd5887b737219cd55132adcd0a3413
INFO: Query nodes: Family Guy, Peter Griffin (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 55 relations
INFO: Query edges: films, Family Guy, Peter Griffin (top_k:20, cosine:0.2)
INFO: Global query: 19 entites, 20 relations
INFO: Raw search results: 27 entities, 56 relations, 0 vector chunks
INFO: After truncation: 27 entities, 56 relations
INFO: Selecting 17 from 17 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 56 relations
INFO: Round-robin merged chunks: 17 -> 17 (deduplicated 0)
INFO: Final context: 27 entities, 56 relations, 8 chunks
INFO: Final chunks S+F/O: E4/1 E11/2 E7/3 E2/4 E3/5 E2/6 E4/7 E3/8
INFO:  == LLM cache == saving: hybrid:query:0ee09e83527c2ad1483a2e4c19044449

[hybrid] 5a7fd7305542992e7d278dc2 | ok | '"Family Guy" and the character of Peter Griffin were developed based on two animated short films created by Seth MacFarlane: *The Life of Larry* and *Larry & Steve*. These shorts were produced in the mid-1990s and served as the foundation for the animated sitcom, with Peter Griffin being one of the characters inspired by this earlier work.\n\n### References\n\n- [1] The Life of Larry and Larry & Steve\n- [2] Peter Griffin\n- [3] Family Guy'

INFO:  == LLM cache == saving: hybrid:keywords:af31b6a17751f4877216a7ee856ee344
INFO: Query nodes: North Blenheim, New York, month (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 36 relations
INFO: Query edges: flooding, Hurricane, disaster inquiry (top_k:20, cosine:0.2)
INFO: Global query: 25 entites, 20 relations
INFO: Raw search results: 44 entities, 55 relations, 0 vector chunks
INFO: After truncation: 44 entities, 55 relations
INFO: Selecting 110 from 133 entity-related chunks by vector similarity
INFO: Find 1 additional chunks in 1 relations (deduplicated 23)
INFO: Selecting 1 from 1 relation-related chunks by vector similarity
INFO: Round-robin merged chunks: 111 -> 111 (deduplicated 0)
INFO: Final context: 44 entities, 55 relations, 8 chunks
INFO: Final chunks S+F/O: E6/1 R1/1 E6/2 E3/3 E7/4 E3/5 E3/6 E2/7
INFO:  == LLM cache == saving: hybrid:query:5dad3f3eb6040bcae8e95255150b9d1a

[hybrid] 5ae60ea9554299546bf8304e | ok | 'North Blenheim, New York was affected by flooding caused by Hurricane Irene, which occurred in August 2011. \n\n### References\n\n- [1] North Blenheim, New York\n- [2] Hurricane Irene\n- [3] Old Blenheim Bridge'

INFO:  == LLM cache == saving: hybrid:keywords:bf08e10113de0a2e5ed049dd663ad9da
INFO: Query nodes: Lewis Young, Ashley Young (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 31 relations
INFO: Query edges: football team, Lewis Young, Ashley Young (top_k:20, cosine:0.2)
INFO: Global query: 26 entites, 20 relations
INFO: Raw search results: 35 entities, 34 relations, 0 vector chunks
INFO: After truncation: 35 entities, 34 relations
INFO: Selecting 16 from 16 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 34 relations
INFO: Round-robin merged chunks: 16 -> 16 (deduplicated 0)
INFO: Final context: 35 entities, 34 relations, 8 chunks
INFO: Final chunks S+F/O: E3/1 E4/2 E6/3 E6/4 E3/5 E6/6 E2/7 E1/8
INFO:  == LLM cache == saving: hybrid:query:7237eebdfac85aaf61af4c982e092a3c

[hybrid] 5a895d305542993b751ca931 | ok | 'Ashley Young plays for Manchester United. \n\n### References\n\n- [1] Ashley Young'

INFO:  == LLM cache == saving: hybrid:keywords:ab1605349c8f1b2ed1854b89e07f7093
INFO: Query nodes: 1989, arrangement, 30 films, television shows (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 40 relations
INFO: Query edges: theme music, animated television series, music composition (top_k:20, cosine:0.2)
INFO: Global query: 25 entites, 20 relations
INFO: Raw search results: 45 entities, 60 relations, 0 vector chunks
INFO: After truncation: 45 entities, 60 relations
INFO: Selecting 37 from 37 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 60 relations
INFO: Round-robin merged chunks: 37 -> 37 (deduplicated 0)
INFO: Final context: 45 entities, 60 relations, 8 chunks
INFO: Final chunks S+F/O: E5/1 E2/2 E5/3 E4/4 E2/5 E6/6 E3/7 E1/8
INFO:  == LLM cache == saving: hybrid:query:d47eaf5085c8ac91487bc7df91264a1f

[hybrid] 5a8319b255429940e5e1a960 | ok | 'The theme music of the animated television series "The Simpsons," which was composed in 1989, was created by Danny Elfman. The current arrangement of the theme music was done by Alf Clausen, who has scored or orchestrated music for more than 30 films and television shows.\n\n### References\n- [1] The Simpsons Theme\n- [2] Alf Clausen'

INFO:  == LLM cache == saving: hybrid:keywords:05830bfbd9b4263b7dc99d432aa008d7
WARNING: low_level_keywords is empty
INFO: Query edges: comic book character, Vic Bloom, Pep Comics (top_k:20, cosine:0.2)
INFO: Global query: 27 entites, 20 relations
INFO: Raw search results: 27 entities, 20 relations, 0 vector chunks
INFO: After truncation: 27 entities, 20 relations
INFO: Selecting 16 from 16 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 20 relations
INFO: Round-robin merged chunks: 16 -> 16 (deduplicated 0)
INFO: Final context: 27 entities, 20 relations, 8 chunks
INFO: Final chunks S+F/O: E3/1 E3/2 E4/3 E3/4 E3/5 E3/6 E2/7 E3/8
INFO:  == LLM cache == saving: hybrid:query:8cd9734e177fc206383676ae6bcb2c76

[hybrid] 5adc94dc5542990d50227cad | ok | 'The comic book character originally written by Vic Bloom after appearing in "Pep Comics" is **Archie Andrews**, who first appeared in "Pep Comics" #22 in December 1941.\n\n### References\n\n- [1] Pep Comics\n- [2] Archie (comic book)'

INFO:  == LLM cache == saving: hybrid:keywords:f227296be82f8bef1f6cc6191ee364aa
INFO: Query nodes: first year, published (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 26 relations
INFO: Query edges: scientific journal, publication, Bronx, organization (top_k:20, cosine:0.2)
INFO: Global query: 28 entites, 20 relations
INFO: Raw search results: 46 entities, 44 relations, 0 vector chunks
INFO: After truncation: 46 entities, 44 relations
INFO: Selecting 33 from 33 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 44 relations
INFO: Round-robin merged chunks: 33 -> 33 (deduplicated 0)
INFO: Final context: 46 entities, 44 relations, 8 chunks
INFO: Final chunks S+F/O: E5/1 E2/2 E7/3 E2/4 E2/5 E3/6 E6/7 E2/8
INFO:  == LLM cache == saving: hybrid:query:042dd378736d95aee691201988f81483

[hybrid] 5a81a4135542990a1d231e37 | ok | 'The first year a scientific journal published by an organization located in the Bronx, specifically "Mycologia," was published is January 1909.\n\n### References\n\n- [1] Mycologia'

INFO:  == LLM cache == saving: hybrid:keywords:60b897b08be365e670121883d6391734
INFO: Query nodes: Slimer (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 46 relations
INFO: Query edges: movie, Melissa McCarthy, character (top_k:20, cosine:0.2)
INFO: Global query: 21 entites, 20 relations
INFO: Raw search results: 41 entities, 66 relations, 0 vector chunks
INFO: After truncation: 41 entities, 66 relations
INFO: Selecting 23 from 23 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 66 relations
INFO: Round-robin merged chunks: 23 -> 23 (deduplicated 0)
INFO: Final context: 41 entities, 66 relations, 8 chunks
INFO: Final chunks S+F/O: E7/1 E8/2 E4/3 E2/4 E7/5 E2/6 E2/7 E6/8
INFO:  == LLM cache == saving: hybrid:query:77604433a672bf321401406c6352b472

[hybrid] 5a865bbf5542991e77181615 | ok | 'The movie starring Melissa McCarthy that features the character Slimer is "Ghostbusters" (2016). \n\n### References\n\n- [1] Ghostbusters (2016 film)'

INFO:  == LLM cache == saving: hybrid:keywords:1988cf78d592a6ccf9063ba9952b8adf
INFO: Query nodes: Robyn Fenty (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 45 relations
INFO: Query edges: singer, birthplace, Pon de Replay (top_k:20, cosine:0.2)
INFO: Global query: 23 entites, 20 relations
INFO: Raw search results: 35 entities, 53 relations, 0 vector chunks
INFO: After truncation: 35 entities, 53 relations
INFO: Selecting 15 from 15 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 53 relations
INFO: Round-robin merged chunks: 15 -> 15 (deduplicated 0)
INFO: Final context: 35 entities, 53 relations, 8 chunks
INFO: Final chunks S+F/O: E10/1 E9/2 E8/3 E10/4 E6/5 E3/6 E1/7 E8/8
INFO:  == LLM cache == saving: hybrid:query:f7294aef490405ca2a4b8da95d8ff31c

[hybrid] 5ae3006c55429928c423959f | ok | 'The singer who performs "Pon de Replay" and was born Robyn Fenty was born in Saint Michael, Barbados.\n\n### References\n\n- [1] Rihanna\n- [2] Pon de Replay\n- [3] Music of the Sun'

INFO:  == LLM cache == saving: hybrid:keywords:3cd16ebbc2eb6774b61936e2034768f9
INFO: Query nodes: Stephen Cepello (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 31 relations
INFO: Query edges: current governor, state, Governor's Mansion (top_k:20, cosine:0.2)
INFO: Global query: 26 entites, 20 relations
INFO: Raw search results: 44 entities, 50 relations, 0 vector chunks
INFO: After truncation: 44 entities, 50 relations
INFO: Selecting 58 from 58 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 50 relations
INFO: Round-robin merged chunks: 58 -> 58 (deduplicated 0)
INFO: Final context: 44 entities, 50 relations, 8 chunks
INFO: Final chunks S+F/O: E5/1 E5/2 E2/3 E5/4 E1/5 E3/6 E2/7 E1/8
INFO:  == LLM cache == saving: hybrid:query:2836222de751f6befa008faa7bd4423f

[hybrid] 5ab47e0a5542990594ba9c32 | ok | "The current governor of the state where former wrestler Stephen Cepello painted the Governor's Mansion is Mark Dayton, who serves as the governor of Minnesota. \n\n### References\n\n- [1] Governor of Minnesota\n- [2] Stephen Cepello"

INFO:  == LLM cache == saving: hybrid:keywords:7f8eea52283d6e849517ee281d3065f5
INFO: Query nodes: Benthesikyme, father (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 32 relations
INFO: Query edges: Greek mythology, chief deity (top_k:20, cosine:0.2)
INFO: Global query: 29 entites, 20 relations
INFO: Raw search results: 41 entities, 43 relations, 0 vector chunks
INFO: After truncation: 41 entities, 43 relations
INFO: Selecting 17 from 17 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 43 relations
INFO: Round-robin merged chunks: 17 -> 17 (deduplicated 0)
INFO: Final context: 41 entities, 43 relations, 8 chunks
INFO: Final chunks S+F/O: E6/1 E4/2 E5/3 E2/4 E2/5 E7/6 E1/7 E1/8
INFO:  == LLM cache == saving: hybrid:query:199912b28c8e6bc6438b3a3840b0f1c6

[hybrid] 5a8e17ce554299653c1aa169 | ok | 'In Greek mythology, Poseidon, the father of Benthesikyme, was venerated as a chief deity in the ancient cities of Pylos and Thebes during the pre-Olympian Bronze Age.\n\n### References\n\n- [1] Poseidon\n- [2] Benthesikyme'

INFO:  == LLM cache == saving: hybrid:keywords:71ffb09188f55ea637718ae424763260
INFO: Query nodes: Norman Buckley, ABC Family (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 47 relations
INFO: Query edges: family drama, cable network (top_k:20, cosine:0.2)
INFO: Global query: 24 entites, 20 relations
INFO: Raw search results: 39 entities, 58 relations, 0 vector chunks
INFO: After truncation: 39 entities, 58 relations
INFO: Selecting 33 from 33 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 58 relations
INFO: Round-robin merged chunks: 33 -> 33 (deduplicated 0)
INFO: Final context: 39 entities, 58 relations, 8 chunks
INFO: Final chunks S+F/O: E1/1 E4/2 E1/3 E4/4 E6/5 E4/6 E3/7 E5/8
INFO:  == LLM cache == saving: hybrid:query:c858378b5cabe4008183c7e778441160

[hybrid] 5ae75eb45542991bbc976201 | ok | 'Norman Buckley is associated with the family drama "Switched at Birth," which aired on the cable network now known as Freeform, previously called ABC Family.\n\n### References\n\n- [1] Switched at Birth (TV series)\n- [2] List of Switched at Birth episodes\n- [3] The Fosters (2013 TV series)'

INFO:  == LLM cache == saving: hybrid:keywords:6f34833fcf31aaeea3a65f0f9390009b
INFO: Query nodes: New York City, 48th Street, 51st Street (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 54 relations
INFO: Query edges: high-rise commercial buildings, architecture style (top_k:20, cosine:0.2)
INFO: Global query: 26 entites, 20 relations
INFO: Raw search results: 43 entities, 69 relations, 0 vector chunks
INFO: After truncation: 43 entities, 69 relations
INFO: Selecting 74 from 74 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 69 relations
INFO: Round-robin merged chunks: 74 -> 74 (deduplicated 0)
INFO: Final context: 43 entities, 69 relations, 8 chunks
INFO: Final chunks S+F/O: E3/1 E10/2 E5/3 E3/4 E2/5 E1/6 E7/7 E2/8
INFO:  == LLM cache == saving: hybrid:query:0940623364f284bf9e2b796d528b0644

[hybrid] 5a79e1275542990198eaefe7 | ok | 'The 19 high-rise commercial buildings covering 22 acres between 48th and 51st Streets in New York City feature the Art Deco architectural style, as exemplified by Rockefeller Center. \n\n### References\n\n- [1] Rockefeller Center\n- [2] Art Deco in the United States'

INFO:  == LLM cache == saving: hybrid:keywords:8b7c296af9d184e30ddafb1f0557e4aa
INFO: Query nodes: relief first officer, flight, Cairo, New York (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 38 relations
INFO: Query edges: flight crash, relief first officer, Cairo, New York, birth month (top_k:20, cosine:0.2)
INFO: Global query: 23 entites, 20 relations
INFO: Raw search results: 33 entities, 40 relations, 0 vector chunks
INFO: After truncation: 33 entities, 40 relations
INFO: Selecting 15 from 15 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 40 relations
INFO: Round-robin merged chunks: 15 -> 15 (deduplicated 0)
INFO: Final context: 33 entities, 40 relations, 8 chunks
INFO: Final chunks S+F/O: E9/1 E4/2 E7/3 E3/4 E3/5 E5/6 E3/7 E4/8
INFO:  == LLM cache == saving: hybrid:query:fd25135aba80c7cc51aacb10bc0aa508

[hybrid] 5ae791ef55429952e35ea979 | ok | 'The relief first officer of EgyptAir Flight 990, Gameel Al-Batouti, was born in February. \n\n### References\n- [1] EgyptAir Flight 990\n- [2] Gameel Al-Batouti'

INFO:  == LLM cache == saving: hybrid:keywords:559cdd7bf8cf39c993a9daafb4142762
INFO: Query nodes: 1971, 1989, Buddy MacKay (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 28 relations
INFO: Query edges: American politician, United States Senator, Governor of Florida (top_k:20, cosine:0.2)
INFO: Global query: 27 entites, 20 relations
INFO: Raw search results: 45 entities, 43 relations, 0 vector chunks
INFO: After truncation: 45 entities, 43 relations
INFO: Selecting 112 from 119 entity-related chunks by vector similarity
INFO: Find 1 additional chunks in 1 relations (deduplicated 26)
INFO: Selecting 1 from 1 relation-related chunks by vector similarity
INFO: Round-robin merged chunks: 113 -> 113 (deduplicated 0)
INFO: Final context: 45 entities, 43 relations, 8 chunks
INFO: Final chunks S+F/O: E4/1 R1/1 E5/2 E2/3 E4/4 E3/5 E3/6 E2/7
INFO:  == LLM cache == saving: hybrid:query:151680079b8337a7e24202465d264996

[hybrid] 5a8d0940554299585d9e379e | ok | 'The American politician who served as United States Senator from 1971 to 1989 and was Governor of Florida before Buddy MacKay is Lawton Chiles. \n\n### References\n\n- [1] Lawton Chiles'

INFO:  == LLM cache == saving: hybrid:keywords:b91983dfa72ca712d3c59196e7e0eda0
INFO: Query nodes: Vikram Bhatt, Rajneesh Duggal, Adah Sharma (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 44 relations
INFO: Query edges: film collaboration, movie director (top_k:20, cosine:0.2)
INFO: Global query: 33 entites, 20 relations
INFO: Raw search results: 52 entities, 63 relations, 0 vector chunks
INFO: After truncation: 52 entities, 63 relations
INFO: Selecting 49 from 49 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 63 relations
INFO: Round-robin merged chunks: 49 -> 49 (deduplicated 0)
INFO: Final context: 52 entities, 63 relations, 8 chunks
INFO: Final chunks S+F/O: E2/1 E5/2 E4/3 E1/4 E4/5 E3/6 E2/7 E1/8
INFO:  == LLM cache == saving: hybrid:query:2111973f0c868cd6163ca4032fe1c966

[hybrid] 5ade69e455429975fa854ec5 | ok | 'The director who worked with Vikram Bhatt on the film starring Rajneesh Duggal and Adah Sharma is Vikram Bhatt himself. He directed the film "1920," which features both actors in lead roles.\n\n### References\n- [6] 1920 (film) \n- [5] 1920 (film series) \n- [4] Rajneesh Duggal'

INFO:  == LLM cache == saving: hybrid:keywords:8f30619dc118df81f59e95cdf1938bd8
INFO: Query nodes: north, south (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 49 relations
INFO: Query edges: Sleepers, Kancamagus Highway (top_k:20, cosine:0.2)
INFO: Global query: 23 entites, 20 relations
INFO: Raw search results: 42 entities, 68 relations, 0 vector chunks
INFO: After truncation: 42 entities, 68 relations
INFO: Selecting 39 from 39 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 68 relations
INFO: Round-robin merged chunks: 39 -> 39 (deduplicated 0)
INFO: Final context: 42 entities, 68 relations, 8 chunks
INFO: Final chunks S+F/O: E7/1 E3/2 E3/3 E7/4 E4/5 E3/6 E3/7 E1/8
INFO:  == LLM cache == saving: hybrid:query:87f8bd5a6f64acecef87baa9a62467a8

[hybrid] 5abd5a135542992ac4f3829f | ok | 'I do not have enough information to answer.'

INFO:  == LLM cache == saving: hybrid:keywords:c4543e6fd4ef5b4372002aa567f8befd
INFO: Query nodes: First Vice Captain, Juventus (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 35 relations
INFO: Query edges: Juventus, football position, First Vice Captain (top_k:20, cosine:0.2)
INFO: Global query: 24 entites, 20 relations
INFO: Raw search results: 36 entities, 44 relations, 0 vector chunks
INFO: After truncation: 36 entities, 44 relations
INFO: Selecting 18 from 18 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 44 relations
INFO: Round-robin merged chunks: 18 -> 18 (deduplicated 0)
INFO: Final context: 36 entities, 44 relations, 8 chunks
INFO: Final chunks S+F/O: E5/1 E4/2 E5/3 E2/4 E1/5 E2/6 E3/7 E3/8
INFO:  == LLM cache == saving: hybrid:query:c9e6579d5c4594e4a940b84d20576ffd

[hybrid] 5adefcf15542995ec70e8f4c | ok | 'The First Vice Captain of Juventus, Claudio Marchisio, plays as a midfielder. \n\n### References\n- [1] Claudio Marchisio\n- [2] Giorgio Chiellini'

INFO:  == LLM cache == saving: hybrid:keywords:2588c0beee5ea2407a3f1be35001405f
INFO: Query nodes: male, females (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 28 relations
INFO: Query edges: animal kingdom, sexuality, sexual behavior (top_k:20, cosine:0.2)
INFO: Global query: 24 entites, 20 relations
INFO: Raw search results: 39 entities, 41 relations, 0 vector chunks
INFO: After truncation: 39 entities, 41 relations
INFO: Selecting 9 from 9 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 41 relations
INFO: Round-robin merged chunks: 9 -> 9 (deduplicated 0)
INFO: Final context: 39 entities, 41 relations, 8 chunks
INFO: Final chunks S+F/O: E5/1 E12/2 E9/3 E7/4 E4/5 E1/6 E1/7 E1/8
INFO:  == LLM cache == saving: hybrid:query:85585ebaa9551e90e9b74546f7f5c4f8

[hybrid] 5ae3ac665542994393b9e73f | ok | 'In the animal kingdom, the type of sexuality described as sexual behavior toward both males and females is known as **homosexual behavior**. This encompasses sexual activities, courtship, affection, and pair bonding among same-sex animal pairs. It is documented across various species, demonstrating the diversity of sexual behaviors in the animal kingdom.\n\n### References\n\n- [1] Homosexual behavior in animals\n- [2] Non-reproductive sexual behavior in animals\n- [3] Extended female sexuality'

INFO:  == LLM cache == saving: hybrid:keywords:134325445a61ad413464dffc234fdcd4
INFO: Query nodes: Clifton Junction, Penrith, Kirkby Stephen (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 41 relations
INFO: Query edges: Cliburn railway station, railway history, transportation (top_k:20, cosine:0.2)
INFO: Global query: 24 entites, 20 relations
INFO: Raw search results: 30 entities, 44 relations, 0 vector chunks
INFO: After truncation: 30 entities, 44 relations
INFO: Selecting 37 from 37 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 44 relations
INFO: Round-robin merged chunks: 37 -> 37 (deduplicated 0)
INFO: Final context: 30 entities, 44 relations, 8 chunks
INFO: Final chunks S+F/O: E5/1 E6/2 E5/3 E5/4 E4/5 E5/6 E4/7 E4/8
INFO:  == LLM cache == saving: hybrid:query:f2424476b77a60697e6f1e6d04d2c540

[hybrid] 5a8affca55429971feec45e3 | ok | 'Cliburn railway station was situated on the Eden Valley Railway, which ran between Clifton Junction near Penrith and Kirkby Stephen via Appleby-in-Westmorland.\n\n### References\n\n- [1] Eden Valley Railway\n- [2] Cliburn railway station'

INFO:  == LLM cache == saving: hybrid:keywords:40d368678c4c4d5bdbab6a88142a181d
INFO: Query nodes: choreographer, one who is said to be the last muse (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 56 relations
INFO: Query edges: choreography, Nutcracker, muse (top_k:20, cosine:0.2)
INFO: Global query: 26 entites, 20 relations
INFO: Raw search results: 41 entities, 67 relations, 0 vector chunks
INFO: After truncation: 41 entities, 67 relations
INFO: Selecting 53 from 53 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 67 relations
INFO: Round-robin merged chunks: 53 -> 53 (deduplicated 0)
INFO: Final context: 41 entities, 67 relations, 8 chunks
INFO: Final chunks S+F/O: E5/1 E7/2 E2/3 E4/4 E5/5 E2/6 E2/7 E1/8
INFO:  == LLM cache == saving: hybrid:query:769a5a0e04a3b0126766540cd323cede

[hybrid] 5a88be405542997e5c09a6ab | ok | 'Darci Kistler is said to be the last muse for the choreographer George Balanchine and she starred in "The Nutcracker" (1993 film) where she is noted for her contributions. \n\n### References\n\n- [1] Darci Kistler\n- [2] The Nutcracker (1993 film)'

INFO:  == LLM cache == saving: hybrid:keywords:1bb444980ca9d84553d3191da8be6430
INFO: Query nodes: artists, name (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 41 relations
INFO: Query edges: record label, 1993 album, Honky Tonk Angels (top_k:20, cosine:0.2)
INFO: Global query: 26 entites, 20 relations
INFO: Raw search results: 46 entities, 61 relations, 0 vector chunks
INFO: After truncation: 46 entities, 61 relations
INFO: Selecting 46 from 46 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 61 relations
INFO: Round-robin merged chunks: 46 -> 46 (deduplicated 0)
INFO: Final context: 46 entities, 61 relations, 8 chunks
INFO: Final chunks S+F/O: E6/1 E3/2 E4/3 E4/4 E4/5 E4/6 E3/7 E1/8
INFO:  == LLM cache == saving: hybrid:query:dbb1d60051f22eb16be7550520675501

[hybrid] 5ae2120c5542997283cd23ac | ok | 'The record label associated with one of the artists, specifically Dolly Parton, involved in the creation of the 1993 album **Honky Tonk Angels** is **Columbia Records**.\n\n### References\n\n* [Honky Tonk Angels]'

INFO:  == LLM cache == saving: hybrid:keywords:ad4f4eed8a65fbd781fda09439f2bb26
INFO: Query nodes: adoptive brothers, Rome (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 44 relations
INFO: Query edges: Roman Empire, co-emperors, Nerva-Antonine dynasty (top_k:20, cosine:0.2)
INFO: Global query: 15 entites, 20 relations
INFO: Raw search results: 35 entities, 64 relations, 0 vector chunks
INFO: After truncation: 35 entities, 64 relations
INFO: Selecting 18 from 18 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 64 relations
INFO: Round-robin merged chunks: 18 -> 18 (deduplicated 0)
INFO: Final context: 35 entities, 64 relations, 8 chunks
INFO: Final chunks S+F/O: E8/1 E5/2 E2/3 E11/4 E4/5 E1/6 E1/7 E5/8
INFO:  == LLM cache == saving: hybrid:query:9db76c4f684316f3b0586bdf5eddf06e

[hybrid] 5ab45bcd5542991779162c80 | ok | 'The adoptive brothers who were co-emperors of Rome during the Nerva-Antonine dynasty are Lucius Verus and Marcus Aurelius. \n\n### References\n\n- [1] Nerva–Antonine dynasty\n- [2] Lucius Verus\n- [3] History of the Roman Empire'

INFO:  == LLM cache == saving: hybrid:keywords:a6cf44549c9cc61fcdc18fa467fc9792
INFO: Query nodes: CBS, Strange Fruit (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 35 relations
INFO: Query edges: actress, sitcom, Strange Fruit (top_k:20, cosine:0.2)
INFO: Global query: 24 entites, 20 relations
INFO: Raw search results: 31 entities, 37 relations, 0 vector chunks
INFO: After truncation: 31 entities, 37 relations
INFO: Selecting 18 from 18 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 37 relations
INFO: Round-robin merged chunks: 18 -> 18 (deduplicated 0)
INFO: Final context: 31 entities, 37 relations, 8 chunks
INFO: Final chunks S+F/O: E6/1 E2/2 E1/3 E2/4 E3/5 E8/6 E2/7 E1/8
INFO:  == LLM cache == saving: hybrid:query:c0e1e4c0689dca48af8b2d84cea1d123

[hybrid] 5ae5ff845542996de7b71ad0 | ok | 'The actress Berlinda Tolbert, who stars as Emma Ayers in the film *Strange Fruit*, is better known for her role as Jenny Willis Jefferson on the CBS sitcom *The Jeffersons*.\n\n### References\n\n- [1] Berlinda Tolbert\n- [2] Strange Fruit (film)'

INFO:  == LLM cache == saving: hybrid:keywords:ff82e8a3d19eaee1f0a2d15ca16ffe42
INFO: Query nodes: BASIC (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 27 relations
INFO: Query edges: cartridge-based development system, Atari, programmer (top_k:20, cosine:0.2)
INFO: Global query: 25 entites, 20 relations
INFO: Raw search results: 34 entities, 37 relations, 0 vector chunks
INFO: After truncation: 34 entities, 37 relations
INFO: Selecting 12 from 12 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 37 relations
INFO: Round-robin merged chunks: 12 -> 12 (deduplicated 0)
INFO: Final context: 34 entities, 37 relations, 8 chunks
INFO: Final chunks S+F/O: E4/1 E5/2 E6/3 E5/4 E3/5 E1/6 E3/7 E2/8
INFO:  == LLM cache == saving: hybrid:query:236d97e54c3bdb77daae088c131bc2dd

[hybrid] 5ac2a399554299218029dada | ok | "Kathleen O'Brien programmed the Atari Assembler Editor, which is a cartridge-based development system developed by Shepardson Microsystems, Inc., a company noted for authoring Atari's BASIC. \n\n### References\n- [1] Atari Assembler Editor\n- [2] Shepardson Microsystems"

INFO:  == LLM cache == saving: hybrid:keywords:621b0b46b7eb3b2e583e639ef32dd798
INFO: Query nodes: Raymond Yip, winner, Miss Chinese International Pageant, 1988 (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 33 relations
INFO: Query edges: movie, directed by Raymond Yip, Miss Chinese International Pageant 1988 (top_k:20, cosine:0.2)
INFO: Global query: 22 entites, 20 relations
INFO: Raw search results: 29 entities, 35 relations, 0 vector chunks
INFO: After truncation: 29 entities, 35 relations
INFO: Selecting 29 from 29 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 35 relations
INFO: Round-robin merged chunks: 29 -> 29 (deduplicated 0)
INFO: Final context: 29 entities, 35 relations, 8 chunks
INFO: Final chunks S+F/O: E6/1 E7/2 E5/3 E7/4 E5/5 E3/6 E5/7 E2/8
INFO:  == LLM cache == saving: hybrid:query:136ba431102e3d2265471ebf8edfa699

[hybrid] 5aba480c55429939ce03dc77 | ok | 'The movie "Beauty and the Breast," directed by Raymond Yip, is from Hong Kong. The film stars Michelle Reis, who won the Miss Chinese International Pageant in 1988. \n\n### References\n\n- [1] Beauty and the Breast'

INFO:  == LLM cache == saving: hybrid:keywords:85a8100b6e087c2bec05e334f80450b4
INFO: Query nodes: 2013 Valdosta State Blazers, Gulf South Conference (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 42 relations
INFO: Query edges: sports, college football, conference affiliation (top_k:20, cosine:0.2)
INFO: Global query: 30 entites, 20 relations
INFO: Raw search results: 46 entities, 56 relations, 0 vector chunks
INFO: After truncation: 46 entities, 56 relations
INFO: Selecting 28 from 28 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 56 relations
INFO: Round-robin merged chunks: 28 -> 28 (deduplicated 0)
INFO: Final context: 46 entities, 56 relations, 8 chunks
INFO: Final chunks S+F/O: E7/1 E6/2 E6/3 E5/4 E5/5 E3/6 E4/7 E5/8
INFO:  == LLM cache == saving: hybrid:query:e63a5f598bcebf43386fb88db4ee25ca

[hybrid] 5a7a1e635542990783324e69 | ok | 'The 2013 Valdosta State Blazers football team and the Gulf South Conference are part of NCAA Division II. \n\n### References\n\n- [1] Valdosta State Blazers football\n- [2] 2013 Valdosta State Blazers football team\n- [3] Gulf South Conference'

INFO:  == LLM cache == saving: hybrid:keywords:3bef7276a7d1b1092ec992975b7b4247
INFO: Query nodes: name, first performed (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 32 relations
INFO: Query edges: reform opera, Vienna, Empress Maria Theresa (top_k:20, cosine:0.2)
INFO: Global query: 24 entites, 20 relations
INFO: Raw search results: 43 entities, 50 relations, 0 vector chunks
INFO: After truncation: 43 entities, 50 relations
INFO: Selecting 29 from 29 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 50 relations
INFO: Round-robin merged chunks: 29 -> 29 (deduplicated 0)
INFO: Final context: 43 entities, 50 relations, 8 chunks
INFO: Final chunks S+F/O: E4/1 E5/2 E5/3 E2/4 E3/5 E2/6 E2/7 E6/8
INFO:  == LLM cache == saving: hybrid:query:2d33c0bf2ff9b3a8fff32c0d5c87a7ad

[hybrid] 5a8466a75542993344746108 | ok | 'The so-called reform opera for Vienna that came before "Orfeo ed Euridice," which was first performed in the presence of Empress Maria Theresa, is "Alceste." \n\n### References\n\n- [1] Orfeo ed Euridice\n- [2] Paride ed Elena'

INFO:  == LLM cache == saving: hybrid:keywords:16030f1d56a6d66daf660f9edf1350a9
INFO: Query nodes: Blackfin (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 37 relations
INFO: Query edges: Blackfin processors, company headquarters, city (top_k:20, cosine:0.2)
INFO: Global query: 25 entites, 20 relations
INFO: Raw search results: 41 entities, 51 relations, 0 vector chunks
INFO: After truncation: 41 entities, 51 relations
INFO: Selecting 25 from 25 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 51 relations
INFO: Round-robin merged chunks: 25 -> 25 (deduplicated 0)
INFO: Final context: 41 entities, 51 relations, 8 chunks
INFO: Final chunks S+F/O: E7/1 E4/2 E10/3 E2/4 E4/5 E1/6 E3/7 E1/8
INFO:  == LLM cache == saving: hybrid:query:c682477cda4daef5787138b7b1dee0aa

[hybrid] 5ac132a755429964131be17c | ok | 'The Blackfin is a family of processors developed by Analog Devices, which is headquartered in Norwood, Massachusetts.\n\n### References\n- [1] Document ID: hotpot-000135'

INFO:  == LLM cache == saving: hybrid:keywords:593e90a1146dc2019da1686f7ab46502
INFO: Query nodes: Kurt Russell (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 25 relations
INFO: Query edges: company, contract, anti-hero, Escape From New York (top_k:20, cosine:0.2)
INFO: Global query: 30 entites, 20 relations
INFO: Raw search results: 50 entities, 45 relations, 0 vector chunks
INFO: After truncation: 50 entities, 45 relations
INFO: Selecting 94 from 94 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 45 relations
INFO: Round-robin merged chunks: 94 -> 94 (deduplicated 0)
INFO: Final context: 50 entities, 45 relations, 8 chunks
INFO: Final chunks S+F/O: E9/1 E2/2 E2/3 E1/4 E4/5 E1/6 E4/7 E1/8
INFO:  == LLM cache == saving: hybrid:query:bd2b54e72c1f5ede9552c98fac3a484b

[hybrid] 5addcfd65542997dc790703e | ok | 'Kurt Russell signed a ten-year contract with The Walt Disney Company, where he became one of its top stars in the 1970s, during his portrayal of the anti-hero Snake Plissken from "Escape From New York" and "Escape From L.A."\n\n### References\n\n- [1] Kurt Russell'

INFO:  == LLM cache == saving: hybrid:keywords:2360e4bac23b66fda7fd94b74f9279c6
INFO: Query nodes: chicken, dance (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 36 relations
INFO: Query edges: dance patterns, change of pace (top_k:20, cosine:0.2)
INFO: Global query: 26 entites, 20 relations
INFO: Raw search results: 36 entities, 41 relations, 0 vector chunks
INFO: After truncation: 36 entities, 41 relations
INFO: Selecting 11 from 11 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 41 relations
INFO: Round-robin merged chunks: 11 -> 11 (deduplicated 0)
INFO: Final context: 36 entities, 41 relations, 8 chunks
INFO: Final chunks S+F/O: E5/1 E3/2 E6/3 E8/4 E4/5 E4/6 E3/7 E2/8
INFO:  == LLM cache == saving: hybrid:query:fdbaef30dc353bd78817a8fb7e14b3d6

[hybrid] 5ac509e95542994611c8b333 | ok | 'The Chicken is a type of dance pattern that served as a change of pace step while performing the Twist. \n\n### References\n- [1] Chicken (dance)'

INFO:  == LLM cache == saving: hybrid:keywords:45805c60ad758d0b013c64b7b47e9367
INFO: Query nodes: David Huntsinger (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 43 relations
INFO: Query edges: David Huntsinger, gospel singer, July (top_k:20, cosine:0.2)
INFO: Global query: 21 entites, 20 relations
INFO: Raw search results: 28 entities, 43 relations, 0 vector chunks
INFO: After truncation: 28 entities, 43 relations
INFO: Selecting 27 from 27 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 43 relations
INFO: Round-robin merged chunks: 27 -> 27 (deduplicated 0)
INFO: Final context: 28 entities, 43 relations, 8 chunks
INFO: Final chunks S+F/O: E24/1 E1/2 E1/3 E1/4 E1/5 E1/6 E1/7 E1/8
INFO:  == LLM cache == saving: hybrid:query:749d2daff575399e12b5b9c13ddea421

[hybrid] 5a774e9c55429972597f14f3 | ok | 'David Huntsinger has worked with the gospel singer Sandi Patti, who was born on July 12, 1956.\n\n### References\n\n- [1] David Huntsinger'

INFO:  == LLM cache == saving: hybrid:keywords:904a6ecdd7b00302fcbafa074aad9499
INFO: Query nodes: address, building (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 44 relations
INFO: Query edges: tallest building, New Hampshire, U.S. Route 3, 1972 (top_k:20, cosine:0.2)
INFO: Global query: 21 entites, 20 relations
INFO: Raw search results: 39 entities, 59 relations, 0 vector chunks
INFO: After truncation: 39 entities, 59 relations
INFO: Selecting 52 from 52 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 59 relations
INFO: Round-robin merged chunks: 52 -> 52 (deduplicated 0)
INFO: Final context: 39 entities, 59 relations, 8 chunks
INFO: Final chunks S+F/O: E4/1 E4/2 E3/3 E3/4 E3/5 E3/6 E2/7 E3/8
INFO:  == LLM cache == saving: hybrid:query:2e3c42900a76e722c80ab25560093b51

[hybrid] 5a860d09554299211dda2a53 | ok | 'The address of the building that was the tallest in New Hampshire when completed in 1972 is 1000 Elm Street, Manchester, New Hampshire. This building is known as Brady Sullivan Plaza. \n\n### References\n\n- [1] Brady Sullivan Plaza'

INFO:  == LLM cache == saving: hybrid:keywords:798c6528b633d969b2d808cdca7f9a5c
INFO: Query nodes: Torra di Tizzà (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 44 relations
INFO: Query edges: Torra di Tizzà, protection, people (top_k:20, cosine:0.2)
INFO: Global query: 20 entites, 20 relations
INFO: Raw search results: 31 entities, 44 relations, 0 vector chunks
INFO: After truncation: 31 entities, 44 relations
INFO: Selecting 16 from 16 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 44 relations
INFO: Round-robin merged chunks: 16 -> 16 (deduplicated 0)
INFO: Final context: 31 entities, 44 relations, 8 chunks
INFO: Final chunks S+F/O: E4/1 E4/2 E4/3 E4/4 E3/5 E5/6 E4/7 E4/8
INFO:  == LLM cache == saving: hybrid:query:686b5fddb616bb156026a7e0d04f8bb0

[hybrid] 5a77a15b5542995d83181226 | ok | 'The Torra di Tizzà was created to protect against the Barbary pirates. \n\n### References\n\n- [1] Torra di Tizzà'

INFO:  == LLM cache == saving: hybrid:keywords:ef709ee19e70edb88d7be3e2a94caa19
INFO: Query nodes: 1922, 1985, Delacorte Press (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 32 relations
INFO: Query edges: birth year, book publication, Delacorte Press (top_k:20, cosine:0.2)
INFO: Global query: 29 entites, 20 relations
INFO: Raw search results: 40 entities, 38 relations, 0 vector chunks
INFO: After truncation: 40 entities, 38 relations
INFO: Selecting 26 from 26 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 38 relations
INFO: Round-robin merged chunks: 26 -> 26 (deduplicated 0)
INFO: Final context: 40 entities, 38 relations, 8 chunks
INFO: Final chunks S+F/O: E5/1 E3/2 E2/3 E3/4 E2/5 E2/6 E1/7 E3/8
INFO:  == LLM cache == saving: hybrid:query:522b3b90715e233319157b909d886d26

[hybrid] 5a77101d5542994aec3b71d7 | ok | 'I do not have enough information to answer. \n\n### References'

INFO:  == LLM cache == saving: hybrid:keywords:7a34bbc4fc08da7fca8748badde319d5
INFO: Query nodes: Stan Winters (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 49 relations
INFO: Query edges: American comedian, Saturday Night Live, sitcom Martin (top_k:20, cosine:0.2)
INFO: Global query: 22 entites, 20 relations
INFO: Raw search results: 41 entities, 68 relations, 0 vector chunks
INFO: After truncation: 41 entities, 68 relations
INFO: Selecting 34 from 34 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 68 relations
INFO: Round-robin merged chunks: 34 -> 34 (deduplicated 0)
INFO: Final context: 41 entities, 68 relations, 8 chunks
INFO: Final chunks S+F/O: E3/1 E3/2 E6/3 E3/4 E3/5 E2/6 E4/7 E4/8
INFO:  == LLM cache == saving: hybrid:query:fdd9795f7da00c68d8b0ceffeff93613

[hybrid] 5ab30336554299166977417c | ok | 'The American comedian who starred in the original cast of Saturday Night Live and played Stan Winters in the sitcom Martin is **Garrett Morris**. \n\n### References\n\n- [1] Garrett Morris\n- [2] Martin (TV series)'

INFO:  == LLM cache == saving: hybrid:keywords:2780ba4c7858ad92f8467b810423a92c
INFO: Query nodes: Mudvayne, Hellyeah, country (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 34 relations
INFO: Query edges: music bands, origin (top_k:20, cosine:0.2)
INFO: Global query: 38 entites, 20 relations
INFO: Raw search results: 53 entities, 51 relations, 0 vector chunks
INFO: After truncation: 53 entities, 51 relations
INFO: Selecting 132 from 183 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 51 relations
INFO: Round-robin merged chunks: 132 -> 132 (deduplicated 0)
INFO: Final context: 53 entities, 51 relations, 8 chunks
INFO: Final chunks S+F/O: E3/1 E15/2 E3/3 E6/4 E3/5 E4/6 E2/7 E1/8
INFO:  == LLM cache == saving: hybrid:query:9df57e4c201fe6cf56f434e11384a171

[hybrid] 5ade3e69554299728e26c68d | ok | 'Mudvayne and Hellyeah are both from the **United States**. \n\n### References\n\n- [1] Mudvayne\n- [2] Hellyeah'

INFO:  == LLM cache == saving: hybrid:keywords:6087cb146112ee3f12b3ba4d5eee5e56
INFO: Query nodes: Big Fish Theory (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 32 relations
INFO: Query edges: rapper, album, music styles, Detroit techno (top_k:20, cosine:0.2)
INFO: Global query: 20 entites, 20 relations
INFO: Raw search results: 40 entities, 52 relations, 0 vector chunks
INFO: After truncation: 40 entities, 52 relations
INFO: Selecting 75 from 75 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 52 relations
INFO: Round-robin merged chunks: 75 -> 75 (deduplicated 0)
INFO: Final context: 40 entities, 52 relations, 8 chunks
INFO: Final chunks S+F/O: E13/1 E10/2 E5/3 E4/4 E2/5 E4/6 E6/7 E2/8
INFO:  == LLM cache == saving: hybrid:query:525749a3e6309bacb579c8db0b541cf7

[hybrid] 5ab2fccb5542991669774176 | ok | 'The album *Big Fish Theory* was released by American rapper Vince Staples, and it features a number of styles of music including Detroit techno.\n\n### References\n\n- [1] Big Fish Theory\n- [2] Detroit techno\n- [3] Techno'

INFO:  == LLM cache == saving: hybrid:keywords:92f005b7400fe7b6c1db178fc447d55b
INFO: Query nodes: Jerry Tarkanian, team (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 77 relations
INFO: Query edges: 1991 NCAA tournament, UNLV Runnin' Rebels, basketball, semifinals (top_k:20, cosine:0.2)
INFO: Global query: 23 entites, 20 relations
INFO: Raw search results: 39 entities, 83 relations, 0 vector chunks
INFO: After truncation: 39 entities, 83 relations
INFO: Selecting 58 from 58 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 83 relations
INFO: Round-robin merged chunks: 58 -> 58 (deduplicated 0)
INFO: Final context: 39 entities, 83 relations, 8 chunks
INFO: Final chunks S+F/O: E5/1 E6/2 E6/3 E5/4 E1/5 E4/6 E6/7 E6/8
INFO:  == LLM cache == saving: hybrid:query:63fb511ff62d517a287a5510ca9a8da1

[hybrid] 5a7ce7b755429909bec76872 | ok | "The 1990–91 UNLV Runnin' Rebels basketball team coached by Jerry Tarkanian lost in the semifinals of the 1991 NCAA tournament to Duke. \n\n### References\n* [1] 1990–91 UNLV Runnin' Rebels basketball team"

INFO:  == LLM cache == saving: hybrid:keywords:cf29dd524db413a6e280b4d85a27cdd8
INFO: Query nodes: Experts Network, 2000 (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 43 relations
INFO: Query edges: Pro Football Hall of Fame, NFL, sports analysts (top_k:20, cosine:0.2)
INFO: Global query: 21 entites, 20 relations
INFO: Raw search results: 37 entities, 59 relations, 0 vector chunks
INFO: After truncation: 37 entities, 59 relations
INFO: Selecting 26 from 26 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 59 relations
INFO: Round-robin merged chunks: 26 -> 26 (deduplicated 0)
INFO: Final context: 37 entities, 59 relations, 8 chunks
INFO: Final chunks S+F/O: E6/1 E2/2 E3/3 E6/4 E3/5 E3/6 E3/7 E3/8
INFO:  == LLM cache == saving: hybrid:query:0690dc9da63eff5dc53908517b9297ac

[hybrid] 5a7b1c0a55429931da12c9c9 | ok | 'Howie Long, a sports analyst for The Experts Network, was inducted into the Pro Football Hall of Fame in 2000 and played in the NFL for 13 seasons.\n\n### References\n\n- [1] The Experts Network\n- [2] Howie Long'

INFO:  == LLM cache == saving: hybrid:keywords:a23a9cb2fd1e345a1d9ae97baa41b97d
INFO: Query nodes: president, CEO, Tracinda Corporation (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 47 relations
INFO: Query edges: book purchase, corporate leadership (top_k:20, cosine:0.2)
INFO: Global query: 24 entites, 20 relations
INFO: Raw search results: 43 entities, 64 relations, 0 vector chunks
INFO: After truncation: 43 entities, 64 relations
INFO: Selecting 23 from 23 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 64 relations
INFO: Round-robin merged chunks: 23 -> 23 (deduplicated 0)
INFO: Final context: 43 entities, 64 relations, 8 chunks
INFO: Final chunks S+F/O: E4/1 E7/2 E3/3 E1/4 E2/5 E1/6 E1/7 E2/8
INFO:  == LLM cache == saving: hybrid:query:17493ac600c5d610c5bbc4d3d3932f3b

[hybrid] 5a78b386554299148911f949 | ok | 'I do not have enough information to answer. \n\n### References\n- None'

INFO:  == LLM cache == saving: hybrid:keywords:de9ad86f18e53c9fb218a8a23e55e368
INFO: Query nodes: Love Is All Around (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 36 relations
INFO: Query edges: British romantic comedy, 1994 (top_k:20, cosine:0.2)
INFO: Global query: 26 entites, 20 relations
INFO: Raw search results: 45 entities, 55 relations, 0 vector chunks
INFO: After truncation: 45 entities, 55 relations
INFO: Selecting 53 from 53 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 55 relations
INFO: Round-robin merged chunks: 53 -> 53 (deduplicated 0)
INFO: Final context: 45 entities, 55 relations, 8 chunks
INFO: Final chunks S+F/O: E3/1 E11/2 E1/3 E3/4 E3/5 E1/6 E1/7 E2/8
INFO:  == LLM cache == saving: hybrid:query:4515f8b1bd8feae0ed354b7756be0f96

[hybrid] 5a75176a5542993748c897b6 | ok | 'The 1994 British romantic comedy that featured the song "Love Is All Around" is **"Four Weddings and a Funeral."**\n\n### References\n\n- [1] Four Weddings and a Funeral\n- [2] Reg Presley'

INFO:  == LLM cache == saving: hybrid:keywords:956b2b1c61ca4abb6f104fc3e72462a0
INFO: Query nodes: Bill Madlock, third baseman, team (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 47 relations
INFO: Query edges: baseball, World Series, batting title record (top_k:20, cosine:0.2)
INFO: Global query: 23 entites, 20 relations
INFO: Raw search results: 34 entities, 56 relations, 0 vector chunks
INFO: After truncation: 34 entities, 56 relations
INFO: Selecting 15 from 15 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 56 relations
INFO: Round-robin merged chunks: 15 -> 15 (deduplicated 0)
INFO: Final context: 34 entities, 56 relations, 8 chunks
INFO: Final chunks S+F/O: E5/1 E9/2 E5/3 E5/4 E4/5 E3/6 E4/7 E3/8
INFO:  == LLM cache == saving: hybrid:query:b5032774cef135c84e9a6ee4f929aa58

[hybrid] 5a7a562355429941d65f25ba | ok | "Wade Boggs, the player who eclipsed Bill Madlock's batting title record for a third baseman, won the World Series with the New York Yankees in 1996. \n\n### References\n\n- [1] Bill Madlock\n- [2] Wade Boggs"

INFO:  == LLM cache == saving: hybrid:keywords:b8899710341a393addcff04474ced96f
INFO: Query nodes: Angelina Jolie (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 64 relations
INFO: Query edges: Christian Evangelist, US prisoner of war survivor, film directed by Angelina Jolie (top_k:20, cosine:0.2)
INFO: Global query: 20 entites, 20 relations
INFO: Raw search results: 27 entities, 65 relations, 0 vector chunks
INFO: After truncation: 27 entities, 65 relations
INFO: Selecting 32 from 32 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 65 relations
INFO: Round-robin merged chunks: 32 -> 32 (deduplicated 0)
INFO: Final context: 27 entities, 65 relations, 8 chunks
INFO: Final chunks S+F/O: E11/1 E8/2 E2/3 E3/4 E2/5 E2/6 E2/7 E2/8
INFO:  == LLM cache == saving: hybrid:query:c0a61aee552b2ca9069ba6b058e67db4

[hybrid] 5ac245015542992f1f2b3829 | ok | 'Louis Zamperini was a Christian evangelist and US prisoner of war survivor who was the basis for the film "Unbroken," which was directed by Angelina Jolie.\n\n### References\n* [1] Unbroken (film)\n* [2] Angelina Jolie filmography'

INFO:  == LLM cache == saving: hybrid:keywords:df873bf1ea8c2c8e5da11e3da4bb7c13
INFO: Query nodes: Alexander Trachtenberg, Act (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 38 relations
INFO: Query edges: Second Red Scare, conviction, legal Act (top_k:20, cosine:0.2)
INFO: Global query: 15 entites, 20 relations
INFO: Raw search results: 33 entities, 56 relations, 0 vector chunks
INFO: After truncation: 33 entities, 56 relations
INFO: Selecting 82 from 89 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 56 relations
INFO: Round-robin merged chunks: 82 -> 82 (deduplicated 0)
INFO: Final context: 33 entities, 56 relations, 8 chunks
INFO: Final chunks S+F/O: E3/1 E4/2 E3/3 E5/4 E2/5 E4/6 E2/7 E3/8
INFO:  == LLM cache == saving: hybrid:query:5ccd1e6e101ad8620991d70c33719473

[hybrid] 5a8a32d65542992d82986ef4 | ok | 'During the Second Red Scare, Alexander Trachtenberg was convicted under the Smith Act. \n\n### References\n\n- [1] Alexander Trachtenberg\n- [2] Red Scare\n- [3] McCarthyism'

INFO:  == LLM cache == saving: hybrid:keywords:4eeabb132432a3069c55f4569bbf5499
INFO: Query nodes: The Reels, late 1960's, early 1970's (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 55 relations
INFO: Query edges: American rock band, cover song, 1986 (top_k:20, cosine:0.2)
INFO: Global query: 33 entites, 20 relations
INFO: Raw search results: 44 entities, 68 relations, 0 vector chunks
INFO: After truncation: 44 entities, 68 relations
INFO: Selecting 30 from 30 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 68 relations
INFO: Round-robin merged chunks: 30 -> 30 (deduplicated 0)
INFO: Final context: 44 entities, 68 relations, 8 chunks
INFO: Final chunks S+F/O: E6/1 E2/2 E4/3 E1/4 E1/5 E1/6 E2/7 E2/8
INFO:  == LLM cache == saving: hybrid:query:709c455a8ff895c4defbe35fa82b8fc7

[hybrid] 5a8ee7c95542990e94052bb1 | ok | 'The Reels covered the song "Bad Moon Rising," originally released by the American rock band Creedence Clearwater Revival, which was active in the late 1960s and early 1970s. The Reels\' cover reached No. 11 on the Kent Music Report Singles Chart in 1986. \n\n### References\n\n- [1] The Reels\n- [2] Creedence Clearwater Revival'

INFO:  == LLM cache == saving: hybrid:keywords:7f74b7c4b10a30a7ba6d72711ca7e951
WARNING: low_level_keywords is empty
INFO: Query edges: Wiener Werkstätte Style, art movement, eras (top_k:20, cosine:0.2)
INFO: Global query: 28 entites, 20 relations
INFO: Raw search results: 28 entities, 20 relations, 0 vector chunks
INFO: After truncation: 28 entities, 20 relations
INFO: Selecting 30 from 30 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 20 relations
INFO: Round-robin merged chunks: 30 -> 30 (deduplicated 0)
INFO: Final context: 28 entities, 20 relations, 8 chunks
INFO: Final chunks S+F/O: E5/1 E5/2 E2/3 E3/4 E2/5 E3/6 E2/7 E3/8
INFO:  == LLM cache == saving: hybrid:query:8b8a94254a09f56fe2aefd90a7031921

[hybrid] 5a89cc99554299669944a5ae | ok | 'The Wiener Werkstätte Style emerged during the early 20th century and significantly contributed to the establishment of the Modernist movement, which arose from cultural transformations during the late 19th and early 20th centuries. Notably, key developments occurred around the time of the 14th Exhibition of the Vienna Sezession in 1902, marking the rise of Viennese artists and their radical styles.\n\n### References\n\n- [1] Wiener Werkstätte Style\n- [2] Modernism'

INFO:  == LLM cache == saving: hybrid:keywords:44dec775fdb8f2a4ebef058f546d7b6e
INFO: Query nodes: Star, Full Frontal (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 37 relations
INFO: Query edges: British-Canadian-American comedy, satirical comedy, Ricky Gervais, sketch comedy (top_k:20, cosine:0.2)
INFO: Global query: 23 entites, 20 relations
INFO: Raw search results: 43 entities, 57 relations, 0 vector chunks
INFO: After truncation: 43 entities, 57 relations
INFO: Selecting 45 from 45 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 57 relations
INFO: Round-robin merged chunks: 45 -> 45 (deduplicated 0)
INFO: Final context: 43 entities, 57 relations, 8 chunks
INFO: Final chunks S+F/O: E9/1 E7/2 E2/3 E4/4 E8/5 E3/6 E2/7 E2/8
INFO:  == LLM cache == saving: hybrid:query:5c681dc29841576ae207bc7e440bc807

[hybrid] 5a7f924c55429969796c1aba | ok | 'The star of the British-Canadian-American satirical comedy who began his career in the sketch comedy series "Full Frontal" is Eric Bana. \n\n### References\n\n- [1] Full Frontal (Australian TV series)\n- [2] Special Correspondents\n- [3] David Brent: Life on the Road'

INFO:  == LLM cache == saving: hybrid:keywords:479c5141982a8092208771eebf79280a
INFO: Query nodes: person, right hand man (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 29 relations
INFO: Query edges: birth date, Samuel Flores Borrego (top_k:20, cosine:0.2)
INFO: Global query: 33 entites, 20 relations
INFO: Raw search results: 53 entities, 49 relations, 0 vector chunks
INFO: After truncation: 53 entities, 49 relations
INFO: Selecting 58 from 58 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 49 relations
INFO: Round-robin merged chunks: 58 -> 58 (deduplicated 0)
INFO: Final context: 53 entities, 49 relations, 8 chunks
INFO: Final chunks S+F/O: E4/1 E3/2 E2/3 E3/4 E3/5 E2/6 E2/7 E1/8
INFO:  == LLM cache == saving: hybrid:query:d786a872e80e4ab06cffb1040e82c8fb

[hybrid] 5ac00584554299012d1db575 | ok | 'Samuel Flores Borrego became the right-hand man of Jorge Eduardo Costilla Sánchez, who was born on August 1, 1971.\n\n### References\n- [1] Jorge Eduardo Costilla Sánchez'

INFO:  == LLM cache == saving: hybrid:keywords:1a5ef6cc78e09f8382a73ad29f1edd1e
INFO: Query nodes: Raúl Arellano (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 66 relations
INFO: Query edges: football tournament, Mexico, 1954 (top_k:20, cosine:0.2)
INFO: Global query: 25 entites, 20 relations
INFO: Raw search results: 43 entities, 82 relations, 0 vector chunks
INFO: After truncation: 43 entities, 82 relations
INFO: Selecting 60 from 60 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 82 relations
INFO: Round-robin merged chunks: 60 -> 60 (deduplicated 0)
INFO: Final context: 43 entities, 82 relations, 8 chunks
INFO: Final chunks S+F/O: E4/1 E5/2 E4/3 E2/4 E3/5 E5/6 E3/7 E2/8
INFO:  == LLM cache == saving: hybrid:query:7dc0233ca0220820af58fd65afba7271

[hybrid] 5ae721c15542996d980e7cbc | ok | 'Raúl Arellano played for Mexico in the **1954 FIFA World Cup**. \n\n### References\n\n- [1] Raúl Arellano\n- [2] 1954 FIFA World Cup'

INFO:  == LLM cache == saving: hybrid:keywords:de587896d008c793819603f89cac7459
INFO: Query nodes: Jed Hoyer, John William Henry II (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 36 relations
INFO: Query edges: age comparison, sports executives (top_k:20, cosine:0.2)
INFO: Global query: 29 entites, 20 relations
INFO: Raw search results: 47 entities, 53 relations, 0 vector chunks
INFO: After truncation: 47 entities, 53 relations
INFO: Selecting 45 from 45 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 53 relations
INFO: Round-robin merged chunks: 45 -> 45 (deduplicated 0)
INFO: Final context: 47 entities, 53 relations, 8 chunks
INFO: Final chunks S+F/O: E7/1 E5/2 E1/3 E1/4 E1/5 E1/6 E1/7 E1/8
INFO:  == LLM cache == saving: hybrid:query:278d80868978408bd72ac6917eb621b8

[hybrid] 5a862974554299211dda2a95 | ok | 'John William Henry II is older than Jed Hoyer. John William Henry II was born on September 13, 1949, while Jed Hoyer was born on December 7, 1973.\n\n### References\n\n- [1] Jed Hoyer\n- [2] John W. Henry'

INFO:  == LLM cache == saving: hybrid:keywords:d9e088438528bb5e4ae801cf969cfc39
INFO: Query nodes: Bulls, Knicks, player, tall (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 36 relations
INFO: Query edges: Bulls–Knicks rivalry, height of player (top_k:20, cosine:0.2)
INFO: Global query: 22 entites, 20 relations
INFO: Raw search results: 31 entities, 42 relations, 0 vector chunks
INFO: After truncation: 31 entities, 42 relations
INFO: Selecting 22 from 22 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 42 relations
INFO: Round-robin merged chunks: 22 -> 22 (deduplicated 0)
INFO: Final context: 31 entities, 42 relations, 8 chunks
INFO: Final chunks S+F/O: E7/1 E3/2 E10/3 E2/4 E2/5 E1/6 E7/7 E2/8
INFO:  == LLM cache == saving: hybrid:query:32700b859963a483878f71469d2b2d7d

[hybrid] 5abe49765542991f6610611f | ok | 'The Bulls–Knicks rivalry involved well-known player John Starks, who was listed at 6\'5" during his NBA playing career. \n\n### References\n\n- [1] John Starks (basketball)\n- [2] Bulls–Knicks rivalry'

INFO:  == LLM cache == saving: hybrid:keywords:326da48be38d8fe0175f0b977a417a72
INFO: Query nodes: Olivia DeJonge, Shyamalan, horror film (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 48 relations
INFO: Query edges: American horror film, Olivia DeJonge, Shyamalan (top_k:20, cosine:0.2)
INFO: Global query: 27 entites, 20 relations
INFO: Raw search results: 35 entities, 56 relations, 0 vector chunks
INFO: After truncation: 35 entities, 56 relations
INFO: Selecting 28 from 28 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 56 relations
INFO: Round-robin merged chunks: 28 -> 28 (deduplicated 0)
INFO: Final context: 35 entities, 56 relations, 8 chunks
INFO: Final chunks S+F/O: E3/1 E4/2 E3/3 E4/4 E2/5 E5/6 E2/7 E8/8
INFO:  == LLM cache == saving: hybrid:query:31a93c6cf98b2dc2c7afd746984e6eb7

[hybrid] 5a8ed10b5542995085b374a0 | ok | 'Olivia DeJonge starred in the American horror film directed by M. Night Shyamalan called **The Visit**.\n\n### References\n\n- [1] The Visit (2015 American film)\n- [2] Olivia DeJonge'

INFO:  == LLM cache == saving: hybrid:keywords:6d987463b339ce1e6f1c02c3830e7227
INFO: Query nodes: private coeducational liberal arts college, founded year, professor (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 53 relations
INFO: Query edges: Minnesota State High School Mathematics League, history, education (top_k:20, cosine:0.2)
INFO: Global query: 22 entites, 20 relations
INFO: Raw search results: 41 entities, 71 relations, 0 vector chunks
INFO: After truncation: 41 entities, 71 relations
INFO: Selecting 84 from 84 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 71 relations
INFO: Round-robin merged chunks: 84 -> 84 (deduplicated 0)
INFO: Final context: 41 entities, 71 relations, 8 chunks
INFO: Final chunks S+F/O: E5/1 E4/2 E5/3 E1/4 E2/5 E5/6 E7/7 E2/8
INFO:  == LLM cache == saving: hybrid:query:88430aa339715211dac38316e87ceadb

[hybrid] 5abd8c295542992ac4f382ab | ok | 'The Minnesota State High School Mathematics League was founded by Wayne Roberts, a professor at Macalester College, which was founded in 1874.\n\n### References\n\n- [1] Minnesota State High School Mathematics League\n- [2] Macalester College'

INFO:  == LLM cache == saving: hybrid:keywords:8d1358af5c4d7e799c17531a9ebee43d
INFO: Query nodes: month, day (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 24 relations
INFO: Query edges: Park Seo-joon, television series, premiere date (top_k:20, cosine:0.2)
INFO: Global query: 34 entites, 20 relations
INFO: Raw search results: 54 entities, 44 relations, 0 vector chunks
INFO: After truncation: 54 entities, 44 relations
INFO: Selecting 70 from 70 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 44 relations
INFO: Round-robin merged chunks: 70 -> 70 (deduplicated 0)
INFO: Final context: 54 entities, 44 relations, 8 chunks
INFO: Final chunks S+F/O: E5/1 E2/2 E2/3 E2/4 E3/5 E2/6 E1/7 E4/8
INFO:  == LLM cache == saving: hybrid:query:ce1a55d07f70aabb9370a74890f371af

[hybrid] 5a83697e5542996488c2e441 | ok | 'Park Seo-joon is best known for his role in the television series "Fight for My Way," which premiered on May 22, 2017.\n\n### References\n\n- [1] Fight for My Way'

INFO:  == LLM cache == saving: hybrid:keywords:d66778e6991cd93b1b343180fb2f4adc
INFO: Query nodes: Julianne Moore, movie, 2002, Oscar (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 38 relations
INFO: Query edges: Julianne Moore, Oscar winning movie, 2002 (top_k:20, cosine:0.2)
INFO: Global query: 25 entites, 20 relations
INFO: Raw search results: 34 entities, 40 relations, 0 vector chunks
INFO: After truncation: 34 entities, 40 relations
INFO: Selecting 26 from 26 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 40 relations
INFO: Round-robin merged chunks: 26 -> 26 (deduplicated 0)
INFO: Final context: 34 entities, 40 relations, 8 chunks
INFO: Final chunks S+F/O: E3/1 E3/2 E2/3 E3/4 E5/5 E2/6 E1/7 E2/8
INFO:  == LLM cache == saving: hybrid:query:1ddca87d96e566072de170ca1afb70e3

[hybrid] 5ae61dce5542992663a4f262 | ok | 'In the 2002 Oscar-winning movie "The Hours," Julianne Moore played the role of Laura Brown, a character whose story explores themes of depression and the search for identity. \n\n### References\n- [1] The Hours (novel)'

INFO:  == LLM cache == saving: hybrid:keywords:d01c3019be8b3f94b94b5918c806c961
INFO: Query nodes: Backford Cross (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 38 relations
INFO: Query edges: truck road (top_k:20, cosine:0.2)
INFO: Global query: 30 entites, 20 relations
INFO: Raw search results: 50 entities, 58 relations, 0 vector chunks
INFO: After truncation: 50 entities, 58 relations
INFO: Selecting 49 from 49 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 58 relations
INFO: Round-robin merged chunks: 49 -> 49 (deduplicated 0)
INFO: Final context: 50 entities, 58 relations, 8 chunks
INFO: Final chunks S+F/O: E8/1 E3/2 E4/3 E2/4 E8/5 E1/6 E1/7 E8/8
INFO:  == LLM cache == saving: hybrid:query:29ffd9c4b83c3cfc83ec0dd28a7d66f3

[hybrid] 5a75f0ea5542994ccc91866c | ok | 'I do not have enough information to answer. \n\n### References'

INFO:  == LLM cache == saving: hybrid:keywords:4534e93d69abbcf0980b0b866b03b611
INFO: Query nodes: Peter Hackett, gap (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 50 relations
INFO: Query edges: Scotish-Irish migration, Wilderness Road, states junction (top_k:20, cosine:0.2)
INFO: Global query: 32 entites, 20 relations
INFO: Raw search results: 50 entities, 68 relations, 0 vector chunks
INFO: After truncation: 50 entities, 68 relations
INFO: Selecting 57 from 57 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 68 relations
INFO: Round-robin merged chunks: 57 -> 57 (deduplicated 0)
INFO: Final context: 50 entities, 68 relations, 8 chunks
INFO: Final chunks S+F/O: E8/1 E3/2 E5/3 E5/4 E2/5 E2/6 E2/7 E3/8
INFO:  == LLM cache == saving: hybrid:query:cb91bcbdb1f765aa5111cb16eb963fc3

[hybrid] 5ab54e145542992aa134a2a1 | ok | 'The three states that junction near the Cumberland Gap, which Peter Hackett traveled along during the Scotch-Irish migration along the Wilderness Road, are Kentucky, Virginia, and Tennessee. \n\n### References\n\n- [1] Cumberland Gap\n- [2] Wilderness Road'

INFO:  == LLM cache == saving: hybrid:keywords:d7383b2eab3767334b61d38176a323ca
INFO: Query nodes: Richard Williams, former assistant (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 31 relations
INFO: Query edges: University, Athletics Hall of Fame (top_k:20, cosine:0.2)
INFO: Global query: 29 entites, 20 relations
INFO: Raw search results: 49 entities, 51 relations, 0 vector chunks
INFO: After truncation: 49 entities, 51 relations
INFO: Selecting 26 from 26 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 51 relations
INFO: Round-robin merged chunks: 26 -> 26 (deduplicated 0)
INFO: Final context: 49 entities, 51 relations, 8 chunks
INFO: Final chunks S+F/O: E6/1 E5/2 E3/3 E1/4 E4/5 E3/6 E1/7 E7/8
INFO:  == LLM cache == saving: hybrid:query:28b2062641bef259c70515cc83818569

[hybrid] 5a81e4e8554299676cceb140 | ok | "Richard Williams' former assistant, Rick Stansbury, is a member of the Campbellsville University Athletics Hall of Fame.\n\n### References\n\n- [1] Richard Williams (basketball coach)\n- [2] Rick Stansbury"

INFO:  == LLM cache == saving: hybrid:keywords:1a92a5ab5c7bc22394a7591629cc6d20
INFO: Query nodes: set photographer (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 42 relations
INFO: Query edges: nationality, famous photographer, Hollywood film productions (top_k:20, cosine:0.2)
INFO: Global query: 38 entites, 20 relations
INFO: Raw search results: 52 entities, 56 relations, 0 vector chunks
INFO: After truncation: 52 entities, 56 relations
INFO: Selecting 56 from 56 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 56 relations
INFO: Round-robin merged chunks: 56 -> 56 (deduplicated 0)
INFO: Final context: 52 entities, 56 relations, 8 chunks
INFO: Final chunks S+F/O: E4/1 E2/2 E3/3 E2/4 E3/5 E3/6 E2/7 E2/8
INFO:  == LLM cache == saving: hybrid:query:507bc931ac823f572f73952dd3007ec0

[hybrid] 5a7f95685542995d8a8ddeaa | ok | 'The nationality of Ned Scott, a famous photographer who worked as a set photographer in Hollywood film productions, is American. \n\n### References\n\n- [1] Ned Scott'

INFO:  == LLM cache == saving: hybrid:keywords:c39f0468bfce8393a47205d1d1b0f2fb
INFO: Query nodes: 5,457, 2010 (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 27 relations
INFO: Query edges: town, New Hampshire, population, Mount Monadnock (top_k:20, cosine:0.2)
INFO: Global query: 19 entites, 20 relations
INFO: Raw search results: 39 entities, 47 relations, 0 vector chunks
INFO: After truncation: 39 entities, 47 relations
INFO: Selecting 43 from 43 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 47 relations
INFO: Round-robin merged chunks: 43 -> 43 (deduplicated 0)
INFO: Final context: 39 entities, 47 relations, 8 chunks
INFO: Final chunks S+F/O: E4/1 E6/2 E4/3 E4/4 E7/5 E3/6 E3/7 E3/8
INFO:  == LLM cache == saving: hybrid:query:c970274457d14917fcb0b236de19feab

[hybrid] 5a8ce584554299585d9e375c | ok | 'The town in New Hampshire with a population of 5,457 in 2010 that is located by Mount Monadnock is Jaffrey.\n\n### References\n\n- [1] Jaffrey, New Hampshire'

INFO:  == LLM cache == saving: hybrid:keywords:6bf35e67d9ceb9ecc29b1270dcb1539c
INFO: Query nodes: 2106, negatively charged electrons, highly charged ions (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 27 relations
INFO: Query edges: nuclear fusion, magnetically confined fusion, highest pressure (top_k:20, cosine:0.2)
INFO: Global query: 23 entites, 20 relations
INFO: Raw search results: 40 entities, 41 relations, 0 vector chunks
INFO: After truncation: 40 entities, 41 relations
INFO: Selecting 14 from 14 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 41 relations
INFO: Round-robin merged chunks: 14 -> 14 (deduplicated 0)
INFO: Final context: 40 entities, 41 relations, 8 chunks
INFO: Final chunks S+F/O: E3/1 E7/2 E8/3 E1/4 E3/5 E5/6 E3/7 E8/8
INFO:  == LLM cache == saving: hybrid:query:b2344278a9add9fa02c67fcf34e49e33

[hybrid] 5a7b695f5542997c3ec97156 | ok | 'In 2016, the Alcator C-Mod, a magnetically confined nuclear fusion device, achieved the highest pressure of a gaseous mixture of negatively charged electrons and highly charged ions known as "Highly Charged Ions" (HCI).\n\n### References\n\n- [1] Alcator C-Mod\n- [2] Highly charged ion'

INFO:  == LLM cache == saving: hybrid:keywords:b8742252ab5b600a1ac2e9601d449c93
INFO: Query nodes: bay (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 33 relations
INFO: Query edges: Death of Cook, James Cook, coast (top_k:20, cosine:0.2)
INFO: Global query: 25 entites, 20 relations
INFO: Raw search results: 45 entities, 53 relations, 0 vector chunks
INFO: After truncation: 45 entities, 53 relations
INFO: Selecting 54 from 54 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 53 relations
INFO: Round-robin merged chunks: 54 -> 54 (deduplicated 0)
INFO: Final context: 45 entities, 53 relations, 8 chunks
INFO: Final chunks S+F/O: E3/1 E5/2 E5/3 E8/4 E4/5 E2/6 E1/7 E2/8
INFO:  == LLM cache == saving: hybrid:query:8727db9154ac3421998e1197b266571c

[hybrid] 5abdf8c45542993f32c2a072 | ok | "The Death of Cook depicts the death of James Cook at Kealakekua Bay on the Kona coast of the island of Hawai'i.\n\n### References\n- [1] Death of Cook\n- [2] The Death of Captain James Cook (Zoffany)\n- [3] Kealakekua Bay"

INFO:  == LLM cache == saving: hybrid:keywords:9c4334560d8b2b865990fb5b65c8b791
INFO: Query nodes: Italian, language (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 30 relations
INFO: Query edges: Giuseppe Tornatore, film direction, screenwriting, The Best Offer (top_k:20, cosine:0.2)
INFO: Global query: 21 entites, 20 relations
INFO: Raw search results: 41 entities, 50 relations, 0 vector chunks
INFO: After truncation: 41 entities, 50 relations
INFO: Selecting 40 from 40 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 50 relations
INFO: Round-robin merged chunks: 40 -> 40 (deduplicated 0)
INFO: Final context: 41 entities, 50 relations, 8 chunks
INFO: Final chunks S+F/O: E7/1 E8/2 E5/3 E3/4 E3/5 E4/6 E2/7 E2/8
INFO:  == LLM cache == saving: hybrid:query:d5b9cc9f824dc0550a80f9f1ddf536b7

[hybrid] 5aba6d4b5542994dbf019906 | ok | 'Giuseppe Tornatore wrote and directed "The Best Offer" in English, as it is described as an Italian English-language romantic mystery film. \n\n### References\n\n- [1] The Best Offer\n- [2] Giuseppe Tornatore'

INFO:  == LLM cache == saving: hybrid:keywords:eaf37b7c6d34263aaab1cde65651cb41
INFO: Query nodes: Led Zeppelin, Bert Jansch (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 37 relations
INFO: Query edges: British musicians, influence, Davey Graham (top_k:20, cosine:0.2)
INFO: Global query: 30 entites, 20 relations
INFO: Raw search results: 47 entities, 54 relations, 0 vector chunks
INFO: After truncation: 47 entities, 54 relations
INFO: Selecting 29 from 29 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 54 relations
INFO: Round-robin merged chunks: 29 -> 29 (deduplicated 0)
INFO: Final context: 47 entities, 54 relations, 8 chunks
INFO: Final chunks S+F/O: E5/1 E3/2 E3/3 E5/4 E4/5 E4/6 E4/7 E4/8
INFO:  == LLM cache == saving: hybrid:query:3d019e52bb754443f552e2e71e0ee908

[hybrid] 5a887f5c554299206df2b2c0 | ok | 'Eric Clapton is another British musician who was heavily influenced by Davey Graham. \n\n### References\n* [1] Folk, Blues and Beyond\n* [2] Jimmy Page\n* [3] Bill Leader'

INFO:  == LLM cache == saving: hybrid:keywords:c69d8a000c82dda37a98f2b554a69d0f
INFO: Query nodes: Chris Jones, goalkeeper (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 30 relations
INFO: Query edges: semi-professional footballer, Derby County, Yorkshire (top_k:20, cosine:0.2)
INFO: Global query: 24 entites, 20 relations
INFO: Raw search results: 41 entities, 47 relations, 0 vector chunks
INFO: After truncation: 41 entities, 47 relations
INFO: Selecting 19 from 19 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 47 relations
INFO: Round-robin merged chunks: 19 -> 19 (deduplicated 0)
INFO: Final context: 41 entities, 47 relations, 8 chunks
INFO: Final chunks S+F/O: E7/1 E3/2 E2/3 E6/4 E6/5 E5/6 E3/7 E3/8
INFO:  == LLM cache == saving: hybrid:query:44f3ea98ae1362f0b54ccc8391232e29

[hybrid] 5abcedb355429959677d6b4f | ok | 'Chris Jones played with Scott Carson, a goalkeeper for Derby County, during his time with Leeds United, which is in Yorkshire. \n\n### References\n* [1] Chris Jones (footballer, born 1985)\n* [2] Scott Carson'

INFO:  == LLM cache == saving: hybrid:keywords:c406ef9ef27a78db70e4c316bedebd00
INFO: Query nodes: creator, Mouten Cadet (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 22 relations
INFO: Query edges: dynasty, Mouten Cadet wine (top_k:20, cosine:0.2)
INFO: Global query: 29 entites, 20 relations
INFO: Raw search results: 45 entities, 38 relations, 0 vector chunks
INFO: After truncation: 45 entities, 38 relations
INFO: Selecting 30 from 30 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 38 relations
INFO: Round-robin merged chunks: 30 -> 30 (deduplicated 0)
INFO: Final context: 45 entities, 38 relations, 8 chunks
INFO: Final chunks S+F/O: E3/1 E7/2 E2/3 E5/4 E2/5 E1/6 E2/7 E3/8
INFO:  == LLM cache == saving: hybrid:query:b44f27dde1fe36d8199343fa7ef15449

[hybrid] 5a7f46115542994857a766d9 | ok | 'I do not have enough information to answer.'

INFO:  == LLM cache == saving: hybrid:keywords:f7332c37b0e60a77df1d8444cf381859
INFO: Query nodes: François Beaucourt, 1740-1794 (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 35 relations
INFO: Query edges: Canada, François Beaucourt, place name history (top_k:20, cosine:0.2)
INFO: Global query: 33 entites, 20 relations
INFO: Raw search results: 46 entities, 50 relations, 0 vector chunks
INFO: After truncation: 46 entities, 50 relations
INFO: Selecting 37 from 37 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 50 relations
INFO: Round-robin merged chunks: 37 -> 37 (deduplicated 0)
INFO: Final context: 46 entities, 50 relations, 8 chunks
INFO: Final chunks S+F/O: E3/1 E5/2 E2/3 E2/4 E2/5 E1/6 E2/7 E4/8
INFO:  == LLM cache == saving: hybrid:query:341e4d92093e55dacf257d659e16faa5

[hybrid] 5ae4b8fc55429913cc2044e5 | ok | 'The place in Canada where François Beaucourt was mainly active, known as the Province of Quebec, acquired its present name as a result of the Royal Proclamation of 1763, which formally renamed Canada (part of New France) to the Province of Quebec.\n\n### References\n\n- [1] François Beaucourt\n- [2] Province of Quebec (1763–1791)\n- [3] Canada under British rule'

INFO:  == LLM cache == saving: hybrid:keywords:4eb3ac592b96f72e8e39cf07b4714715
INFO: Query nodes: Twelfth Night, title, name (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 41 relations
INFO: Query edges: comedy play, Shakespeare, Twelfth Night (top_k:20, cosine:0.2)
INFO: Global query: 25 entites, 20 relations
INFO: Raw search results: 36 entities, 45 relations, 0 vector chunks
INFO: After truncation: 36 entities, 45 relations
INFO: Selecting 11 from 11 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 45 relations
INFO: Round-robin merged chunks: 11 -> 11 (deduplicated 0)
INFO: Final context: 36 entities, 45 relations, 8 chunks
INFO: Final chunks S+F/O: E8/1 E3/2 E5/3 E5/4 E5/5 E4/6 E3/7 E4/8
INFO:  == LLM cache == saving: hybrid:query:6b41295d89985ec341733f77424a2386

[hybrid] 5ab3eb1955429969a97a81f6 | ok | 'The comedy play written by Shakespeare titled *Twelfth Night* is also known as *Twelfth Night, or What You Will*.\n\n### References\n\n- [1] Twelfth Night\n- [2] Twelfth Night (1996 film)'

INFO:  == LLM cache == saving: hybrid:keywords:9fd2b5a943e3644e2aa42eb0292f538c
INFO: Query nodes: Chick-Fil-A (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 35 relations
INFO: Query edges: reward, founder, Chick-Fil-A (top_k:20, cosine:0.2)
INFO: Global query: 29 entites, 20 relations
INFO: Raw search results: 41 entities, 45 relations, 0 vector chunks
INFO: After truncation: 41 entities, 45 relations
INFO: Selecting 25 from 25 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 45 relations
INFO: Round-robin merged chunks: 25 -> 25 (deduplicated 0)
INFO: Final context: 41 entities, 45 relations, 8 chunks
INFO: Final chunks S+F/O: E4/1 E6/2 E3/3 E4/4 E2/5 E1/6 E3/7 E3/8
INFO:  == LLM cache == saving: hybrid:query:1fe5adc2cd1644d8152307bbbe4b595d

[hybrid] 5ae2c509554299492dc91c68 | ok | "The founder of Chick-fil-A, S. Truett Cathy, received the President's Call to Service Award, which is the most prestigious award given for over 4,000 hours of extraordinary volunteer service. \n\n### References\n\n- [1] S. Truett Cathy\n- [2] President's Volunteer Service Award"

INFO:  == LLM cache == saving: hybrid:keywords:067f1c11ca0ccd183c3aae5f1bb96039
INFO: Query nodes: Coca-Cola, Red Flash (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 53 relations
INFO: Query edges: soft drink, Coca-Cola Company, Red Flash, year created (top_k:20, cosine:0.2)
INFO: Global query: 21 entites, 20 relations
INFO: Raw search results: 27 entities, 54 relations, 0 vector chunks
INFO: After truncation: 27 entities, 54 relations
INFO: Selecting 10 from 10 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 54 relations
INFO: Round-robin merged chunks: 10 -> 10 (deduplicated 0)
INFO: Final context: 27 entities, 54 relations, 8 chunks
INFO: Final chunks S+F/O: E4/1 E3/2 E5/3 E3/4 E3/5 E4/6 E5/7 E4/8
INFO:  == LLM cache == saving: hybrid:query:ba97130e94ea7fd75a644d2911c99714

[hybrid] 5a87560d5542994775f607d9 | ok | 'Red Flash was designed to compete against Big Red, which was created in 1937.\n\n### References\n- [1] Big Red (drink)'

INFO:  == LLM cache == saving: hybrid:keywords:90c931d12407c9d5a3a9face86a2a7ef
INFO: Query nodes: 1973 (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 29 relations
INFO: Query edges: American sports series, Channel 8, premiere (top_k:20, cosine:0.2)
INFO: Global query: 30 entites, 20 relations
INFO: Raw search results: 49 entities, 48 relations, 0 vector chunks
INFO: After truncation: 49 entities, 48 relations
INFO: Selecting 54 from 54 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 48 relations
INFO: Round-robin merged chunks: 54 -> 54 (deduplicated 0)
INFO: Final context: 49 entities, 48 relations, 8 chunks
INFO: Final chunks S+F/O: E3/1 E2/2 E4/3 E1/4 E1/5 E1/6 E1/7 E1/8
INFO:  == LLM cache == saving: hybrid:query:8f86682509ddb813b380529cbbb5a5a2

[hybrid] 5abee75f5542993fe9a41d8e | ok | 'Channel 8 has broadcast **HBO World Championship Boxing**, an American sports television series that premiered in January 1973.\n\n### References\n\n- [1] HBO World Championship Boxing\n- [2] Channel 8 (Thailand)'

INFO:  == LLM cache == saving: hybrid:keywords:3b062bc18ee98970b65e25c20ae53df3
INFO: Query nodes: John Roger Kirkpatrick Scott, east (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 46 relations
INFO: Query edges: U.S. House of Representatives, Commonwealth (top_k:20, cosine:0.2)
INFO: Global query: 25 entites, 20 relations
INFO: Raw search results: 42 entities, 60 relations, 0 vector chunks
INFO: After truncation: 42 entities, 60 relations
INFO: Selecting 55 from 55 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 60 relations
INFO: Round-robin merged chunks: 55 -> 55 (deduplicated 0)
INFO: Final context: 42 entities, 60 relations, 8 chunks
INFO: Final chunks S+F/O: E3/1 E3/2 E3/3 E3/4 E1/5 E3/6 E1/7 E2/8
INFO:  == LLM cache == saving: hybrid:query:ac30f20f0ddb8b327650420b2946951c

[hybrid] 5ae5559c55429960a22e02ba | ok | 'John Roger Kirkpatrick Scott was a member of the U.S. House of Representatives from Pennsylvania, which is a Commonwealth that borders New Jersey to the east.\n\n### References\n\n- [1] John Roger Kirkpatrick Scott\n- [2] Pennsylvania'

INFO:  == LLM cache == saving: hybrid:keywords:80e17d0c6413648acc8c9c530af09598
INFO: Query nodes: Jeanne Marie Beaumont, 2007-2010 (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 22 relations
INFO: Query edges: seminar, location (top_k:20, cosine:0.2)
INFO: Global query: 34 entites, 20 relations
INFO: Raw search results: 54 entities, 42 relations, 0 vector chunks
INFO: After truncation: 54 entities, 42 relations
INFO: Selecting 111 from 111 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 42 relations
INFO: Round-robin merged chunks: 111 -> 111 (deduplicated 0)
INFO: Final context: 54 entities, 42 relations, 8 chunks
INFO: Final chunks S+F/O: E15/1 E2/2 E1/3 E1/4 E1/5 E2/6 E2/7 E4/8
INFO:  == LLM cache == saving: hybrid:query:01385125192ebb492d7aa59af3160fbc

[hybrid] 5a7631cd5542994ccc91870c | ok | 'The seminar Jeanne Marie Beaumont directed from 2007 to 2010 is located at The Frost Place. \n\n### References\n\n- [1] Jeanne Marie Beaumont'

INFO:  == LLM cache == saving: hybrid:keywords:934b05e7969c275b361b6a1997faf312
WARNING: low_level_keywords is empty
INFO: Query edges: army division, Operation Blue Hearts, Korean War, city (top_k:20, cosine:0.2)
INFO: Global query: 25 entites, 20 relations
INFO: Raw search results: 25 entities, 20 relations, 0 vector chunks
INFO: After truncation: 25 entities, 20 relations
INFO: Selecting 15 from 15 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 20 relations
INFO: Round-robin merged chunks: 15 -> 15 (deduplicated 0)
INFO: Final context: 25 entities, 20 relations, 8 chunks
INFO: Final chunks S+F/O: E5/1 E8/2 E5/3 E3/4 E2/5 E2/6 E2/7 E1/8
INFO:  == LLM cache == saving: hybrid:query:caab02f1972a8ff7f641789e23f9ac23

[hybrid] 5a8c6ebd5542996e8ac88aa9 | ok | 'The First Cavalry Division, which conducted Operation Blue Hearts during the Korean War, is based at Fort Hood, Texas.\n\n### References\n\n- [1] 1st Cavalry Division (United States)'

INFO:  == LLM cache == saving: hybrid:keywords:58883b8ca9832f19d42fd87a1405f2b3
INFO: Query nodes: co-author, book (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 27 relations
INFO: Query edges: current position, Nathan Sharansky, The Case for Democracy (top_k:20, cosine:0.2)
INFO: Global query: 27 entites, 20 relations
INFO: Raw search results: 47 entities, 47 relations, 0 vector chunks
INFO: After truncation: 47 entities, 47 relations
INFO: Selecting 104 from 104 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 47 relations
INFO: Round-robin merged chunks: 104 -> 104 (deduplicated 0)
INFO: Final context: 47 entities, 47 relations, 8 chunks
INFO: Final chunks S+F/O: E6/1 E4/2 E5/3 E4/4 E4/5 E2/6 E3/7 E1/8
INFO:  == LLM cache == saving: hybrid:query:fc818b94f542133c4b332e793d58bbab

[hybrid] 5a84f5195542994c784dda9d | ok | "Nathan Sharansky's co-author of the book *The Case for Democracy* is Ron Dermer, who currently serves as the Israeli Ambassador to the United States. \n\n### References\n\n- [1] The Case for Democracy\n- [2] Ron Dermer"

INFO:  == LLM cache == saving: hybrid:keywords:ca187fcf9dc4b7586c382bef9d06584e
INFO: Query nodes: tour (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 27 relations
INFO: Query edges: American actress, singer, songwriter, I Stand tour (top_k:20, cosine:0.2)
INFO: Global query: 29 entites, 20 relations
INFO: Raw search results: 46 entities, 41 relations, 0 vector chunks
INFO: After truncation: 46 entities, 41 relations
INFO: Selecting 34 from 34 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 41 relations
INFO: Round-robin merged chunks: 34 -> 34 (deduplicated 0)
INFO: Final context: 46 entities, 41 relations, 8 chunks
INFO: Final chunks S+F/O: E2/1 E3/2 E7/3 E2/4 E3/5 E1/6 E1/7 E1/8
INFO:  == LLM cache == saving: hybrid:query:a24d45da892c99b19da30a793ac71116

[hybrid] 5ac2660d55429951e9e685a1 | ok | 'The I Stand tour was undertaken by American actress, singer, and songwriter Idina Menzel. \n\n### References\n\n- [1] I Stand tour'

INFO:  == LLM cache == saving: hybrid:keywords:11216485b06b6ccdb62311db528dc190
INFO: Query nodes: year, NBA Finals (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 71 relations
INFO: Query edges: NBA, Golden State, Cavaliers-Warriors rivalry, Most Valuable Player (top_k:20, cosine:0.2)
INFO: Global query: 18 entites, 20 relations
INFO: Raw search results: 29 entities, 75 relations, 0 vector chunks
INFO: After truncation: 29 entities, 75 relations
INFO: Selecting 18 from 18 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 75 relations
INFO: Round-robin merged chunks: 18 -> 18 (deduplicated 0)
INFO: Final context: 29 entities, 75 relations, 8 chunks
INFO: Final chunks S+F/O: E5/1 E6/2 E10/3 E8/4 E3/5 E5/6 E4/7 E7/8
INFO:  == LLM cache == saving: hybrid:query:b2fe8b754f2221b76d1bd5c0c815817c

[hybrid] 5a84574455429933447460e6 | ok | 'The Golden State player who was part of the Cavaliers-Warriors rivalry and was named NBA Finals Most Valuable Player is Andre Iguodala, who received this honor in 2015. \n\n### References\n- [1] 2015 NBA Finals\n- [2] Cavaliers–Warriors rivalry\n- [3] Andre Iguodala'

INFO:  == LLM cache == saving: hybrid:keywords:57e5b20bafd970f6c568cccfa6b48acf
INFO: Query nodes: The Fixer, song (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 37 relations
INFO: Query edges: music, album, production (top_k:20, cosine:0.2)
INFO: Global query: 36 entites, 20 relations
INFO: Raw search results: 55 entities, 56 relations, 0 vector chunks
INFO: After truncation: 55 entities, 56 relations
INFO: Selecting 48 from 48 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 56 relations
INFO: Round-robin merged chunks: 48 -> 48 (deduplicated 0)
INFO: Final context: 55 entities, 56 relations, 8 chunks
INFO: Final chunks S+F/O: E3/1 E2/2 E1/3 E3/4 E1/5 E1/6 E2/7 E1/8
INFO:  == LLM cache == saving: hybrid:query:51a91280038279d06b9e188bb12d03e6

[hybrid] 5ae394e05542990afbd1e18d | ok | '"The Fixer" is a song from the album "Backspacer," which was produced by Brendan O\'Brien.'

INFO:  == LLM cache == saving: hybrid:keywords:f1ce5e254adbaaf48095710b2bdfcc28
INFO: Query nodes: Evie (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 31 relations
INFO: Query edges: band formation, Evie, city (top_k:20, cosine:0.2)
INFO: Global query: 28 entites, 20 relations
INFO: Raw search results: 44 entities, 45 relations, 0 vector chunks
INFO: After truncation: 44 entities, 45 relations
INFO: Selecting 93 from 93 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 45 relations
INFO: Round-robin merged chunks: 93 -> 93 (deduplicated 0)
INFO: Final context: 44 entities, 45 relations, 8 chunks
INFO: Final chunks S+F/O: E7/1 E6/2 E2/3 E1/4 E2/5 E2/6 E3/7 E1/8
INFO:  == LLM cache == saving: hybrid:query:3184dff073919fa44bacf1193d1b6b7c

[hybrid] 5a84564c5542990548d0b288 | ok | 'The band associated with the song "Evie," The Easybeats, was formed in Sydney, Australia. \n\n### References\n- [1] The Easybeats'

INFO:  == LLM cache == saving: hybrid:keywords:4abd63519b3249ef66df60d83066aff1
INFO: Query nodes: skirmishes, raids, 1701, 1765, disputed border (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 54 relations
INFO: Query edges: American colonies, British proprietary colony, royal colony, northeast coast of North America (top_k:20, cosine:0.2)
INFO: Global query: 26 entites, 20 relations
INFO: Raw search results: 45 entities, 72 relations, 0 vector chunks
INFO: After truncation: 45 entities, 72 relations
INFO: Selecting 45 from 45 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 72 relations
INFO: Round-robin merged chunks: 45 -> 45 (deduplicated 0)
INFO: Final context: 45 entities, 72 relations, 8 chunks
INFO: Final chunks S+F/O: E3/1 E3/2 E2/3 E3/4 E2/5 E1/6 E7/7 E4/8
INFO:  == LLM cache == saving: hybrid:query:123349474cc5f782f4872fd1ae443f6d

[hybrid] 5a7a33205542996a35c1712f | ok | 'The Province of New York became a royal colony on the northeast coast of North America. \n\n### References\n\n- [1] New York – New Jersey Line War\n- [2] Province of New York'

INFO:  == LLM cache == saving: hybrid:keywords:006a95834b478d46cf2ff58834f18646
INFO: Query nodes: activist, The Irrational Atheist (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 27 relations
INFO: Query edges: activism, author, The Irrational Atheist (top_k:20, cosine:0.2)
INFO: Global query: 30 entites, 20 relations
INFO: Raw search results: 33 entities, 30 relations, 0 vector chunks
INFO: After truncation: 33 entities, 30 relations
INFO: Selecting 11 from 11 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 30 relations
INFO: Round-robin merged chunks: 11 -> 11 (deduplicated 0)
INFO: Final context: 33 entities, 30 relations, 8 chunks
INFO: Final chunks S+F/O: E6/1 E5/2 E3/3 E4/4 E4/5 E2/6 E1/7 E3/8
INFO:  == LLM cache == saving: hybrid:query:3fec1a525b729cdac22942701bbe7178

[hybrid] 5a849c1b5542997175ce1ef9 | ok | 'Vox Day, the author of *The Irrational Atheist*, is known for his controversial opinions in social and cultural debates. He is recognized as an alt-right activist, in addition to being a writer, editor, and video game designer.\n\n### References\n\n- [1] Vox Day'

INFO:  == LLM cache == saving: hybrid:keywords:ba43514ecc0289b794dbdb376b320a13
INFO: Query nodes: Ckm wz. 25, Hotchkiss (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 19 relations
INFO: Query edges: machine gun, World War I, French Army (top_k:20, cosine:0.2)
INFO: Global query: 26 entites, 20 relations
INFO: Raw search results: 35 entities, 30 relations, 0 vector chunks
INFO: After truncation: 35 entities, 30 relations
INFO: Selecting 34 from 34 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 30 relations
INFO: Round-robin merged chunks: 34 -> 34 (deduplicated 0)
INFO: Final context: 35 entities, 30 relations, 8 chunks
INFO: Final chunks S+F/O: E4/1 E8/2 E3/3 E7/4 E1/5 E2/6 E2/7 E5/8
INFO:  == LLM cache == saving: hybrid:query:3961fdfc9a75155f5c17b43add8d59ee

[hybrid] 5ab2c418554299545a2cfa67 | ok | 'Ckm wz. 25 Hotchkiss was a Polish derivative of the Hotchkiss M1914 machine gun, which became the standard machine gun of the French Army during World War I.\n\n### References\n\n- [1] Ckm wz. 25 Hotchkiss\n- [2] Hotchkiss M1914 machine gun'

INFO:  == LLM cache == saving: hybrid:keywords:403ec1c299bfc4c54338e307370721da
INFO: Query nodes: created, combated (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 35 relations
INFO: Query edges: territories, Kansas, Nebraska, Republican Party (top_k:20, cosine:0.2)
INFO: Global query: 24 entites, 20 relations
INFO: Raw search results: 44 entities, 55 relations, 0 vector chunks
INFO: After truncation: 44 entities, 55 relations
INFO: Selecting 106 from 106 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 55 relations
INFO: Round-robin merged chunks: 106 -> 106 (deduplicated 0)
INFO: Final context: 44 entities, 55 relations, 8 chunks
INFO: Final chunks S+F/O: E6/1 E3/2 E4/3 E3/4 E4/5 E1/6 E3/7 E1/8
INFO:  == LLM cache == saving: hybrid:query:28149753eb921b060a8f27a1242c1af9

[hybrid] 5ab5dc44554299494045f089 | ok | 'The territories of Kansas and Nebraska were created by the **Kansas–Nebraska Act** of 1854, which was also the legislative act that the Republican Party emerged to combat. This act dissolved the terms of the Missouri Compromise and allowed the status of slavery to be decided by popular sovereignty in those territories.\n\n### References\n\n- [1] Kansas–Nebraska Act\n- [2] History of the United States Republican Party'

INFO:  == LLM cache == saving: hybrid:keywords:40d6e2e1913d3255ca28ceb096c26b89
INFO: Query nodes: aircraft, photograph (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 25 relations
INFO: Query edges: American naval officer, United States Antarctic Service, Cox Point, specialization (top_k:20, cosine:0.2)
INFO: Global query: 24 entites, 20 relations
INFO: Raw search results: 42 entities, 43 relations, 0 vector chunks
INFO: After truncation: 42 entities, 43 relations
INFO: Selecting 26 from 26 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 43 relations
INFO: Round-robin merged chunks: 26 -> 26 (deduplicated 0)
INFO: Final context: 42 entities, 43 relations, 8 chunks
INFO: Final chunks S+F/O: E8/1 E7/2 E2/3 E3/4 E4/5 E4/6 E4/7 E6/8
INFO:  == LLM cache == saving: hybrid:query:cf89152081274b433b77c487fef6434f

[hybrid] 5a8e4a7355429917b4a5bd80 | ok | 'The American naval officer who led the aircraft of the United States Antarctic Service to photograph Cox Point was Admiral Richard E. Byrd, who specialized in feats of exploration, particularly in aviation and polar logistics.\n\n### References\n\n- [1] Richard E. Byrd'

INFO:  == LLM cache == saving: hybrid:keywords:d3e45b1c7bceb1158ac02e911ba9fbcb
INFO: Query nodes: Wrigley Park, social networks (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 39 relations
INFO: Query edges: Wrigley Park, social networks, commonalities (top_k:20, cosine:0.2)
INFO: Global query: 31 entites, 20 relations
INFO: Raw search results: 41 entities, 49 relations, 0 vector chunks
INFO: After truncation: 41 entities, 49 relations
INFO: Selecting 27 from 27 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 49 relations
INFO: Round-robin merged chunks: 27 -> 27 (deduplicated 0)
INFO: Final context: 41 entities, 49 relations, 8 chunks
INFO: Final chunks S+F/O: E3/1 E5/2 E2/3 E2/4 E8/5 E3/6 E5/7 E2/8
INFO:  == LLM cache == saving: hybrid:query:0c4617de3830b5e74aa080cda2ce7565

[hybrid] 5a772e465542994aec3b7209 | ok | 'Wrigley Park and social networks share a connection through the concept of community and interaction. Wrigley Park, also known as Fourth Ward, represents a neighborhood in Paterson, New Jersey, characterized by social interactions among its residents. Similarly, social networks are structured relationships that facilitate interactions among individuals, allowing them to form connections and communicate. \n\nFurthermore, neighborhoods like Wrigley Park can facilitate the formation of social networks through face-to-face interactions among their members, enhancing community ties and support.\n\n### References\n\n- [1] Wrigley Park\n- [2] Geosocial networking\n- [3] Opportunistic mobile social network'

INFO:  == LLM cache == saving: hybrid:keywords:de261b4fdd0ce4086ce0b3d185dc3b24
INFO: Query nodes: Icknield Walk First School (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 30 relations
INFO: Query edges: county, school location (top_k:20, cosine:0.2)
INFO: Global query: 36 entites, 20 relations
INFO: Raw search results: 53 entities, 47 relations, 0 vector chunks
INFO: After truncation: 53 entities, 47 relations
INFO: Selecting 125 from 125 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 47 relations
INFO: Round-robin merged chunks: 125 -> 125 (deduplicated 0)
INFO: Final context: 53 entities, 47 relations, 8 chunks
INFO: Final chunks S+F/O: E7/1 E2/2 E1/3 E6/4 E1/5 E1/6 E2/7 E1/8
INFO:  == LLM cache == saving: hybrid:query:51b6a627d0a303908d876494e050bf9e

[hybrid] 5ab844815542992aa3b8c8af | ok | 'Icknield Walk First School is located in Hertfordshire, England.\n\n### References\n\n- [1] Icknield Walk First School'

INFO:  == LLM cache == saving: hybrid:keywords:5e4eeceb0ea819aee17799f326e40c9f
INFO: Query nodes: Roger Groot, Class of 1975 (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 41 relations
INFO: Query edges: university, law professor, alumni (top_k:20, cosine:0.2)
INFO: Global query: 34 entites, 20 relations
INFO: Raw search results: 53 entities, 60 relations, 0 vector chunks
INFO: After truncation: 53 entities, 60 relations
INFO: Selecting 38 from 38 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 60 relations
INFO: Round-robin merged chunks: 38 -> 38 (deduplicated 0)
INFO: Final context: 53 entities, 60 relations, 8 chunks
INFO: Final chunks S+F/O: E4/1 E1/2 E3/3 E2/4 E3/5 E2/6 E4/7 E2/8
INFO:  == LLM cache == saving: hybrid:query:9aba4f04fea1d680975b448aed0afa71

[hybrid] 5adfa73b55429942ec259ad8 | ok | 'Roger Groot was the Class of 1975 Alumni Professor of Law at Washington and Lee University School of Law, which is located in Lexington, Virginia. The university is situated in Rockbridge County. \n\n### References\n- [1] Roger Groot'

INFO:  == LLM cache == saving: hybrid:keywords:7cda8a617b5491d88d638550f7ab5fd1
INFO: Query nodes: 1962, revival (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 23 relations
INFO: Query edges: original surname, actor, It's a De-Lovely, Anything Goes (top_k:20, cosine:0.2)
INFO: Global query: 19 entites, 20 relations
INFO: Raw search results: 38 entities, 42 relations, 0 vector chunks
INFO: After truncation: 38 entities, 42 relations
INFO: Selecting 30 from 30 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 42 relations
INFO: Round-robin merged chunks: 30 -> 30 (deduplicated 0)
INFO: Final context: 38 entities, 42 relations, 8 chunks
INFO: Final chunks S+F/O: E9/1 E7/2 E2/3 E3/4 E7/5 E5/6 E3/7 E2/8
INFO:  == LLM cache == saving: hybrid:query:109301901e82e2cd02aaf2691fa5d8e8

[hybrid] 5ae361d15542990afbd1e126 | ok | 'The original surname for the actor who sang "It\'s De-Lovely" in the 1962 revival of "Anything Goes" is Lipshitz. His stage name is Hal Linden. \n\n### References\n- [1] It\'s De-Lovely\n- [2] Anything Goes (soundtrack)\n- [3] Anything Goes (Cole Porter song)'

INFO:  == LLM cache == saving: hybrid:keywords:8ad0885a0263af77581565c35ec9189d
INFO: Query nodes: New Zealand, astronomer (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 59 relations
INFO: Query edges: American Astronomical Society, award, New Zealand astronomer (top_k:20, cosine:0.2)
INFO: Global query: 22 entites, 20 relations
INFO: Raw search results: 38 entities, 73 relations, 0 vector chunks
INFO: After truncation: 38 entities, 73 relations
INFO: Selecting 28 from 28 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 73 relations
INFO: Round-robin merged chunks: 28 -> 28 (deduplicated 0)
INFO: Final context: 38 entities, 73 relations, 8 chunks
INFO: Final chunks S+F/O: E6/1 E2/2 E6/3 E4/4 E3/5 E3/6 E3/7 E3/8
INFO:  == LLM cache == saving: hybrid:query:83dd8f03247f526ece938f2d4b6ad513

[hybrid] 5a72814f5542994cef4bc2eb | ok | 'The American Astronomical Society presents an award named after Beatrice Muriel Hill Tinsley, a British-born New Zealand astronomer and cosmologist known for her contributions to the understanding of galaxies. \n\n### References\n\n- [1] Beatrice Tinsley'

INFO:  == LLM cache == saving: hybrid:keywords:1ffaa2c2648323705b41bedcc17a49bd
INFO: Query nodes: Rex Gene Foods, Foodtown (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 43 relations
INFO: Query edges: Rex Gene Foods, Foodtown, location, state (top_k:20, cosine:0.2)
INFO: Global query: 23 entites, 20 relations
INFO: Raw search results: 30 entities, 47 relations, 0 vector chunks
INFO: After truncation: 30 entities, 47 relations
INFO: Selecting 75 from 119 entity-related chunks by vector similarity
INFO: Find 2 additional chunks in 2 relations (deduplicated 21)
INFO: Selecting 2 from 2 relation-related chunks by vector similarity
INFO: Round-robin merged chunks: 77 -> 77 (deduplicated 0)
INFO: Final context: 30 entities, 47 relations, 8 chunks
INFO: Final chunks S+F/O: E6/1 R1/1 E6/2 R2/2 E4/3 E2/4 E6/5 E2/6
INFO:  == LLM cache == saving: hybrid:query:94b87db476c8271d3dc6cdad00a25bf9

[hybrid] 5ae5b255554299546bf82f2c | ok | 'Both Rex Gene Foods and Foodtown were located in New Jersey. \n\n### References\n- [1] Rex Gene Foods\n- [2] Foodtown (United States)'

INFO:  == LLM cache == saving: hybrid:keywords:8fcc1a94258e539f94266528839d89d6
INFO: Query nodes: director, Midnight Cowboy (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 44 relations
INFO: Query edges: Academy Award, best director, film, Midnight Cowboy (top_k:20, cosine:0.2)
INFO: Global query: 21 entites, 20 relations
INFO: Raw search results: 26 entities, 44 relations, 0 vector chunks
INFO: After truncation: 26 entities, 44 relations
INFO: Selecting 24 from 24 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 44 relations
INFO: Round-robin merged chunks: 24 -> 24 (deduplicated 0)
INFO: Final context: 26 entities, 44 relations, 8 chunks
INFO: Final chunks S+F/O: E12/1 E3/2 E2/3 E2/4 E3/5 E5/6 E4/7 E1/8
INFO:  == LLM cache == saving: hybrid:query:160a9842e262639e7f480adb54eff7f3

[hybrid] 5a734a205542992359bc32e2 | ok | 'John Schlesinger won an Academy Award for Best Director for his work on the film "Midnight Cowboy." \n\n### References\n\n- [1] John Schlesinger\n- [2] Midnight Cowboy'

INFO:  == LLM cache == saving: hybrid:keywords:8a90137b9b62412910d06f906b97b3ad
INFO: Query nodes: Å (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 18 relations
INFO: Query edges: Upper German dialects, alphabets (top_k:20, cosine:0.2)
INFO: Global query: 30 entites, 20 relations
INFO: Raw search results: 45 entities, 34 relations, 0 vector chunks
INFO: After truncation: 45 entities, 34 relations
INFO: Selecting 15 from 15 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 34 relations
INFO: Round-robin merged chunks: 15 -> 15 (deduplicated 0)
INFO: Final context: 45 entities, 34 relations, 8 chunks
INFO: Final chunks S+F/O: E14/1 E2/2 E3/3 E6/4 E3/5 E2/6 E2/7 E3/8
INFO:  == LLM cache == saving: hybrid:query:c882b6d9d2c9d1d5fb0810cdbd9d6399

[hybrid] 5ae3f2895542995ad6573cc9 | ok | 'Å is part of the alphabet used in the *Alemannic dialect*, which is considered a group of the Upper German dialects. \n\n### References\n\n- [1] Å\n- [2] Alemannic German'

INFO:  == LLM cache == saving: hybrid:keywords:8944ae8c486611aec2e500a0ec7ac92d
INFO: Query nodes: Blue Ridge, music center, linear park (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 35 relations
INFO: Query edges: landform, Blue Ridge Music Center, American's longest linear park (top_k:20, cosine:0.2)
INFO: Global query: 26 entites, 20 relations
INFO: Raw search results: 32 entities, 39 relations, 0 vector chunks
INFO: After truncation: 32 entities, 39 relations
INFO: Selecting 22 from 22 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 39 relations
INFO: Round-robin merged chunks: 22 -> 22 (deduplicated 0)
INFO: Final context: 32 entities, 39 relations, 8 chunks
INFO: Final chunks S+F/O: E9/1 E6/2 E4/3 E2/4 E2/5 E1/6 E2/7 E3/8
INFO:  == LLM cache == saving: hybrid:query:a1293ad0c1ba6ea57c23f9ec10ac2dc2

[hybrid] 5ae397df5542994393b9e71f | ok | "The major landform that lent its name to both the Blue Ridge Music Center and America's longest linear park is the **Blue Ridge Mountains**. \n\n### References\n\n- [1] Blue Ridge Music Center\n- [2] Blue Ridge Parkway"

INFO:  == LLM cache == saving: hybrid:keywords:f0e6824e65b4b3cfe92b49e8f4271796
INFO: Query nodes: Jomar Brun (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 50 relations
INFO: Query edges: nuclear weapons, operation, country (top_k:20, cosine:0.2)
INFO: Global query: 20 entites, 20 relations
INFO: Raw search results: 40 entities, 70 relations, 0 vector chunks
INFO: After truncation: 40 entities, 70 relations
INFO: Selecting 100 from 105 entity-related chunks by vector similarity
INFO: Find 1 additional chunks in 1 relations (deduplicated 17)
INFO: Selecting 1 from 1 relation-related chunks by vector similarity
INFO: Round-robin merged chunks: 101 -> 101 (deduplicated 0)
INFO: Final context: 40 entities, 70 relations, 8 chunks
INFO: Final chunks S+F/O: E10/1 R1/1 E6/2 E2/3 E4/4 E4/5 E2/6 E4/7
INFO:  == LLM cache == saving: hybrid:query:a5933c8354d0a1ac3970420ae93c309d

[hybrid] 5ab480c45542990594ba9c36 | ok | 'Jomar Brun contributed to operations designed to prevent Germany from producing nuclear weapons during World War II, specifically through his involvement in the Norwegian heavy water sabotage efforts.\n\n### References\n\n- [1] Jomar Brun\n- [2] Norwegian heavy water sabotage'

INFO:  == LLM cache == saving: hybrid:keywords:54c8e1102aae3ea75d0692ee0c699e3c
INFO: Query nodes: Home Free (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 50 relations
INFO: Query edges: Marian Mercer, acting career, filmography (top_k:20, cosine:0.2)
INFO: Global query: 35 entites, 20 relations
INFO: Raw search results: 53 entities, 68 relations, 0 vector chunks
INFO: After truncation: 53 entities, 68 relations
INFO: Selecting 45 from 45 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 68 relations
INFO: Round-robin merged chunks: 45 -> 45 (deduplicated 0)
INFO: Final context: 53 entities, 68 relations, 8 chunks
INFO: Final chunks S+F/O: E2/1 E7/2 E2/3 E2/4 E1/5 E1/6 E1/7 E1/8
INFO:  == LLM cache == saving: hybrid:query:6ede836dbc0fa7de34b0cc18ee21407b

[hybrid] 5ae30d4b55429928c42395cc | ok | 'Marian Mercer, born Marian Ethel Mercer, was an American actress and singer. In addition to her acting in the sitcom *Home Free*, she was known for her work in various television shows and films throughout her career. She was born on November 26, 1935, and passed away on April 27, 2011.\n\n### References\n\n- [1] Marian Mercer\n- [2] Home Free (1993 TV series)'

INFO:  == LLM cache == saving: hybrid:keywords:21caa2e8e782881648724e05c6db60f5
INFO: Query nodes: name, series (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 21 relations
INFO: Query edges: Cleo Demetriou, So Awkward, role (top_k:20, cosine:0.2)
INFO: Global query: 27 entites, 20 relations
INFO: Raw search results: 47 entities, 41 relations, 0 vector chunks
INFO: After truncation: 47 entities, 41 relations
INFO: Selecting 24 from 24 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 41 relations
INFO: Round-robin merged chunks: 24 -> 24 (deduplicated 0)
INFO: Final context: 47 entities, 41 relations, 8 chunks
INFO: Final chunks S+F/O: E10/1 E4/2 E2/3 E3/4 E6/5 E4/6 E2/7 E1/8
INFO:  == LLM cache == saving: hybrid:query:43441dfe2b4ead153aa8270b16409604

[hybrid] 5ac3959855429939154137f0 | ok | 'Cleo Demetriou played the role of Lily Hampton in the series So Awkward.\n\n### References\n- [1] So Awkward\n- [2] Cleo Demetriou'

INFO:  == LLM cache == saving: hybrid:keywords:9021fef083a25eb2c062f2cd85ce16c1
INFO: Query nodes: English-born, South Australian, W. K. Simms, West End Brewery (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 23 relations
INFO: Query edges: brewer, brewery, amalgamation (top_k:20, cosine:0.2)
INFO: Global query: 25 entites, 20 relations
INFO: Raw search results: 34 entities, 33 relations, 0 vector chunks
INFO: After truncation: 34 entities, 33 relations
INFO: Selecting 17 from 17 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 33 relations
INFO: Round-robin merged chunks: 17 -> 17 (deduplicated 0)
INFO: Final context: 34 entities, 33 relations, 8 chunks
INFO: Final chunks S+F/O: E9/1 E4/2 E4/3 E2/4 E2/5 E7/6 E1/7 E6/8
INFO:  == LLM cache == saving: hybrid:query:44a970c56caac8c11b97b5b17d0880bf

[hybrid] 5adf0cbd5542993a75d263e0 | ok | "The English-born South Australian brewer whose brewery was amalgamated with W. K. Simms's West End Brewery is Sir Edwin Thomas Smith, who was born on April 6, 1830. \n\n### References\n\n- [1] South Australian Brewing Company\n- [2] Edwin Thomas Smith"

INFO:  == LLM cache == saving: hybrid:keywords:61e5b1eb66cf8af82d641c0143ff71e8
INFO: Query nodes: The Duke Steps Out, tenth, greatest female Hollywood stars, year (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 46 relations
INFO: Query edges: film, Hollywood stars, actress ranking (top_k:20, cosine:0.2)
INFO: Global query: 28 entites, 20 relations
INFO: Raw search results: 38 entities, 56 relations, 0 vector chunks
INFO: After truncation: 38 entities, 56 relations
INFO: Selecting 54 from 54 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 56 relations
INFO: Round-robin merged chunks: 54 -> 54 (deduplicated 0)
INFO: Final context: 38 entities, 56 relations, 8 chunks
INFO: Final chunks S+F/O: E4/1 E3/2 E1/3 E6/4 E4/5 E4/6 E4/7 E1/8
INFO:  == LLM cache == saving: hybrid:query:214837fbc54becb37defa63f45c0dfd0

[hybrid] 5a8ba59a554299240d9c2058 | ok | 'The actress Joan Crawford, who stars in "The Duke Steps Out," was ranked tenth on the American Film Institute\'s list of the greatest female stars of Classic Hollywood Cinema in the year 1999.\n\n### References\n\n- [1] The Duke Steps Out\n- [2] Joan Crawford'

INFO:  == LLM cache == saving: hybrid:keywords:91003ffc3374cbda7a6e47db6769fe90
INFO: Query nodes: IndyCar race driver, Formula 1 car, Peter McCool (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 33 relations
INFO: Query edges: IndyCar, Formula 1, Peter McCool, race driver (top_k:20, cosine:0.2)
INFO: Global query: 24 entites, 20 relations
INFO: Raw search results: 30 entities, 34 relations, 0 vector chunks
INFO: After truncation: 30 entities, 34 relations
INFO: Selecting 10 from 10 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 34 relations
INFO: Round-robin merged chunks: 10 -> 10 (deduplicated 0)
INFO: Final context: 30 entities, 34 relations, 8 chunks
INFO: Final chunks S+F/O: E4/1 E2/2 E1/3 E7/4 E5/5 E4/6 E6/7 E2/8
INFO:  == LLM cache == saving: hybrid:query:6beaab71c485a70d8bdbabdb8ad3b571

[hybrid] 5abd04bd5542992ac4f381a9 | ok | 'Takuma Sato drove the Super Aguri F1 SA07, a Formula One car designed by Peter McCool, during the 2007 Formula One season.\n\n### References\n\n- [1] Super Aguri SA07\n- [2] Takuma Sato'

INFO:  == LLM cache == saving: hybrid:keywords:42e74c73bb112e96dc03d5d58a559e80
INFO: Query nodes: Blair Cramer, Eve Donovan (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 37 relations
INFO: Query edges: actress, daytime drama series, One Life to Live, Days of Our Lives (top_k:20, cosine:0.2)
INFO: Global query: 21 entites, 20 relations
INFO: Raw search results: 32 entities, 45 relations, 0 vector chunks
INFO: After truncation: 32 entities, 45 relations
INFO: Selecting 17 from 17 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 45 relations
INFO: Round-robin merged chunks: 17 -> 17 (deduplicated 0)
INFO: Final context: 32 entities, 45 relations, 8 chunks
INFO: Final chunks S+F/O: E6/1 E6/2 E2/3 E3/4 E3/5 E4/6 E3/7 E4/8
INFO:  == LLM cache == saving: hybrid:query:6c8bbe7fa9ac2b523a1ad81eea971d68

[hybrid] 5a7e96f655429934daa2fc39 | ok | 'The actress who played Blair Cramer for almost 20 years on "One Life to Live" and is currently portraying Eve Donovan on "Days of Our Lives" is Kassie DePaiva. \n\n### References\n\n- [1] Kassie DePaiva\n- [2] Blair Cramer'

INFO:  == LLM cache == saving: hybrid:keywords:3e350d4107feff529872216d7ce8bd4e
INFO: Query nodes: 728, continental United States (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 120 relations
INFO: Query edges: anchor store, Stratford Square Mall, department store locations (top_k:20, cosine:0.2)
INFO: Global query: 23 entites, 20 relations
INFO: Raw search results: 43 entities, 140 relations, 0 vector chunks
INFO: After truncation: 43 entities, 140 relations
INFO: Selecting 107 from 108 entity-related chunks by vector similarity
INFO: Find 1 additional chunks in 1 relations (deduplicated 93)
INFO: Selecting 1 from 1 relation-related chunks by vector similarity
INFO: Round-robin merged chunks: 108 -> 108 (deduplicated 0)
INFO: Final context: 43 entities, 140 relations, 8 chunks
INFO: Final chunks S+F/O: E8/1 R1/1 E5/2 E5/3 E2/4 E3/5 E5/6 E1/7
INFO:  == LLM cache == saving: hybrid:query:b069048e79da32112837257b94459346

[hybrid] 5a746abf55429929fddd8417 | ok | "The anchor store in the Stratford Square Mall that has 728 department store locations in the continental United States is Macy's.\n\n### References\n\n- [1] Stratford Square Mall\n- [2] Macy's"

INFO:  == LLM cache == saving: hybrid:keywords:c5f619748272964ee9d72530c7400d7a
INFO: Query nodes: year (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 39 relations
INFO: Query edges: public research university, Brock Marion, college football, founded (top_k:20, cosine:0.2)
INFO: Global query: 29 entites, 20 relations
INFO: Raw search results: 49 entities, 59 relations, 0 vector chunks
INFO: After truncation: 49 entities, 59 relations
INFO: Selecting 122 from 124 entity-related chunks by vector similarity
INFO: Find 1 additional chunks in 1 relations (deduplicated 41)
INFO: Selecting 1 from 1 relation-related chunks by vector similarity
INFO: Round-robin merged chunks: 123 -> 123 (deduplicated 0)
INFO: Final context: 49 entities, 59 relations, 8 chunks
INFO: Final chunks S+F/O: E7/1 R1/1 E4/2 E3/3 E4/4 E4/5 E2/6 E2/7
INFO:  == LLM cache == saving: hybrid:query:ee60eb7cf43703b4e9578c08ae4e42b6

[hybrid] 5ae2ce505542996483e64a72 | ok | 'I do not have enough information to answer.'

INFO:  == LLM cache == saving: hybrid:keywords:1fe7a0339dc946cc2bbdb0a70633196f
INFO: Query nodes: Bruno Ganz, Solveig Dommartin (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 42 relations
INFO: Query edges: film, sequel, German romantic fantasy (top_k:20, cosine:0.2)
INFO: Global query: 33 entites, 20 relations
INFO: Raw search results: 49 entities, 58 relations, 0 vector chunks
INFO: After truncation: 49 entities, 58 relations
INFO: Selecting 37 from 37 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 58 relations
INFO: Round-robin merged chunks: 37 -> 37 (deduplicated 0)
INFO: Final context: 49 entities, 58 relations, 8 chunks
INFO: Final chunks S+F/O: E3/1 E7/2 E5/3 E2/4 E4/5 E4/6 E4/7 E4/8
INFO:  == LLM cache == saving: hybrid:query:ffc109dc0553d152c72284e0c2fa368f

[hybrid] 5ae72c1e554299572ea54754 | ok | 'The film that is a sequel to a German romantic fantasy film featuring Bruno Ganz and Solveig Dommartin is "Faraway, So Close!" This film is a sequel to "Wings of Desire," in which Bruno Ganz plays an angel who falls in love with Solveig Dommartin\'s character, a trapeze artist.\n\n### References\n\n- [1] Faraway, So Close!\n- [2] Wings of Desire'

INFO:  == LLM cache == saving: hybrid:keywords:d48345c336626c33f2905615affd9551
INFO: Query nodes: The Kenyon Review, writer, year (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 36 relations
INFO: Query edges: Pulitzer Prize, literary awards (top_k:20, cosine:0.2)
INFO: Global query: 33 entites, 20 relations
INFO: Raw search results: 53 entities, 56 relations, 0 vector chunks
INFO: After truncation: 53 entities, 56 relations
INFO: Selecting 45 from 45 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 56 relations
INFO: Round-robin merged chunks: 45 -> 45 (deduplicated 0)
INFO: Final context: 53 entities, 56 relations, 8 chunks
INFO: Final chunks S+F/O: E18/1 E2/2 E1/3 E1/4 E1/5 E2/6 E3/7 E2/8
INFO:  == LLM cache == saving: hybrid:query:dbba0f8a7c4520d923cc2a4513931ac7

[hybrid] 5a8ba0855542995d1e6f1427 | ok | 'The Kenyon Review had works published by Robert Penn Warren, who won the Pulitzer Prize for the Novel in 1947 and the Pulitzer Prize for Poetry in 1958 and 1979.\n\n### References\n\n- [1] Robert Penn Warren'

INFO:  == LLM cache == saving: hybrid:keywords:8064e85c34bbc8b57311c14a680a05ba
INFO: Query nodes: Greensky Bluegrass, album (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 25 relations
INFO: Query edges: Greensky Bluegrass, band home, first album location (top_k:20, cosine:0.2)
INFO: Global query: 28 entites, 20 relations
INFO: Raw search results: 32 entities, 30 relations, 0 vector chunks
INFO: After truncation: 32 entities, 30 relations
INFO: Selecting 44 from 44 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 30 relations
INFO: Round-robin merged chunks: 44 -> 44 (deduplicated 0)
INFO: Final context: 32 entities, 30 relations, 8 chunks
INFO: Final chunks S+F/O: E10/1 E3/2 E4/3 E3/4 E2/5 E1/6 E2/7 E3/8
INFO:  == LLM cache == saving: hybrid:query:5844e8bc38915f47c223166ab92b64ea

[hybrid] 5a778ce55542995d831811c0 | ok | 'Greensky Bluegrass was founded in Kalamazoo, Michigan, which also serves as their home base. They recorded their first album, "Live At Bell\'s," at Bell\'s Brewery, located in Kalamazoo. \n\n### References\n- [1] Greensky Bluegrass\n- [2] Live At Bell\'s'

INFO:  == LLM cache == saving: hybrid:keywords:29d282de6dd5ad5e1f3a538701d93507
INFO: Query nodes: Eric Goldberg (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 40 relations
INFO: Query edges: MadMaze, game type (top_k:20, cosine:0.2)
INFO: Global query: 32 entites, 20 relations
INFO: Raw search results: 51 entities, 59 relations, 0 vector chunks
INFO: After truncation: 51 entities, 59 relations
INFO: Selecting 34 from 34 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 59 relations
INFO: Round-robin merged chunks: 34 -> 34 (deduplicated 0)
INFO: Final context: 51 entities, 59 relations, 8 chunks
INFO: Final chunks S+F/O: E5/1 E1/2 E3/3 E3/4 E3/5 E4/6 E1/7 E1/8
INFO:  == LLM cache == saving: hybrid:query:cb2a1be9c056826adec78d0e886e9069

[hybrid] 5ab3f6935542992339550019 | ok | 'MadMaze was developed by Eric Goldberg as an online video game. \n\n### References\n\n- [1] MadMaze\n- [2] Eric Goldberg (game designer)'

INFO:  == LLM cache == saving: hybrid:keywords:10245267390c69e24b2f847dc762d7e2
INFO: Query nodes: company, Washington (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 30 relations
INFO: Query edges: Chicagoland Sports Hall of Fame, founded, Washington town, state capital (top_k:20, cosine:0.2)
INFO: Global query: 24 entites, 20 relations
INFO: Raw search results: 44 entities, 50 relations, 0 vector chunks
INFO: After truncation: 44 entities, 50 relations
INFO: Selecting 34 from 34 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 50 relations
INFO: Round-robin merged chunks: 34 -> 34 (deduplicated 0)
INFO: Final context: 44 entities, 50 relations, 8 chunks
INFO: Final chunks S+F/O: E8/1 E4/2 E3/3 E2/4 E1/5 E4/6 E2/7 E4/8
INFO:  == LLM cache == saving: hybrid:query:bf3853691f0b179d0994b07d89f85327

[hybrid] 5a8a495055429930ff3c0d6a | ok | 'The Chicagoland Sports Hall of Fame was founded by the Olympia Brewing Company, which was located in Tumwater, Washington, near the state capital, Olympia.\n\n### References\n\n- [1] Olympia Brewing Company'

INFO:  == LLM cache == saving: hybrid:keywords:043d20bf53bd32fb34028099fcec2178
WARNING: low_level_keywords is empty
INFO: Query edges: Republican of Indonesia, opponent, Nugroho Notosusanto, Student Army (top_k:20, cosine:0.2)
INFO: Global query: 31 entites, 20 relations
INFO: Raw search results: 31 entities, 20 relations, 0 vector chunks
INFO: After truncation: 31 entities, 20 relations
INFO: Selecting 77 from 87 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 20 relations
INFO: Round-robin merged chunks: 77 -> 77 (deduplicated 0)
INFO: Final context: 31 entities, 20 relations, 8 chunks
INFO: Final chunks S+F/O: E5/1 E3/2 E3/3 E6/4 E2/5 E2/6 E3/7 E1/8
INFO:  == LLM cache == saving: hybrid:query:e341fe05270ab943822224d640ab60c3

[hybrid] 5a7b22f8554299042af8f6ff | ok | 'I do not have enough information to answer.'

INFO:  == LLM cache == saving: hybrid:keywords:a1bd9d7a0d82c65636c021eea37b7535
INFO: Query nodes: Arthur Newman, Colin Firth (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 39 relations
INFO: Query edges: film, debut, play (top_k:20, cosine:0.2)
INFO: Global query: 39 entites, 20 relations
INFO: Raw search results: 58 entities, 58 relations, 0 vector chunks
INFO: After truncation: 58 entities, 58 relations
INFO: Selecting 83 from 83 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 58 relations
INFO: Round-robin merged chunks: 83 -> 83 (deduplicated 0)
INFO: Final context: 58 entities, 58 relations, 8 chunks
INFO: Final chunks S+F/O: E6/1 E1/2 E1/3 E1/4 E9/5 E2/6 E1/7 E1/8
INFO:  == LLM cache == saving: hybrid:query:6e30e95743b180b69b8a2176610cf75e

[hybrid] 5a90b6985542990a984936c2 | ok | 'The film "Arthur Newman" stars Colin Firth and Emily Blunt, who made her professional debut in the play "The Royal Family." \n\n### References\n\n- [1] Arthur Newman (film)\n- [2] Emily Blunt'

INFO:  == LLM cache == saving: hybrid:keywords:b965c9425ef8be2d4800f2514960e983
INFO: Query nodes: 2015, Ruby Bentall, Verity (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 24 relations
INFO: Query edges: novels, BBC TV series, adaptation (top_k:20, cosine:0.2)
INFO: Global query: 33 entites, 20 relations
INFO: Raw search results: 53 entities, 44 relations, 0 vector chunks
INFO: After truncation: 53 entities, 44 relations
INFO: Selecting 59 from 59 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 44 relations
INFO: Round-robin merged chunks: 59 -> 59 (deduplicated 0)
INFO: Final context: 53 entities, 44 relations, 8 chunks
INFO: Final chunks S+F/O: E3/1 E2/2 E5/3 E2/4 E2/5 E3/6 E1/7 E4/8
INFO:  == LLM cache == saving: hybrid:query:5be3e4ddb69b7de20e4c66c7c3bbc26e

[hybrid] 5adfa570554299025d62a31c | ok | 'The series of novels adapted for the 2015 BBC TV series in which Ruby Bentall plays the character Verity is called "Poldark". There are a total of **six** novels in the series written by Winston Graham.\n\n### References\n- [1] Ruby Bentall'

INFO:  == LLM cache == saving: hybrid:keywords:72e6cf294d81f12cb8116b61eab3e200
INFO: Query nodes: Tomorrow's World, Lost and Safe (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 39 relations
INFO: Query edges: musical duo, sampling, album (top_k:20, cosine:0.2)
INFO: Global query: 34 entites, 20 relations
INFO: Raw search results: 54 entities, 59 relations, 0 vector chunks
INFO: After truncation: 54 entities, 59 relations
INFO: Selecting 39 from 39 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 59 relations
INFO: Round-robin merged chunks: 39 -> 39 (deduplicated 0)
INFO: Final context: 54 entities, 59 relations, 8 chunks
INFO: Final chunks S+F/O: E4/1 E3/2 E2/3 E2/4 E2/5 E2/6 E1/7 E1/8
INFO:  == LLM cache == saving: hybrid:query:f06cae0d92020a3e670f9cc36cbedee0

[hybrid] 5a886364554299206df2b24b | ok | 'The musical duo that used samples from the first presenter of "Tomorrow\'s World," Raymond Baxter, in their album "Lost and Safe" is The Books. \n\n### References\n\n- [1] Lost and Safe\n- [2] De La Soul'

INFO:  == LLM cache == saving: hybrid:keywords:aedf97b29d1c8c0bd1785a98b4f2d6ad
INFO: Query nodes: Straight to Hell, organization (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 24 relations
INFO: Query edges: country music, Parental Advisory label (top_k:20, cosine:0.2)
INFO: Global query: 30 entites, 20 relations
INFO: Raw search results: 48 entities, 43 relations, 0 vector chunks
INFO: After truncation: 48 entities, 43 relations
INFO: Selecting 58 from 58 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 43 relations
INFO: Round-robin merged chunks: 58 -> 58 (deduplicated 0)
INFO: Final context: 48 entities, 43 relations, 8 chunks
INFO: Final chunks S+F/O: E3/1 E7/2 E3/3 E3/4 E2/5 E3/6 E3/7 E1/8
INFO:  == LLM cache == saving: hybrid:query:b3305b99e01a3dbe61b1dd5f0c61735b

[hybrid] 5a7d32af55429907fabef0ca | ok | 'Straight to Hell was the first ever country music release to merit the Parental Advisory label from the Recording Industry Association of America (RIAA). \n\n### References\n- [1] Straight to Hell (album)\n- [2] Parental Advisory'

INFO:  == LLM cache == saving: hybrid:keywords:582db31af1955cc8e74ac94dc2147e2e
INFO: Query nodes: Vadim Bereinskii (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 51 relations
INFO: Query edges: disease, Wolf Prize, Nobel laureate (top_k:20, cosine:0.2)
INFO: Global query: 25 entites, 20 relations
INFO: Raw search results: 45 entities, 71 relations, 0 vector chunks
INFO: After truncation: 45 entities, 71 relations
INFO: Selecting 24 from 24 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 71 relations
INFO: Round-robin merged chunks: 24 -> 24 (deduplicated 0)
INFO: Final context: 45 entities, 71 relations, 8 chunks
INFO: Final chunks S+F/O: E5/1 E6/2 E5/3 E3/4 E7/5 E2/6 E3/7 E3/8
INFO:  == LLM cache == saving: hybrid:query:2cc6d451a26182afcddf7f625c45d019

[hybrid] 5a84d2775542994c784dda5f | ok | "David J. Thouless, the Wolf Prize winner and a Nobel laureate inspired by Vadim L'vovich Berezinskii's work, was reported to be suffering from dementia in 2016."

INFO:  == LLM cache == saving: hybrid:keywords:37314f4aab0601837b5c8f18d9ca7188
INFO: Query nodes: September 2005 (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 19 relations
INFO: Query edges: theme park, competitor, Ocean Park Hong Kong (top_k:20, cosine:0.2)
INFO: Global query: 22 entites, 20 relations
INFO: Raw search results: 42 entities, 39 relations, 0 vector chunks
INFO: After truncation: 42 entities, 39 relations
INFO: Selecting 39 from 39 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 39 relations
INFO: Round-robin merged chunks: 39 -> 39 (deduplicated 0)
INFO: Final context: 42 entities, 39 relations, 8 chunks
INFO: Final chunks S+F/O: E7/1 E6/2 E3/3 E6/4 E5/5 E4/6 E3/7 E1/8
INFO:  == LLM cache == saving: hybrid:query:97054ffcec25ad288400ae21b844d4c4

[hybrid] 5a8f2ba155429918e830d1b9 | ok | 'The theme park that was seen as a competitor for Ocean Park Hong Kong and opened in September 2005 is **Hong Kong Disneyland**, which officially opened to visitors on 12 September 2005. \n\n### References\n\n- [1] Hong Kong Disneyland\n- [2] Ocean Park Hong Kong'

INFO:  == LLM cache == saving: hybrid:keywords:5b07e30110eb89fc5e3258e751f60ae4
INFO: Query nodes: Niels Henrik David Bohr, Nordic Institute for Theoretical Physics (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 32 relations
INFO: Query edges: award, Danish physicist, Nordic Institute for Theoretical Physics (top_k:20, cosine:0.2)
INFO: Global query: 23 entites, 20 relations
INFO: Raw search results: 30 entities, 39 relations, 0 vector chunks
INFO: After truncation: 30 entities, 39 relations
INFO: Selecting 20 from 20 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 39 relations
INFO: Round-robin merged chunks: 20 -> 20 (deduplicated 0)
INFO: Final context: 30 entities, 39 relations, 8 chunks
INFO: Final chunks S+F/O: E3/1 E5/2 E7/3 E8/4 E4/5 E3/6 E1/7 E1/8
INFO:  == LLM cache == saving: hybrid:query:1da01f88ea59765ae8c59640a976eff4

[hybrid] 5adbfb3f55429947ff17388a | ok | 'Niels Henrik David Bohr won the Nobel Prize in Physics in 1922 for his contributions to atomic structure and quantum theory. He was also a co-founder of the Nordic Institute for Theoretical Physics. \n\n### References\n- [1] Niels Bohr\n- [2] Nordic Institute for Theoretical Physics\n- [3] Niels Bohr International Gold Medal'

INFO:  == LLM cache == saving: hybrid:keywords:26c04d7e6411932cd8a8f26452dfe8de
INFO: Query nodes: San Francisco, 2003 (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 38 relations
INFO: Query edges: American politician, mayoral election (top_k:20, cosine:0.2)
INFO: Global query: 27 entites, 20 relations
INFO: Raw search results: 36 entities, 44 relations, 0 vector chunks
INFO: After truncation: 36 entities, 44 relations
INFO: Selecting 34 from 34 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 44 relations
INFO: Round-robin merged chunks: 34 -> 34 (deduplicated 0)
INFO: Final context: 36 entities, 44 relations, 8 chunks
INFO: Final chunks S+F/O: E5/1 E4/2 E4/3 E3/4 E4/5 E5/6 E3/7 E4/8
INFO:  == LLM cache == saving: hybrid:query:4cf83361f73196f6df43581bd78bf9dc

[hybrid] 5ae034bd55429925eb1afc2a | ok | 'The American politician and lawyer who contested in the San Francisco mayoral election in 2003 was Matthew Edward Gonzalez. He ran as a member of the Green Party and lost a close race to Gavin Newsom. \n\n### References\n\n- [1] Matt Gonzalez'

INFO:  == LLM cache == saving: hybrid:keywords:e40e5f89198ce7aec623c64e8a646266
INFO: Query nodes: Jessica Ashley, Leave (Get Out), singer (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 36 relations
INFO: Query edges: songwriting, singer, music (top_k:20, cosine:0.2)
INFO: Global query: 27 entites, 20 relations
INFO: Raw search results: 42 entities, 53 relations, 0 vector chunks
INFO: After truncation: 42 entities, 53 relations
INFO: Selecting 23 from 23 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 53 relations
INFO: Round-robin merged chunks: 23 -> 23 (deduplicated 0)
INFO: Final context: 42 entities, 53 relations, 8 chunks
INFO: Final chunks S+F/O: E10/1 E2/2 E4/3 E2/4 E1/5 E2/6 E1/7 E1/8
INFO:  == LLM cache == saving: hybrid:query:6b52089fd018465fb9b34acc56dd62db

[hybrid] 5a88ba465542993e715ac089 | ok | 'Jessica Ashley has written songs for JoJo, who is known for her song "Leave (Get Out)." \n\n### References\n\n- [1] Jessica Ashley\n- [2] JoJo (singer)'

INFO:  == LLM cache == saving: hybrid:keywords:039cb26712af9b446da125335980e333
INFO: Query nodes: Ogwini Comprehensive Technical High School, Durban (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 37 relations
INFO: Query edges: country, commonality, schools (top_k:20, cosine:0.2)
INFO: Global query: 35 entites, 20 relations
INFO: Raw search results: 53 entities, 54 relations, 0 vector chunks
INFO: After truncation: 53 entities, 54 relations
INFO: Selecting 49 from 49 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 54 relations
INFO: Round-robin merged chunks: 49 -> 49 (deduplicated 0)
INFO: Final context: 53 entities, 54 relations, 8 chunks
INFO: Final chunks S+F/O: E4/1 E4/2 E7/3 E1/4 E3/5 E2/6 E2/7 E3/8
INFO:  == LLM cache == saving: hybrid:query:5e7588e9322d850902b1842907134e51

[hybrid] 5abda6e955429965af743d9b | ok | 'Both Ogwini Comprehensive Technical High School and Durban are located in South Africa. \n\n### References\n- [1] Ogwini Comprehensive Technical High School\n- [2] Durban'

INFO:  == LLM cache == saving: hybrid:keywords:a368067e45546ed0e0c7a0a34ad52a58
INFO: Query nodes: Carl Wieland (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 35 relations
INFO: Query edges: organization beliefs, young earth view (top_k:20, cosine:0.2)
INFO: Global query: 24 entites, 20 relations
INFO: Raw search results: 44 entities, 55 relations, 0 vector chunks
INFO: After truncation: 44 entities, 55 relations
INFO: Selecting 26 from 26 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 55 relations
INFO: Round-robin merged chunks: 26 -> 26 (deduplicated 0)
INFO: Final context: 44 entities, 55 relations, 8 chunks
INFO: Final chunks S+F/O: E2/1 E7/2 E6/3 E4/4 E3/5 E1/6 E1/7 E1/8
INFO:  == LLM cache == saving: hybrid:query:edccc43757483be6c121eb968b443b89

[hybrid] 5ac19eb35542994ab5c67da3 | ok | 'The organization associated with Carl Wieland, which is Answers in Genesis, believes that views other than young Earth creationism compromise biblical inerrancy. They advocate for a literal interpretation of the Book of Genesis and reject scientific investigations that do not conform to their beliefs. \n\n### References\n\n- [1] Young Earth creationism\n- [2] Answers in Genesis'

INFO:  == LLM cache == saving: hybrid:keywords:cbaa187934edb55ad194d13e6a4075a6
INFO: Query nodes: committing (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 31 relations
INFO: Query edges: murderer, Old Smokey, The Crime of the Century (top_k:20, cosine:0.2)
INFO: Global query: 26 entites, 20 relations
INFO: Raw search results: 46 entities, 51 relations, 0 vector chunks
INFO: After truncation: 46 entities, 51 relations
INFO: Selecting 59 from 59 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 51 relations
INFO: Round-robin merged chunks: 59 -> 59 (deduplicated 0)
INFO: Final context: 46 entities, 51 relations, 8 chunks
INFO: Final chunks S+F/O: E5/1 E4/2 E2/3 E4/4 E4/5 E3/6 E4/7 E1/8
INFO:  == LLM cache == saving: hybrid:query:254a6c526fc773b61c748ee2a856bd75

[hybrid] 5a74d7685542996c70cfae0a | ok | 'The murderer sent to "Old Smokey" for allegedly committing "The Crime of the Century" was Bruno Richard Hauptmann. He was convicted of the abduction and murder of Charles Augustus Lindbergh, Jr., the son of famous aviators Charles Lindbergh and Anne Morrow Lindbergh. Hauptmann was executed in the electric chair at the New Jersey State Prison in 1936. \n\n### References\n- [1] Old Smokey\n- [2] Richard Hauptmann'

INFO:  == LLM cache == saving: hybrid:keywords:05f7224d190a4f8137422b75cdeb124b
INFO: Query nodes: multi-use, professional football club (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 51 relations
INFO: Query edges: sports facility, recreation, Dynamo Kyiv (top_k:20, cosine:0.2)
INFO: Global query: 20 entites, 20 relations
INFO: Raw search results: 38 entities, 65 relations, 0 vector chunks
INFO: After truncation: 38 entities, 65 relations
INFO: Selecting 26 from 26 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 65 relations
INFO: Round-robin merged chunks: 26 -> 26 (deduplicated 0)
INFO: Final context: 38 entities, 65 relations, 8 chunks
INFO: Final chunks S+F/O: E7/1 E3/2 E3/3 E5/4 E5/5 E1/6 E2/7 E5/8
INFO:  == LLM cache == saving: hybrid:query:82dad9084abef6bed42d54189eb0c8b9

[hybrid] 5a737dc455429908901be2c9 | ok | 'The multi-use sports and recreation facility that houses professional football club Dynamo Kyiv is called the **Olimpiyskiy National Sports Complex**.\n\n### References\n- [1] Olimpiyskiy National Sports Complex\n- [2] FC Dynamo Kyiv'

INFO:  == LLM cache == saving: hybrid:keywords:f4272c45cebe73a7334727c095717499
INFO: Query nodes: Jeep, variant, years (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 55 relations
INFO: Query edges: Jeep Cherokee, automobile history (top_k:20, cosine:0.2)
INFO: Global query: 24 entites, 20 relations
INFO: Raw search results: 28 entities, 55 relations, 0 vector chunks
INFO: After truncation: 28 entities, 55 relations
INFO: Selecting 13 from 13 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 55 relations
INFO: Round-robin merged chunks: 13 -> 13 (deduplicated 0)
INFO: Final context: 28 entities, 55 relations, 8 chunks
INFO: Final chunks S+F/O: E6/1 E5/2 E3/3 E6/4 E3/5 E4/6 E4/7 E3/8
INFO:  == LLM cache == saving: hybrid:query:b900802fed7630d36c966ea2099cde5c

[hybrid] 5a88f9555542995153361214 | ok | 'The Jeep Cherokee was originally sold as a variant of the Jeep Wagoneer, which was produced from 1963 to 1991. The Cherokee itself has been in continuous use since 1974. \n\n### References\n- [1] Jeep Cherokee\n- [2] Jeep Wagoneer\n- [3] Jeep Cherokee (SJ)'

INFO:  == LLM cache == saving: hybrid:keywords:6b07b492861ba1defd93089a1ba26847
INFO: Query nodes: Art Loeb trail (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 40 relations
INFO: Query edges: National forests, administration, Art Loeb trail (top_k:20, cosine:0.2)
INFO: Global query: 26 entites, 20 relations
INFO: Raw search results: 38 entities, 50 relations, 0 vector chunks
INFO: After truncation: 38 entities, 50 relations
INFO: Selecting 15 from 15 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 50 relations
INFO: Round-robin merged chunks: 15 -> 15 (deduplicated 0)
INFO: Final context: 38 entities, 50 relations, 8 chunks
INFO: Final chunks S+F/O: E9/1 E2/2 E4/3 E5/4 E3/5 E4/6 E2/7 E1/8
INFO:  == LLM cache == saving: hybrid:query:82e6e812b63b205342e4509fac42b4a5

[hybrid] 5ac3a2f35542993915413856 | ok | 'The three other National Forests administered along with Pisgah National Forest are Croatan National Forest, Nantahala National Forest, and Uwharrie National Forest.\n\n### References\n\n- [1] Pisgah National Forest\n- [2] Art Loeb Trail'

INFO:  == LLM cache == saving: hybrid:keywords:40c145cfdc83d6b5087148c2f71702c0
WARNING: low_level_keywords is empty
INFO: Query edges: portable media player, distribution, HP (top_k:20, cosine:0.2)
INFO: Global query: 27 entites, 20 relations
INFO: Raw search results: 27 entities, 20 relations, 0 vector chunks
INFO: After truncation: 27 entities, 20 relations
INFO: Selecting 11 from 11 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 20 relations
INFO: Round-robin merged chunks: 11 -> 11 (deduplicated 0)
INFO: Final context: 27 entities, 20 relations, 8 chunks
INFO: Final chunks S+F/O: E5/1 E4/2 E3/3 E2/4 E4/5 E5/6 E1/7 E3/8
INFO:  == LLM cache == saving: hybrid:query:5a3b1eb2e43dd75e3674bf3450c07957

[hybrid] 5a74e6e855429974ef308c8e | ok | 'The portable media player distributed through HP is the **Apple iPod+HP**, which is an Apple iPod 4G featuring an HP logo on the back. \n\n### References\n\n- [3] IPod+HP'

INFO:  == LLM cache == saving: hybrid:keywords:3f3eacd93990d29b9481c5291b932352
INFO: Query nodes: Friday Night Lights, The River Why (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 40 relations
INFO: Query edges: actress, filmography (top_k:20, cosine:0.2)
INFO: Global query: 37 entites, 20 relations
INFO: Raw search results: 57 entities, 60 relations, 0 vector chunks
INFO: After truncation: 57 entities, 60 relations
INFO: Selecting 47 from 47 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 60 relations
INFO: Round-robin merged chunks: 47 -> 47 (deduplicated 0)
INFO: Final context: 57 entities, 60 relations, 8 chunks
INFO: Final chunks S+F/O: E6/1 E4/2 E1/3 E4/4 E2/5 E5/6 E2/7 E2/8
INFO:  == LLM cache == saving: hybrid:query:0ea811795c5ae3051057ccdc09d25a84

[hybrid] 5ac027005542996f0d89cb3d | ok | 'The actress who made her film debut in *Friday Night Lights* and also starred in *The River Why* is Amber Heard. \n\n### References\n\n- [1] Amber Heard\n- [2] The River Why (film)'

INFO:  == LLM cache == saving: hybrid:keywords:6be7acb096cbe8bcc8081cdd8e38a08d
WARNING: low_level_keywords is empty
INFO: Query edges: descendant, Red Setter, originate (top_k:20, cosine:0.2)
INFO: Global query: 21 entites, 20 relations
INFO: Raw search results: 21 entities, 20 relations, 0 vector chunks
INFO: After truncation: 21 entities, 20 relations
INFO: Selecting 14 from 14 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 20 relations
INFO: Round-robin merged chunks: 14 -> 14 (deduplicated 0)
INFO: Final context: 21 entities, 20 relations, 8 chunks
INFO: Final chunks S+F/O: E4/1 E3/2 E6/3 E2/4 E7/5 E2/6 E1/7 E2/8
INFO:  == LLM cache == saving: hybrid:query:446ab69f643c314091cacb6affcd8c06

[hybrid] 5abde4595542991f66106095 | ok | 'The descendant of the Red Setter, known as the Scotch Collie, originates from the highland regions of Scotland. This breed is believed to have descended from various ancient herding dogs. \n\n### References\n\n- [1] Scotch Collie'

INFO:  == LLM cache == saving: hybrid:keywords:0906c78d40028e57614e49de41603b02
INFO: Query nodes: Angels in the Outfield, Predator 2, Places in the Heart (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 47 relations
INFO: Query edges: actor, film appearances (top_k:20, cosine:0.2)
INFO: Global query: 37 entites, 20 relations
INFO: Raw search results: 54 entities, 65 relations, 0 vector chunks
INFO: After truncation: 54 entities, 65 relations
INFO: Selecting 47 from 47 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 65 relations
INFO: Round-robin merged chunks: 47 -> 47 (deduplicated 0)
INFO: Final context: 54 entities, 65 relations, 8 chunks
INFO: Final chunks S+F/O: E4/1 E9/2 E1/3 E4/4 E2/5 E1/6 E2/7 E3/8
INFO:  == LLM cache == saving: hybrid:query:dc07129ec3758d23a04ff3c58ec079eb

[hybrid] 5ade1f0555429975fa854e74 | ok | 'Danny Glover starred in "Angels in the Outfield," "Predator 2," and "Places in the Heart." \n\n### References\n\n- [1] Danny Glover\n- [2] Places in the Heart\n- [3] Predator 2 (soundtrack)'

INFO:  == LLM cache == saving: hybrid:keywords:89a9671a5cd0298ca3de9d9c731d2cf1
INFO: Query nodes: northern United States, southern Canada (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 131 relations
INFO: Query edges: indigenous American ethnic group, Treaty of Springwells (top_k:20, cosine:0.2)
INFO: Global query: 22 entites, 20 relations
INFO: Raw search results: 41 entities, 149 relations, 0 vector chunks
INFO: After truncation: 41 entities, 149 relations
INFO: Selecting 101 from 101 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 149 relations
INFO: Round-robin merged chunks: 101 -> 101 (deduplicated 0)
INFO: Final context: 41 entities, 149 relations, 8 chunks
INFO: Final chunks S+F/O: E12/1 E6/2 E2/3 E2/4 E8/5 E3/6 E3/7 E2/8
INFO:  == LLM cache == saving: hybrid:query:2848d69517ccef75d1cc9ed79abca87c

[hybrid] 5a75ebfc5542992d0ec06018 | ok | 'The Odawa are an Indigenous American ethnic group that inhabits land in the northern United States and southern Canada and were part of the Treaty of Springwells. \n\n### References\n\n- [1] Odawa'

INFO:  == LLM cache == saving: hybrid:keywords:a83ff5ad9614205aa2024d332659d729
INFO: Query nodes: Colonel Sherman T. Potter, M*A*S*H, Kentucky Jones (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 28 relations
INFO: Query edges: actor roles, television shows, M*A*S*H, Kentucky Jones (top_k:20, cosine:0.2)
INFO: Global query: 28 entites, 20 relations
INFO: Raw search results: 33 entities, 32 relations, 0 vector chunks
INFO: After truncation: 33 entities, 32 relations
INFO: Selecting 7 from 7 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 32 relations
INFO: Round-robin merged chunks: 7 -> 7 (deduplicated 0)
INFO: Final context: 33 entities, 32 relations, 7 chunks
INFO: Final chunks S+F/O: E16/1 E5/2 E7/3 E3/4 E2/5 E2/6 E1/7
INFO:  == LLM cache == saving: hybrid:query:6d857e7613170156233481f5a5d59182

[hybrid] 5ac23f9555429951e9e684db | ok | 'In "Kentucky Jones," the actor who played Colonel Sherman T. Potter in "M*A*S*H," Harry Morgan, portrayed the character Seldom Jackson, a former jockey who assists Dr. Jones. \n\n### References\n\n- [1] Kentucky Jones\n- [2] Harry Morgan'

INFO:  == LLM cache == saving: hybrid:keywords:93e20914ad667c8b9f5a670593421a31
INFO: Query nodes: Posdnuos, Dave, Maseo, Eslam Jawaad (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 34 relations
INFO: Query edges: album release, music history (top_k:20, cosine:0.2)
INFO: Global query: 37 entites, 20 relations
INFO: Raw search results: 56 entities, 52 relations, 0 vector chunks
INFO: After truncation: 56 entities, 52 relations
INFO: Selecting 46 from 46 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 52 relations
INFO: Round-robin merged chunks: 46 -> 46 (deduplicated 0)
INFO: Final context: 56 entities, 52 relations, 8 chunks
INFO: Final chunks S+F/O: E7/1 E7/2 E3/3 E2/4 E1/5 E2/6 E1/7 E1/8
INFO:  == LLM cache == saving: hybrid:query:7f065c9b3a33d2a8a7818cbae6d8c2f5

[hybrid] 5adccdab5542994d58a2f6db | ok | 'The album featuring the trio made up of Posdnuos, Dave, and Maseo, alongside Lebanese-Syrian rapper Eslam Jawaad, titled "The Mammoth Tusk," was released in 2009. \n\n### References\n* [1] The Mammoth Tusk\n* [2] Eslam Jawaad\n* [3] De La Soul'

INFO:  == LLM cache == saving: hybrid:keywords:b0763fa173bbad04e9a27b5662cd136d
INFO: Query nodes: animals, wall, running (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 34 relations
INFO: Query edges: animal depiction, West Gate Lodge, Cardiff Castle (top_k:20, cosine:0.2)
INFO: Global query: 16 entites, 20 relations
INFO: Raw search results: 34 entities, 48 relations, 0 vector chunks
INFO: After truncation: 34 entities, 48 relations
INFO: Selecting 28 from 28 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 48 relations
INFO: Round-robin merged chunks: 28 -> 28 (deduplicated 0)
INFO: Final context: 34 entities, 48 relations, 8 chunks
INFO: Final chunks S+F/O: E4/1 E5/2 E9/3 E2/4 E1/5 E1/6 E3/7 E4/8
INFO:  == LLM cache == saving: hybrid:query:224ae7029f34fa35d394f918b0266d0c

[hybrid] 5aba14195542994dbf0198a9 | ok | 'The Animal Wall, running between the West Gate Lodge and Cardiff Castle, depicts 15 animals. \n\n### References\n- [1] Animal Wall\n- [2] West Lodge, Cardiff Castle'

INFO:  == LLM cache == saving: hybrid:keywords:1fd77f0a558898c70aca4a3d20783ae3
INFO: Query nodes: Get Off, group (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 36 relations
INFO: Query edges: album, music style, NYC, 1970s (top_k:20, cosine:0.2)
INFO: Global query: 30 entites, 20 relations
INFO: Raw search results: 50 entities, 56 relations, 0 vector chunks
INFO: After truncation: 50 entities, 56 relations
INFO: Selecting 91 from 91 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 56 relations
INFO: Round-robin merged chunks: 91 -> 91 (deduplicated 0)
INFO: Final context: 50 entities, 56 relations, 8 chunks
INFO: Final chunks S+F/O: E2/1 E3/2 E1/3 E4/4 E6/5 E1/6 E1/7 E2/8
INFO:  == LLM cache == saving: hybrid:query:c91e6c0c08e1bf17e136f567e8bc679e

[hybrid] 5ade61fd554299728e26c704 | ok | 'Get Off is an album by the group Foxy, which features the disco style that originated in New York City in the early 1970s.\n\n### References\n\n- [1] Get Off (Foxy album)\n- [2] Disco'

INFO:  == LLM cache == saving: hybrid:keywords:032069721e61766b4d5e8c9d40c6a843
INFO: Query nodes: film, written by (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 24 relations
INFO: Query edges: 2017 American 3D film, Cinco Paul, Ken Daurio (top_k:20, cosine:0.2)
INFO: Global query: 14 entites, 20 relations
INFO: Raw search results: 33 entities, 42 relations, 0 vector chunks
INFO: After truncation: 33 entities, 42 relations
INFO: Selecting 25 from 25 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 42 relations
INFO: Round-robin merged chunks: 25 -> 25 (deduplicated 0)
INFO: Final context: 33 entities, 42 relations, 8 chunks
INFO: Final chunks S+F/O: E8/1 E3/2 E2/3 E3/4 E3/5 E3/6 E3/7 E3/8
INFO:  == LLM cache == saving: hybrid:query:dfd4c1fa980d8bf900faee02eda12aaf

[hybrid] 5a77d25555429949eeb29f6c | ok | 'The 2017 American 3D film written by Cinco Paul and Ken Daurio is **Despicable Me 3**. \n\n### References\n\n- [1] Despicable Me 3'

INFO:  == LLM cache == saving: hybrid:keywords:bfe5a2e19550bad033d0294d191fb636
INFO: Query nodes: Whitford Lodge, branch, bank (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 38 relations
INFO: Query edges: banking history, national bank (top_k:20, cosine:0.2)
INFO: Global query: 25 entites, 20 relations
INFO: Raw search results: 43 entities, 55 relations, 0 vector chunks
INFO: After truncation: 43 entities, 55 relations
INFO: Selecting 52 from 52 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 55 relations
INFO: Round-robin merged chunks: 52 -> 52 (deduplicated 0)
INFO: Final context: 43 entities, 55 relations, 8 chunks
INFO: Final chunks S+F/O: E7/1 E6/2 E7/3 E5/4 E5/5 E3/6 E3/7 E3/8
INFO:  == LLM cache == saving: hybrid:query:c1c7277e1d51c14d4c77bc075112ad29

[hybrid] 5ac3b4cc554299741d48a2eb | ok | 'Whitford Lodge once housed a branch of the Hudson United Bank, which later became TD Bank. \n\n### References\n\n- [1] Whitford Lodge'

INFO:  == LLM cache == saving: hybrid:keywords:859f7b72b490d0f7fb5e068fee859034
INFO: Query nodes: Jessica Jones, miniseries (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 63 relations
INFO: Query edges: television series, Netflix, The Defenders, show release (top_k:20, cosine:0.2)
INFO: Global query: 17 entites, 20 relations
INFO: Raw search results: 30 entities, 67 relations, 0 vector chunks
INFO: After truncation: 30 entities, 67 relations
INFO: Selecting 17 from 17 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 67 relations
INFO: Round-robin merged chunks: 17 -> 17 (deduplicated 0)
INFO: Final context: 30 entities, 67 relations, 8 chunks
INFO: Final chunks S+F/O: E8/1 E12/2 E10/3 E5/4 E3/5 E10/6 E6/7 E8/8
INFO:  == LLM cache == saving: hybrid:query:8466e84133bf2e5f339b65e8988e1933

[hybrid] 5a87081755429960ec39b6fe | ok | 'Jessica Jones is the second series in the lineup of shows that lead to "The Defenders" miniseries, following the release of "Daredevil" on Netflix earlier. \n\n### References\n\n- [1] Jessica Jones (TV series)\n- [2] Daredevil (TV series)'

INFO:  == LLM cache == saving: hybrid:keywords:d08aa26efde247032198fd3460e9bc0f
INFO: Query nodes: opposite (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 29 relations
INFO: Query edges: British drama film, Billy Howle, Dominic Cooke (top_k:20, cosine:0.2)
INFO: Global query: 28 entites, 20 relations
INFO: Raw search results: 48 entities, 49 relations, 0 vector chunks
INFO: After truncation: 48 entities, 49 relations
INFO: Selecting 33 from 33 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 49 relations
INFO: Round-robin merged chunks: 33 -> 33 (deduplicated 0)
INFO: Final context: 48 entities, 49 relations, 8 chunks
INFO: Final chunks S+F/O: E9/1 E4/2 E3/3 E4/4 E3/5 E2/6 E2/7 E2/8
INFO:  == LLM cache == saving: hybrid:query:78fa5b9b8d2c87addba8eca350fce1ec

[hybrid] 5add2b435542990d50227e11 | ok | 'Billy Howle will be seen opposite Saoirse Ronan in the upcoming British drama film directed by Dominic Cooke, "On Chesil Beach."\n\n### References\n\n- [1] Billy Howle\n- [2] On Chesil Beach (film)'

INFO:  == LLM cache == saving: hybrid:keywords:4f6581b7286e286b48bf158c00ff7d62
INFO: Query nodes: Sonny (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 22 relations
INFO: Query edges: teacher, actress, killed off (top_k:20, cosine:0.2)
INFO: Global query: 38 entites, 20 relations
INFO: Raw search results: 56 entities, 40 relations, 0 vector chunks
INFO: After truncation: 56 entities, 40 relations
INFO: Selecting 29 from 29 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 40 relations
INFO: Round-robin merged chunks: 29 -> 29 (deduplicated 0)
INFO: Final context: 56 entities, 40 relations, 8 chunks
INFO: Final chunks S+F/O: E6/1 E6/2 E9/3 E2/4 E1/5 E3/6 E2/7 E2/8
INFO:  == LLM cache == saving: hybrid:query:163c3151a403591c355b24a7a4ed5874

[hybrid] 5a8750945542996432c57264 | ok | 'The actress who was killed off along with Sonny Valentine is Gemma Merna, who portrayed Carmel McQueen in "Hollyoaks." She is known for her comedic personality and has become notable for her "dumb blonde" appearance. In terms of her role, she played a character that was involved in significant storylines, including her sacrifice to save her cousin. \n\nHowever, there is no information in the provided context suggesting that Gemma Merna had a character specifically identified as a teacher in the soap opera. \n\n### References\n\n- [1] Sonny Valentine\n- [2] Carmel McQueen'

INFO:  == LLM cache == saving: hybrid:keywords:4c634eb195fa96d575d5a27dee12ff58
INFO: Query nodes: Michael Polcino, Dominic (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 34 relations
INFO: Query edges: animated sitcom, setting (top_k:20, cosine:0.2)
INFO: Global query: 29 entites, 20 relations
INFO: Raw search results: 49 entities, 54 relations, 0 vector chunks
INFO: After truncation: 49 entities, 54 relations
INFO: Selecting 61 from 61 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 54 relations
INFO: Round-robin merged chunks: 61 -> 61 (deduplicated 0)
INFO: Final context: 49 entities, 54 relations, 8 chunks
INFO: Final chunks S+F/O: E6/1 E4/2 E4/3 E3/4 E3/5 E3/6 E2/7 E3/8
INFO:  == LLM cache == saving: hybrid:query:7a53a8299dac2ae1f258e78852bc8d2f

[hybrid] 5a8f8e4d55429918e830d260 | ok | 'The setting for the animated sitcom that Dominic Polcino works on, which is "Family Guy," is the fictional city of Quahog, Rhode Island. \n\n### References\n* [1] Family Guy\n* [2] Dominic Polcino'

INFO:  == LLM cache == saving: hybrid:keywords:085f852d7e180c8bf6f42ddda55e0771
INFO: Query nodes: 25 miles, south, Groom Lake (top_k:20, cosine:0.2)
INFO: Local query: 20 entites, 43 relations
INFO: Query edges: geography, locations, Groom Lake (top_k:20, cosine:0.2)
INFO: Global query: 20 entites, 20 relations
INFO: Raw search results: 29 entities, 46 relations, 0 vector chunks
INFO: After truncation: 29 entities, 46 relations
INFO: Selecting 19 from 19 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 46 relations
INFO: Round-robin merged chunks: 19 -> 19 (deduplicated 0)
INFO: Final context: 29 entities, 46 relations, 8 chunks
INFO: Final chunks S+F/O: E8/1 E5/2 E6/3 E5/4 E2/5 E4/6 E1/7 E2/8
INFO:  == LLM cache == saving: hybrid:query:44a4be5306fd99ef07dbb77bd82fc6f5

[hybrid] 5adfff0755429925eb1afbce | ok | '25 miles south of Groom Lake is the town of Rachel, Nevada. \n\n### References\n\n- [1] Rachel, Nevada'
Saved: hotpot_lightrag/experiment_data/lightrag_predictions.jsonl

## 4. 将长回答规范化为短答案（推荐执行）

LightRAG 的回答有时会忽略 `response_type` 并输出完整解释。这个单元格使用独立的低成本模型，只从原始回答中抽取最终答案；它不允许使用外部知识来修正答案。原始回答始终保留在 `raw_prediction`，短答案写到新的 JSONL，因而可以安全重跑或审计。

> 该后处理会对每条成功预测增加一次短模型调用。

In [ ]:
from openai import AsyncOpenAI

NORMALIZED_PREDICTIONS_PATH = DATA_DIR / 'lightrag_short_predictions.jsonl'
normalizer_client = AsyncOpenAI(api_key=os.environ['OPENAI_API_KEY'])

async def extract_final_answer(question, long_answer):
    prompt = f"""You are a strict answer-formatting function.

Question: {question}
Model answer: {long_answer}

Extract only the shortest final answer stated by the model answer.
Do not explain, cite evidence, add words, or use outside knowledge to correct it.
If the model answer explicitly says the answer cannot be determined, return exactly: Cannot be determined from the provided context.
Return only the answer text.
"""
    completion = await normalizer_client.chat.completions.create(
        model=ANSWER_NORMALIZER_MODEL,
        messages=[
            {'role': 'system', 'content': 'Return only the final short answer.'},
            {'role': 'user', 'content': prompt},
        ],
        temperature=0,
        max_tokens=32,
    )
    return completion.choices[0].message.content.strip()

raw_records = [json.loads(line) for line in PREDICTIONS_PATH.read_text(encoding='utf-8').splitlines() if line.strip()]
already_normalized = set()
if NORMALIZED_PREDICTIONS_PATH.exists():
    for line in NORMALIZED_PREDICTIONS_PATH.read_text(encoding='utf-8').splitlines():
        try:
            previous = json.loads(line)
            if previous.get('normalization_status') == 'ok':
                already_normalized.add((previous.get('mode'), previous.get('id')))
        except json.JSONDecodeError:
            pass

for raw in tqdm(raw_records, desc='Normalizing answers'):
    key = (raw.get('mode'), raw.get('id'))
    if raw.get('status') != 'ok' or key in already_normalized:
        continue
    started = time.time()
    record = {**raw, 'raw_prediction': raw.get('prediction', '')}
    try:
        record['prediction'] = await extract_final_answer(record['question'], record['raw_prediction'])
        record['normalization_status'] = 'ok'
    except Exception as error:
        record['prediction'] = record['raw_prediction']
        record['normalization_status'] = 'error'
        record['normalization_error'] = repr(error)
    record['normalization_seconds'] = round(time.time() - started, 3)
    with NORMALIZED_PREDICTIONS_PATH.open('a', encoding='utf-8') as handle:
        handle.write(json.dumps(record, ensure_ascii=False) + '\n')

print('Saved:', NORMALIZED_PREDICTIONS_PATH)

Normalizing answers:   0%|          | 0/200 [00:00<?, ?it/s]

Saved: hotpot_lightrag/experiment_data/lightrag_short_predictions.jsonl

## 5. Answer EM / F1 与结果导出

这部分沿用 HotpotQA/SQuAD 风格的答案规范化。LightRAG 的 SDK 输出不是原始 `(title, sentence_id)` supporting facts，因此此版本只将 Answer EM/F1 作为主要指标；空 `sp` 不能用于解读 Support 或 Joint F1。

In [ ]:
def normalize_answer(text):
    text = str(text).lower()
    text = ''.join(char for char in text if char not in string.punctuation)
    text = re.sub(r'\b(a|an|the)\b', ' ', text)
    return ' '.join(text.split())

def exact_match(prediction, gold):
    return float(normalize_answer(prediction) == normalize_answer(gold))

def token_f1(prediction, gold):
    prediction_tokens = normalize_answer(prediction).split()
    gold_tokens = normalize_answer(gold).split()
    if not prediction_tokens or not gold_tokens:
        return float(prediction_tokens == gold_tokens)
    overlap = sum((Counter(prediction_tokens) & Counter(gold_tokens)).values())
    if overlap == 0:
        return 0.0
    precision = overlap / len(prediction_tokens)
    recall = overlap / len(gold_tokens)
    return 2 * precision * recall / (precision + recall)

# 优先评测规范化后的短答案；若尚未运行上一单元格，则回退到原始长回答。
EVALUATED_PREDICTIONS_PATH = (NORMALIZED_PREDICTIONS_PATH
                              if NORMALIZED_PREDICTIONS_PATH.exists()
                              else PREDICTIONS_PATH)
records = [json.loads(line) for line in EVALUATED_PREDICTIONS_PATH.read_text(encoding='utf-8').splitlines() if line.strip()]
# 断点续跑可能留下同一题的旧失败记录；只保留每个 (mode, id) 的最新记录。
latest_records = {}
for record in records:
    latest_records[(record.get('mode'), record.get('id'))] = record
records = list(latest_records.values())
df = pd.DataFrame(records)
ok = df[df['status'].eq('ok')].copy()
ok['EM'] = ok.apply(lambda row: exact_match(row['prediction'], row['gold_answer']), axis=1)
ok['F1'] = ok.apply(lambda row: token_f1(row['prediction'], row['gold_answer']), axis=1)
summary = (ok.groupby('mode', as_index=False)
           .agg(questions=('id', 'count'), answer_em=('EM', 'mean'),
                answer_f1=('F1', 'mean'), avg_seconds=('seconds', 'mean'))
           .sort_values('mode'))
display(summary)
display(ok[['mode', 'question', 'gold_answer', 'prediction', 'EM', 'F1', 'seconds']].head(20))

EVALUATION_PATH = DATA_DIR / 'lightrag_evaluation.json'
EVALUATION_PATH.write_text(
    json.dumps({'config': {'num_questions': NUM_QUESTIONS, 'seed': RANDOM_SEED,
                           'chat_model': CHAT_MODEL, 'embedding_model': EMBEDDING_MODEL},
                'summary': summary.to_dict(orient='records'),
                'records': records}, ensure_ascii=False, indent=2),
    encoding='utf-8',
)
print('Evaluated:', EVALUATED_PREDICTIONS_PATH)
print('Saved:', EVALUATION_PATH)

     mode  questions  answer_em  answer_f1  avg_seconds
0  hybrid        200        0.5   0.691456      3.37258

,mode,question,gold_answer,prediction,EM,F1,seconds
0,hybrid,What Dutch painter specialized in domestic int...,Johannes Vermeer,Johannes Vermeer,1.0,1.000000,0.370
1,hybrid,Aughton Park railway station is on a branch of...,12+3/4 mi northeast of Liverpool,approximately 11½ miles (19 km) northeast of L...,0.0,0.428571,2.916
2,hybrid,Who is the son of the author of the short stor...,Benjamin Hale Cheever,Benjamin Cheever,0.0,0.800000,2.819
3,hybrid,One of the members of Dru Hill is nicknamed af...,Woody Woodpecker,Woody Woodpecker,1.0,1.000000,3.797
4,hybrid,"How many records did the singer who sang ""Four...",140 million,Cannot be determined from the provided context.,0.0,0.000000,2.937
5,hybrid,The director of a film about Wong Fei-hung als...,"""The 36th Chamber of Shaolin""","""Warriors Two.""",0.0,0.000000,2.752
6,hybrid,Both Bishop Carroll Catholic High School and K...,Wichita,"Wichita, Kansas.",0.0,0.666667,3.111
7,hybrid,Luke Rockhold defeated the MMA fighter who was...,Anderson Silva,Anderson Silva,1.0,1.000000,4.706
8,hybrid,Who wrote the novel that the movie directed by...,Stephen King,Stephen King,1.0,1.000000,3.220
9,hybrid,What is the name of the daughter of the Irish ...,Chloë Alexandra Adele Emily Agnew,Chloë Agnew,0.0,0.571429,2.969
10,hybrid,In which year did Baek Bong-ki appear in the S...,2004,2004,1.0,1.000000,2.971
11,hybrid,How long is the river for which Frenchmans Cre...,2844 km,1472 km,0.0,0.500000,4.043
12,hybrid,In which six Western European territories have...,"Brittany, Cornwall, Ireland, Isle of Man, Scot...","Brittany, Cornwall, Ireland, Isle of Man, Scot...",0.0,0.941176,3.458
13,hybrid,Clone of clones played alongside a band from w...,"Cleveland, Ohio","Cleveland, Ohio",1.0,1.000000,3.118
14,hybrid,Which episode of SpongeBob SquarePants aired f...,To SquarePants or Not to SquarePants,The Clash of Triton,0.0,0.000000,3.604
15,hybrid,Grown-Ups starred the actor who was best known...,Captain Hans Geering,Captain Hans Geering,1.0,1.000000,3.491
16,hybrid,When was the seven-time World and Olympic meda...,"June 6, 1959","June 6, 1959",1.0,1.000000,3.331
17,hybrid,Grimsby Minster is located in which English Pr...,Province of Canterbury,Province of Canterbury,1.0,1.000000,3.102
18,hybrid,Toni Braxton: Revealed was performed at a hote...,Caesars Entertainment Corporation,Caesars Entertainment Corporation.,1.0,1.000000,4.124
19,hybrid,Padosan had a supporting actor who is known as...,Hindi,Hindi,1.0,1.000000,3.184

Evaluated: hotpot_lightrag/experiment_data/lightrag_short_predictions.jsonl
Saved: hotpot_lightrag/experiment_data/lightrag_evaluation.json

In [ ]:
# 可选：导出为 HotpotQA 预测文件。sp 暂为空，故不要将其 Joint F1 作为 LightRAG 的真实表现。
def export_hotpot_answers(frame, mode):
    selected = frame[(frame['mode'] == mode) & (frame['status'] == 'ok')]
    payload = {
        'answer': dict(zip(selected['id'], selected['prediction'])),
        'sp': {question_id: [] for question_id in selected['id']},
    }
    target = DATA_DIR / f'lightrag_{mode}_hotpot_predictions.json'
    target.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding='utf-8')
    return target

for mode in QUERY_MODES:
    print(export_hotpot_answers(df, mode))

hotpot_lightrag/experiment_data/lightrag_hybrid_hotpot_predictions.json

## 下一步：使其成为更严格的 HotpotQA 实验

- 将 `QUERY_MODES` 改为 `['naive', 'local', 'global', 'hybrid']`，比较同一索引下的模式差异。
- 将 `NUM_QUESTIONS` 改为 200；保持 seed、模型、chunk 参数不变。
- 对回答后返回的 source chunk 做标题/句子切分匹配，生成 `supporting_facts`，再运行官方 `hotpot_evaluate_v1.py` 计算 Support/Joint 指标。
- 若目标是可与 FullWiki 工作横向比较的结果，需要替换为完整 Wikipedia 检索语料，而不是此处的 distractor 候选段落池。